/** IPC channel names — preload-safe (no Zod). */
export const IPC = {
  pickWorkspace: 'workspace:pick',
  workspacesGet: 'workspaces:get',
  /** The app's own scratch folder, open whenever no project is. */
  workspacesHome: 'workspaces:home',
  /** New task briefs put aside with Save as draft, per workspace. */
  taskDraftsList: 'drafts:list',
  taskDraftsSave: 'drafts:save',
  taskDraftsDelete: 'drafts:delete',
  /** Whether a task's last rewind can still be redone, and redoing it. */
  runRewindRedoStatus: 'runs:rewindRedoStatus',
  runRewindRedo: 'runs:rewindRedo',
  /** A whole task in its own git worktree: make one, read it, merge it back, delete it. */
  taskWorktreeCreate: 'worktrees:create',
  taskWorktreeInfo: 'worktrees:info',
  taskWorktreeMerge: 'worktrees:merge',
  taskWorktreeDiscard: 'worktrees:discard',
  /** Tasks that repeat on a schedule while the app is open. */
  schedulesList: 'schedules:list',
  schedulesCreate: 'schedules:create',
  schedulesUpdate: 'schedules:update',
  schedulesDelete: 'schedules:delete',
  schedulesToggle: 'schedules:toggle',
  schedulesRunNow: 'schedules:run-now',
  /** What Repeat… would repeat: a task's brief, model and worktree, read from its record. */
  schedulesSource: 'schedules:source',
  /** Main → renderer: open a scheduled run's new worktree as a workspace. */
  schedulesWorktreeOpen: 'schedules:worktree-open',
  /** Renderer → main: that worktree is open (or why not); main starts the run. */
  schedulesWorktreeOpened: 'schedules:worktree-opened',
  workspacesAdd: 'workspaces:add',
  workspacesRemove: 'workspaces:remove',
  workspacesSetActive: 'workspaces:set-active',
  workspacesUpdateUiState: 'workspaces:update-ui-state',
  workspacesUpdateUiStateSync: 'workspaces:update-ui-state-sync',
  workspacesSetSettingsOverride: 'workspaces:set-settings-override',
  /** Persisted composer attachment buckets (images / files / audio) per workspace+run key. */
  composerAttachmentsGet: 'composer-attachments:get',
  composerAttachmentsSet: 'composer-attachments:set',
  composerAttachmentsClear: 'composer-attachments:clear',
  getSettings: 'settings:get',
  /** Main → renderer: settings as just written, by anyone (main included). */
  settingsChanged: 'settings:changed',
  setSettings: 'settings:set',
  setSecret: 'secrets:set',
  clearSecret: 'secrets:clear',
  secretStatus: 'secrets:status',
  googleAdcStatus: 'providers:google-adc-status',
  networkProxyStatus: 'network:proxy-status',
  listModels: 'models:list',
  chatStart: 'chat:start',
  chatCancel: 'chat:cancel',
  chatRewindAndStart: 'chat:rewindAndStart',
  chatRewind: 'chat:rewind',
  /** Read-only preview of which files a chatRewind would restore. */
  chatRewindPreview: 'chat:rewindPreview',
  chatFollowUp: 'chat:followUp',
  chatFollowUpRemove: 'chat:followUpRemove',
  chatFollowUpUpdate: 'chat:followUpUpdate',
  chatFollowUpPromote: 'chat:followUpPromote',
  chatQueueMode: 'chat:queueMode',
  chatEvent: 'chat:event',
  /** Renderer tells main which runIds currently want token streams. */
  chatUiSubscribe: 'chat:ui-subscribe',
  /** Renderer adds one run to the subscribed set the moment it starts. */
  chatUiSubscribeAdd: 'chat:ui-subscribe-add',
  chatCompact: 'chat:compact',
  toolApprovalRequest: 'tool:approval-request',
  toolApprovalResponse: 'tool:approval-response',
  toolApprovalListPending: 'tool:approval-list-pending',
  agentQuestionRequest: 'agent:question-request',
  agentQuestionResponse: 'agent:question-response',
  agentQuestionReject: 'agent:question-reject',
  agentQuestionListPending: 'agent:question-list-pending',
  attachmentExtract: 'attachment:extract',
  dictationTranscribe: 'dictation:transcribe',
  dictationCancel: 'dictation:cancel',
  dictationPrepare: 'dictation:prepare',
  dictationTakeStats: 'dictation:takeStats',
  dictationLiveOpen: 'dictation:liveOpen',
  dictationLiveAudio: 'dictation:liveAudio',
  dictationLiveCommit: 'dictation:liveCommit',
  dictationLiveClose: 'dictation:liveClose',
  dictationLiveEvent: 'dictation:liveEvent',
  dictationStatus: 'dictation:status',
  dictationStatusEvent: 'dictation:status-event',
  dictationInstall: 'dictation:install',
  dictationUnload: 'dictation:unload',
  dictationDeleteCache: 'dictation:deleteCache',
  dictationMicAccess: 'dictation:micAccess',
  dictationOpenMicSettings: 'dictation:openMicSettings',
  listRuns: 'runs:list',
  listOlderRuns: 'runs:listOlder',
  loadRun: 'runs:load',
  loadEarlierMessages: 'runs:load-earlier',
  loadRunEvents: 'runs:events',
  loadToolResult: 'runs:tool-result',
  runsDelete: 'runs:delete',
  runsExport: 'runs:export',
  runsRename: 'runs:rename',
  runsFork: 'runs:fork',
  runsActive: 'runs:active',
  runsResolveWrites: 'runs:resolveWrites',
  runsReopenWrites: 'runs:reopenWrites',
  runsTaskOutcome: 'runs:taskOutcome',
  runsUndoTaskCommit: 'runs:undoTaskCommit',
  runsReadArtifact: 'runs:readArtifact',
  runsOpenArtifact: 'runs:openArtifact',
  runsTaskFileStats: 'runs:taskFileStats',
  runsTaskFileDiff: 'runs:taskFileDiff',
  runsPickExtraRoot: 'runs:pickExtraRoot',
  runsSetExtraRoots: 'runs:setExtraRoots',
  runsUndoHunk: 'runs:undoHunk',
  runsRestoreHunk: 'runs:restoreHunk',
  homeActivity: 'runs:activity',
  // Usage page → Export CSV (save dialog in main), and task bundles as JSON.
  usageExportCsv: 'usage:export-csv',
  runsExportJson: 'runs:export-json',
  runsImport: 'runs:import',
  runsSetGoalStatus: 'runs:setGoalStatus',
  runsSetLoop: 'runs:setLoop',
  // Per-run user verdict. Namespaced away from `feedback:compose`, which is
  // the unrelated app-level bug report.
  runFeedbackGet: 'runs:feedback:get',
  runsSearch: 'runs:search',
  settingsExport: 'settings:export',
  settingsImportPreview: 'settings:import-preview',
  settingsImportApply: 'settings:import-apply',
  settingsReset: 'settings:reset',
  runFeedbackSet: 'runs:feedback:set',
  browserState: 'browser:state',
  browserGetState: 'browser:getState',
  browserFocus: 'browser:focus',
  browserClose: 'browser:close',
  browserSelectTab: 'browser:selectTab',
  browserOpenTab: 'browser:openTab',
  browserCloseTab: 'browser:closeTab',
  browserTakeControl: 'browser:takeControl',
  browserReleaseControl: 'browser:releaseControl',
  browserBack: 'browser:back',
  browserForward: 'browser:forward',
  browserSetBounds: 'browser:setBounds',
  browserNavigate: 'browser:navigate',
  browserReload: 'browser:reload',
  browserTakeScreenshot: 'browser:takeScreenshot',
  browserClearBrowsingData: 'browser:clearBrowsingData',
  browserPipToggle: 'browser:pipToggle',
  browserPickStart: 'browser:pickStart',
  browserPickStop: 'browser:pickStop',
  browserElementPicked: 'browser:elementPicked',
  gitStatus: 'git:status',
  gitGenerateCommitMessage: 'git:generate-commit-message',
  gitCommit: 'git:commit',
  gitStageAll: 'git:stage-all',
  gitStagePaths: 'git:stage-paths',
  gitUnstagePaths: 'git:unstage-paths',
  gitBranches: 'git:branches',
  gitCheckout: 'git:checkout',
  /** Sync, user-initiated only: fetch every remote, pull (ff-only by default), push, new branch. */
  gitFetch: 'git:fetch',
  gitPull: 'git:pull',
  gitPush: 'git:push',
  gitCreateBranch: 'git:create-branch',
  gitLog: 'git:log',
  gitCommitFiles: 'git:commit-files',
  gitBlame: 'git:blame',
  /** Manual, user-initiated `git init` for an open workspace. */
  gitInit: 'git:init',
  /** Let the app's git run the programs this repository's own settings name. */
  gitAllowRepoCommands: 'git:allow-repo-commands',
  gitStatusChanged: 'git:status-changed',
  windowMinimize: 'window:minimize',
  windowMaximize: 'window:maximize',
  windowClose: 'window:close',
  windowIsMaximized: 'window:isMaximized',
  windowMaximizedChanged: 'window:maximized-changed',
  windowFocusChanged: 'window:focus-changed',
  workspaceEditorFlushRequest: 'workspace:editor-flush-request',
  workspaceEditorFlushResponse: 'workspace:editor-flush-response',
  logsOpenDir: 'logs:open-dir',
  logsGetPath: 'logs:get-path',
  traceStop: 'perf:trace-stop',
  crashDiagnosticsGet: 'crash:diagnostics-get',
  crashRecoveryConsume: 'crash:recovery-consume',
  telemetryStatus: 'telemetry:status',
  appInfo: 'app:info',
  /** Whether agent commands can be OS-sandboxed here (Settings → Tools → Sandbox). */
  sandboxCapability: 'sandbox:capability',
  updaterState: 'updater:state',
  updaterGetState: 'updater:get-state',
  updaterCheck: 'updater:check',
  updaterDownload: 'updater:download',
  updaterInstall: 'updater:install',
  feedbackCompose: 'feedback:compose',
  /** Save a redacted .zip of version, logs, crashes, memory and settings (Settings → Diagnostics). */
  diagnosticsExport: 'diagnostics:export',
  workspaceGrep: 'workspace:grep',
  gitConflictFile: 'git:conflict-file',
  gitResolveConflict: 'git:resolve-conflict',
  prReview: 'pr:review',
  githubIssuesList: 'github:issues-list',
  githubIssueCreate: 'github:issue-create',
  mcpStatus: 'mcp:status',
  mcpRefresh: 'mcp:refresh',
  mcpSetAuthToken: 'mcp:setAuthToken',
  mcpClearAuthToken: 'mcp:clearAuthToken',
  mcpSetOAuthClientSecret: 'mcp:setOAuthClientSecret',
  mcpClearOAuthClientSecret: 'mcp:clearOAuthClientSecret',
  mcpSetGoogleClientSecret: 'mcp:setGoogleClientSecret',
  mcpClearGoogleClientSecret: 'mcp:clearGoogleClientSecret',
  mcpStartOAuth: 'mcp:startOAuth',
  /** Locate an MCP launch binary on disk when it is not on PATH. */
  mcpPickBinary: 'mcp:pickBinary',
  toolsCatalogGet: 'tools-catalog:get',
  toolsCatalogChanged: 'tools-catalog:changed',
  marketplaceListInstalled: 'marketplace:listInstalled',
  marketplaceBrowse: 'marketplace:browse',
  marketplaceRefreshCatalog: 'marketplace:refreshCatalog',
  marketplaceInstall: 'marketplace:install',
  marketplaceDetectMcp: 'marketplace:detectMcp',
  marketplaceApplyDetectedMcp: 'marketplace:applyDetectedMcp',
  marketplaceScanExternalMcp: 'marketplace:scanExternalMcp',
  marketplaceImportExternalMcp: 'marketplace:importExternalMcp',
  marketplaceUninstall: 'marketplace:uninstall',
  marketplaceSetEnabled: 'marketplace:setEnabled',
  marketplacePickLocal: 'marketplace:pickLocal',
  marketplaceGetContents: 'marketplace:getContents',
  marketplaceAckRemoteInstall: 'marketplace:ack-remote-install',
  slashCommandsList: 'slash-commands:list',
  slashCommandsResolve: 'slash-commands:resolve',
  slashCommandsCreateRule: 'slash-commands:createRule',
  slashCommandsCreateSkill: 'slash-commands:createSkill',
  slashCommandsOpenFile: 'slash-commands:openFile',
  skillsListLocal: 'skills:listLocal',
  skillsOpenLocal: 'skills:openLocal',
  skillsReadLocal: 'skills:readLocal',
  skillsWriteLocal: 'skills:writeLocal',
  skillsDeleteLocal: 'skills:deleteLocal',
  skillsChanged: 'skills:changed',
  workspaceSuggestPaths: 'workspace:suggestPaths',
  workspaceReadText: 'workspace:readText',
  workspaceReadImage: 'workspace:readImage',
  workspaceFileList: 'workspace:file-list',
  workspaceFileRead: 'workspace:file-read',
  workspaceFileStat: 'workspace:file-stat',
  accessibilitySupportState: 'app:accessibility-state',
  accessibilitySupportChanged: 'app:accessibility-changed',
  workspaceFileSave: 'workspace:file-save',
  workspaceFileCreate: 'workspace:file-create',
  workspaceFileMove: 'workspace:file-move',
  workspaceFileDelete: 'workspace:file-delete',
  workspaceFileReveal: 'workspace:file-reveal',
  workspaceFormatterStatus: 'workspace:formatter-status',
  workspaceFormatFile: 'workspace:format-file',
  workspaceLspStatus: 'workspace:lsp-status',
  workspaceLspRequest: 'workspace:lsp-request',
  workspaceEditorRecoverySave: 'workspace:editor-recovery-save',
  workspaceEditorRecoveryLoad: 'workspace:editor-recovery-load',
  workspaceEditorRecoveryClear: 'workspace:editor-recovery-clear',
  workspaceListDocs: 'workspace:listDocs',
  workspaceListRules: 'workspace:listRules',
  agentContext: 'workspace:agentContext',
  /** Live push: a watched workspace's agent-context summary actually changed. */
  agentContextChanged: 'workspace:agent-context-changed',
  /** Delete the workspace's memory notes, index.md and state.md (Settings → Agent). */
  workspaceClearMemory: 'workspace:clearMemory',
  workspaceDiagnostics: 'workspace:diagnostics',
  gitDiff: 'git:diff',
  /** The branch against its base (merge base with the default branch), uncommitted work included. */
  gitBranchDiff: 'git:branch-diff',
  prView: 'pr:view',
  prCreate: 'pr:create',
  prMerge: 'pr:merge',
  prDiff: 'pr:diff',
  prClose: 'pr:close',
  prReady: 'pr:ready',
  prEditTitle: 'pr:edit-title',
  /** Inline review threads (GraphQL: resolved and outdated state included). */
  prReviewThreads: 'pr:review-threads',
  prReviewThreadResolve: 'pr:review-thread-resolve',
  /** Posts a reply on GitHub: only from an explicit button. */
  prReviewThreadReply: 'pr:review-thread-reply',
  /** Recent open pull requests, for a branch that has none. */
  prList: 'pr:list',
  prCheckout: 'pr:checkout',
  githubAuthStatus: 'github:auth-status',
  githubAuthStart: 'github:auth-start',
  githubAuthCancel: 'github:auth-cancel',
  githubAuthLogout: 'github:auth-logout',
  githubAuthStatusEvent: 'github:auth-status-event',
  githubCliInstall: 'github:cli-install',
  shellOpenExternal: 'shell:open-external',
  ptyCreate: 'pty:create',
  ptyList: 'pty:list',
  ptyWrite: 'pty:write',
  ptyResize: 'pty:resize',
  ptyKill: 'pty:kill',
  ptyData: 'pty:data',
  ptyExit: 'pty:exit',
  ptySessionsChanged: 'pty:sessions-changed',
  themeChanged: 'theme:changed',
  getSystemTheme: 'theme:get-system',
  appearancePickCustomCss: 'appearance:pickCustomCss',
  appearanceReadCustomCss: 'appearance:readCustomCss',
  appearanceCustomCssChanged: 'appearance:customCssChanged',
  networkProbe: 'network:probe',
  codeIndexStatus: 'codeindex:status',
  codeIndexStatusEvent: 'codeindex:status-event',
  codeIndexReindex: 'codeindex:reindex',
  /** Stop a workspace's indexing and keep it stopped; resume carries on from what it has. */
  codeIndexPause: 'codeindex:pause',
  codeIndexResume: 'codeindex:resume',
  processMetrics: 'perf:process-metrics',
  notificationsList: 'notifications:list',
  notificationsMarkRead: 'notifications:markRead',
  notificationsDismiss: 'notifications:dismiss',
  notificationsChanged: 'notifications:changed',
  notificationsActivate: 'notifications:activate',
  /** Storage retention (audit H4/H5): report + confirm-gated cleanup + ack. */
  storageReport: 'storage:report',
  storageCleanupPreview: 'storage:cleanup-preview',
  storageCleanupRun: 'storage:cleanup-run',
  storageAckSurface: 'storage:ack-surface',
  dataWipePreview: 'storage:data-wipe-preview',
  dataWipeRun: 'storage:data-wipe-run',
  /** Deep links (vyotiq:// URLs): push on receipt, invoke to drain the pending slot. */
  deepLinkOpened: 'deeplink:opened',
  deepLinkConsume: 'deeplink:consume'
} as const

export type IpcChannel = (typeof IPC)[keyof typeof IPC]
