import type { Icon as PhosphorIcon, IconProps as PhosphorIconProps } from '@phosphor-icons/react'
import {
  ArrowClockwiseIcon,
  ArrowCounterClockwiseIcon,
  ArrowElbowLeftIcon,
  ArrowUpIcon,
  ArrowsClockwiseIcon,
  ArrowsOutIcon,
  BrainIcon,
  BellIcon,
  BrowsersIcon,
  CaretDownIcon,
  CaretRightIcon,
  CheckIcon,
  ChatCircleIcon,
  CircleIcon,
  CircleHalfIcon,
  ColumnsIcon,
  CopyIcon,
  CornersOutIcon,
  DownloadSimpleIcon,
  FlagIcon,
  FileIcon,
  PlugsConnectedIcon,
  FileMagnifyingGlassIcon,
  FileTextIcon,
  FolderIcon,
  FolderMinusIcon,
  FolderOpenIcon,
  FolderPlusIcon,
  GearSixIcon,
  GitBranchIcon,
  GitCommitIcon,
  GitMergeIcon,
  GitPullRequestIcon,
  GlobeIcon,
  HouseIcon,
  ImageIcon,
  InfoIcon,
  KeyboardIcon,
  ListChecksIcon,
  ListIcon,
  MagnifyingGlassIcon,
  MicrophoneIcon,
  MinusIcon,
  MonitorIcon,
  PencilIcon,
  PaperPlaneRightIcon,
  PaperclipIcon,
  PlusIcon,
  RobotIcon,
  ScanIcon,
  SidebarSimpleIcon,
  SlidersHorizontalIcon,
  SparkleIcon,
  SpinnerIcon,
  SquareIcon,
  SquaresFourIcon,
  StackIcon,
  StarIcon,
  StopIcon,
  StorefrontIcon,
  TerminalWindowIcon,
  TrashIcon,
  WarningIcon,
  WrenchIcon,
  XIcon
} from '@phosphor-icons/react'

export type IconProps = PhosphorIconProps & { size?: number }

const ICONS = {
  send: PaperPlaneRightIcon,
  undo: ArrowCounterClockwiseIcon,
  redo: ArrowClockwiseIcon,
  branch: GitBranchIcon,
  pullRequest: GitPullRequestIcon,
  gitMerge: GitMergeIcon,
  gitCommit: GitCommitIcon,
  gitRebase: ArrowElbowLeftIcon,
  revert: ArrowElbowLeftIcon,
  refresh: ArrowsClockwiseIcon,
  arrowUp: ArrowUpIcon,
  stop: StopIcon,
  folder: FolderIcon,
  folderOpen: FolderOpenIcon,
  search: MagnifyingGlassIcon,
  fileSearch: FileMagnifyingGlassIcon,
  file: FileIcon,
  edit: PencilIcon,
  terminal: TerminalWindowIcon,
  chevron: CaretDownIcon,
  chevronRight: CaretRightIcon,
  close: XIcon,
  check: CheckIcon,
  warning: WarningIcon,
  menu: ListIcon,
  plus: PlusIcon,
  panels: SquaresFourIcon,
  gear: GearSixIcon,
  bell: BellIcon,
  copy: CopyIcon,
  monitor: MonitorIcon,
  sliders: SlidersHorizontalIcon,
  folderPlus: FolderPlusIcon,
  folderMinus: FolderMinusIcon,
  doc: FileTextIcon,
  sidebar: SidebarSimpleIcon,
  minimize: MinusIcon,
  maximize: CornersOutIcon,
  // Diagonal arrows — distinct from the corner-bracket window maximize glyph.
  expand: ArrowsOutIcon,
  columns: ColumnsIcon,
  restore: BrowsersIcon,
  image: ImageIcon,
  memory: BrainIcon,
  trash: TrashIcon,
  paperclip: PaperclipIcon,
  mic: MicrophoneIcon,
  circle: CircleIcon,
  circleHalf: CircleHalfIcon,
  square: SquareIcon,
  loader: SpinnerIcon,
  bot: RobotIcon,
  chat: ChatCircleIcon,
  sparkles: SparkleIcon,
  marketplace: StorefrontIcon,
  star: StarIcon,
  cpu: PlugsConnectedIcon,
  plug: WrenchIcon,
  globe: GlobeIcon,
  info: InfoIcon,
  keyboard: KeyboardIcon,
  listTodo: ListChecksIcon,
  download: DownloadSimpleIcon,
  flag: FlagIcon,
  stack: StackIcon,
  folderSearch: MagnifyingGlassIcon,
  scanSearch: ScanIcon,
  home: HouseIcon
} as const satisfies Record<string, PhosphorIcon>

export type IconName = keyof typeof ICONS

export function Icon({
  name,
  size = 24,
  weight = 'bold',
  className,
  ...props
}: IconProps & { name: IconName }) {
  const Cmp = ICONS[name]
  return (
    <Cmp
      size={size}
      weight={weight}
      aria-hidden="true"
      focusable="false"
      className={['inline-block shrink-0 align-middle', className].filter(Boolean).join(' ')}
      {...props}
    />
  )
}
