import { forwardRef } from 'react'
import type { Icon as PhosphorIcon, IconProps as PhosphorIconProps } from '@phosphor-icons/react'
import {
  ArchiveIcon,
  ArrowBendDownRightIcon,
  ArrowClockwiseIcon,
  ArrowCounterClockwiseIcon,
  ArrowDownIcon,
  ArrowElbowLeftIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowSquareOutIcon,
  ArrowUpIcon,
  ArrowsClockwiseIcon,
  ArrowsInSimpleIcon,
  ArrowsOutIcon,
  AsteriskIcon,
  AtIcon,
  BellIcon,
  BookOpenTextIcon,
  BrainIcon,
  BrowserIcon,
  BrowsersIcon,
  CaretDownIcon,
  CaretLeftIcon,
  CaretRightIcon,
  CaretUpIcon,
  ChartBarIcon,
  ChatCircleIcon,
  CheckCircleIcon,
  CheckIcon,
  CheckSquareIcon,
  CircleHalfIcon,
  CircleIcon,
  CloudIcon,
  ClockIcon,
  CodeIcon,
  ColumnsIcon,
  CommandIcon,
  CopyIcon,
  CornersOutIcon,
  CpuIcon,
  CubeIcon,
  CurrencyDollarIcon,
  DatabaseIcon,
  DotsThreeIcon,
  DotsThreeVerticalIcon,
  DownloadSimpleIcon,
  EyeIcon,
  FileIcon,
  FileMagnifyingGlassIcon,
  FilePlusIcon,
  FileTextIcon,
  FlagIcon,
  FolderIcon,
  FolderMinusIcon,
  FolderOpenIcon,
  FolderPlusIcon,
  FolderSimpleIcon,
  FunnelSimpleIcon,
  GaugeIcon,
  GearSixIcon,
  GitBranchIcon,
  GitCommitIcon,
  GitDiffIcon,
  GitForkIcon,
  GitMergeIcon,
  GitPullRequestIcon,
  GlobeIcon,
  HandIcon,
  HashIcon,
  HouseIcon,
  ImageIcon,
  InfoIcon,
  KeyIcon,
  KeyboardIcon,
  LightningIcon,
  LinkIcon,
  ListBulletsIcon,
  ListChecksIcon,
  ListIcon,
  LockSimpleIcon,
  MagnifyingGlassIcon,
  MicrophoneIcon,
  MicrophoneSlashIcon,
  MinusIcon,
  MonitorIcon,
  MoonIcon,
  NotePencilIcon,
  PaperPlaneRightIcon,
  PaperclipIcon,
  PauseIcon,
  PencilIcon,
  PlayIcon,
  PlugsConnectedIcon,
  WifiSlashIcon,
  PlusIcon,
  PulseIcon,
  PushPinIcon,
  PuzzlePieceIcon,
  QuestionIcon,
  ReceiptIcon,
  RepeatIcon,
  RobotIcon,
  RowsIcon,
  ScanIcon,
  ScrollIcon,
  ShieldCheckIcon,
  SidebarSimpleIcon,
  SlidersHorizontalIcon,
  SparkleIcon,
  SpeakerHighIcon,
  SpinnerIcon,
  SquareIcon,
  SquaresFourIcon,
  StackIcon,
  StarIcon,
  StopIcon,
  StorefrontIcon,
  SunIcon,
  SwapIcon,
  TargetIcon,
  TerminalWindowIcon,
  TextAaIcon,
  TextAUnderlineIcon,
  ThumbsDownIcon,
  ThumbsUpIcon,
  TimerIcon,
  TrashIcon,
  TrayIcon,
  TreeStructureIcon,
  UploadSimpleIcon,
  UsersThreeIcon,
  WarningCircleIcon,
  WarningIcon,
  WaveformIcon,
  WrenchIcon,
  XCircleIcon,
  XIcon
} from '@phosphor-icons/react'

export type IconProps = PhosphorIconProps & { size?: number }

/** The navigator toggle's glyph, mirrored: the inspector opens on the right. */
const InspectorIcon: PhosphorIcon = forwardRef<SVGSVGElement, PhosphorIconProps>((props, ref) => (
  <SidebarSimpleIcon ref={ref} mirrored {...props} />
))
InspectorIcon.displayName = 'InspectorIcon'

const ICONS = {
  send: PaperPlaneRightIcon,
  undo: ArrowCounterClockwiseIcon,
  redo: ArrowClockwiseIcon,
  branch: GitBranchIcon,
  pullRequest: GitPullRequestIcon,
  gitMerge: GitMergeIcon,
  gitCommit: GitCommitIcon,
  gitRebase: ArrowElbowLeftIcon,
  revert: ArrowElbowLeftIcon,
  refresh: ArrowsClockwiseIcon,
  arrowDown: ArrowDownIcon,
  arrowUp: ArrowUpIcon,
  stop: StopIcon,
  folder: FolderIcon,
  folderOpen: FolderOpenIcon,
  search: MagnifyingGlassIcon,
  fileSearch: FileMagnifyingGlassIcon,
  file: FileIcon,
  edit: PencilIcon,
  terminal: TerminalWindowIcon,
  chevron: CaretDownIcon,
  chevronRight: CaretRightIcon,
  close: XIcon,
  check: CheckIcon,
  warning: WarningIcon,
  menu: ListIcon,
  plus: PlusIcon,
  pulse: PulseIcon,
  panels: SquaresFourIcon,
  gear: GearSixIcon,
  bell: BellIcon,
  copy: CopyIcon,
  more: DotsThreeIcon,
  monitor: MonitorIcon,
  sliders: SlidersHorizontalIcon,
  folderPlus: FolderPlusIcon,
  folderMinus: FolderMinusIcon,
  doc: FileTextIcon,
  sidebar: SidebarSimpleIcon,
  inspector: InspectorIcon,
  minimize: MinusIcon,
  maximize: CornersOutIcon,
  // Diagonal arrows — distinct from the corner-bracket window maximize glyph.
  expand: ArrowsOutIcon,
  columns: ColumnsIcon,
  restore: BrowsersIcon,
  image: ImageIcon,
  memory: BrainIcon,
  trash: TrashIcon,
  paperclip: PaperclipIcon,
  mic: MicrophoneIcon,
  micSlash: MicrophoneSlashIcon,
  cloud: CloudIcon,
  circle: CircleIcon,
  circleHalf: CircleHalfIcon,
  square: SquareIcon,
  loader: SpinnerIcon,
  bot: RobotIcon,
  chat: ChatCircleIcon,
  sparkles: SparkleIcon,
  marketplace: StorefrontIcon,
  star: StarIcon,
  cpu: CpuIcon,
  plug: WrenchIcon,
  globe: GlobeIcon,
  info: InfoIcon,
  keyboard: KeyboardIcon,
  listTodo: ListChecksIcon,
  download: DownloadSimpleIcon,
  upload: UploadSimpleIcon,
  flag: FlagIcon,
  thumbsUp: ThumbsUpIcon,
  thumbsDown: ThumbsDownIcon,
  stack: StackIcon,
  folderSearch: MagnifyingGlassIcon,
  scanSearch: ScanIcon,
  home: HouseIcon,

  // Work record redesign (src/redesign) — names the new surfaces use.
  inbox: TrayIcon,
  tasks: ListChecksIcon,
  extensions: PuzzlePieceIcon,
  command: CommandIcon,
  minus: MinusIcon,
  moreV: DotsThreeVerticalIcon,
  chevronUp: CaretUpIcon,
  chevronLeft: CaretLeftIcon,
  arrowLeft: ArrowLeftIcon,
  arrowRight: ArrowRightIcon,
  enter: ArrowBendDownRightIcon,
  external: ArrowSquareOutIcon,
  collapse: ArrowsInSimpleIcon,
  rows: RowsIcon,
  grid: SquaresFourIcon,
  list: ListBulletsIcon,
  filter: FunnelSimpleIcon,
  pin: PushPinIcon,
  archive: ArchiveIcon,
  sun: SunIcon,
  moon: MoonIcon,
  commit: GitCommitIcon,
  diff: GitDiffIcon,
  fork: GitForkIcon,
  merge: GitMergeIcon,
  fileNew: FilePlusIcon,
  workspace: FolderSimpleIcon,
  browser: BrowserIcon,
  code: CodeIcon,
  note: NotePencilIcon,
  tree: TreeStructureIcon,
  database: DatabaseIcon,
  plan: ListChecksIcon,
  checklist: CheckSquareIcon,
  receipt: ReceiptIcon,
  target: TargetIcon,
  repeat: RepeatIcon,
  crew: UsersThreeIcon,
  robot: RobotIcon,
  model: CubeIcon,
  effort: LightningIcon,
  rules: ScrollIcon,
  book: BookOpenTextIcon,
  skill: SparkleIcon,
  mcp: PlugsConnectedIcon,
  offline: WifiSlashIcon,
  tool: WrenchIcon,
  hash: HashIcon,
  link: LinkIcon,
  at: AtIcon,
  waveform: WaveformIcon,
  speaker: SpeakerHighIcon,
  key: KeyIcon,
  lock: LockSimpleIcon,
  shield: ShieldCheckIcon,
  hand: HandIcon,
  eye: EyeIcon,
  play: PlayIcon,
  pause: PauseIcon,
  retry: ArrowClockwiseIcon,
  clock: ClockIcon,
  timer: TimerIcon,
  cost: CurrencyDollarIcon,
  gauge: GaugeIcon,
  chart: ChartBarIcon,
  question: QuestionIcon,
  warningCircle: WarningCircleIcon,
  checkCircle: CheckCircleIcon,
  xCircle: XCircleIcon,
  /** Find options: match case, whole word, regular expression; and replace. */
  matchCase: TextAaIcon,
  wholeWord: TextAUnderlineIcon,
  regex: AsteriskIcon,
  replace: SwapIcon
} as const satisfies Record<string, PhosphorIcon>

export type IconName = keyof typeof ICONS

/**
 * Regular weight by default: bold reads heavy at 16px in a dense layout. Bold
 * stays available for 12px-and-under call sites that pass it.
 */
export function Icon({
  name,
  size = 24,
  weight = 'regular',
  className,
  ...props
}: IconProps & { name: IconName }) {
  const Cmp = ICONS[name]
  return (
    <Cmp
      size={size}
      weight={weight}
      aria-hidden="true"
      focusable="false"
      className={['inline-block shrink-0 align-middle', className].filter(Boolean).join(' ')}
      {...props}
    />
  )
}
