import {
  chmodSync,
  copyFileSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  realpathSync,
  rmdirSync,
  rmSync,
  statSync,
  writeFileSync,
  type Stats
} from 'fs'
import { copyFile, mkdir, readdir, stat } from 'fs/promises'
import { tmpdir } from 'os'
import { basename, dirname, join, relative } from 'path'
import { createHash, randomUUID } from 'crypto'
import { realpathIfExists, resolveInsideWorkspace } from '../workspace/safePath'
import { atomicWriteFile, atomicWriteJson } from '@main/storage/atomicWrite'
import { logger } from '../../shared/logger'
import { isPlausibleWorkspaceFilePath } from './loopPolicy'

export type CheckpointFileAction = 'created' | 'modified' | 'deleted'

export type CheckpointFileResolution = 'kept' | 'discarded'

export type CheckpointFileEntry = {
  /** Workspace-relative path using forward slashes. */
  path: string
  action: CheckpointFileAction
  /** False for recursive directory deletes (v1 cannot restore). */
  undoable: boolean
  /**
   * SHA-256 of workspace content after the write (created/modified).
   * Restore skips when current content differs (user edit after the agent).
   */
  hash?: string
  /** Set when the user Keep/Discard resolves this path. */
  resolved?: CheckpointFileResolution
  /** Revert was refused because the file was edited after the agent wrote it. */
  conflicted?: boolean
}

export type WriteCheckpointMeta = {
  id: string
  createdAt: string
  undone?: boolean
  /** True when every file is Keep/Discard resolved (or discarded via Undo). */
  resolved?: boolean
  /**
   * Index of the user message this invoke was answering (messages already include
   * that user turn when the checkpoint session starts). Used by edit-and-rewind.
   */
  anchorUserMessageIndex?: number
  files: CheckpointFileEntry[]
}

export type CheckpointIndex = {
  checkpoints: Array<{ id: string; createdAt: string; undone?: boolean }>
}

const activeSessions = new Map<string, InvokeWriteCheckpoint>()

/** Checkpoint IDs are UUIDs generated by this module; never trust external input. */
const CHECKPOINT_ID_RE = /^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/

function assertValidCheckpointId(id: string): void {
  if (!CHECKPOINT_ID_RE.test(id)) {
    throw new Error(`Invalid checkpoint id: ${id.slice(0, 64)}`)
  }
}

function normalizeRelPath(rel: string): string {
  return rel.replace(/\\/g, '/')
}

function toCheckpointRelPath(workspaceRoot: string, pathArg: string): string {
  try {
    const resolved = resolveInsideWorkspace(workspaceRoot, pathArg)
    const rel = normalizeRelPath(relative(realpathIfExists(workspaceRoot), resolved))
    if (rel && !rel.startsWith('..')) return rel
  } catch {
    /* fall through to slash-normalize */
  }
  return normalizeRelPath(pathArg)
}

function hashExistingFile(path: string): string | undefined {
  if (!existsSync(path)) return undefined
  try {
    const st = statSync(path)
    if (!st.isFile()) return undefined
    return createHash('sha256').update(readFileSync(path)).digest('hex')
  } catch {
    return undefined
  }
}

function blobPathFor(checkpointDir: string, relPath: string): string {
  const parts = normalizeRelPath(relPath).split('/').filter(Boolean)
  if (parts.some((p) => p === '..')) {
    throw new Error('Invalid checkpoint path')
  }
  return join(checkpointDir, 'files', ...parts)
}

function loadIndex(runDir: string): CheckpointIndex {
  const p = join(runDir, 'checkpoints', 'index.json')
  if (!existsSync(p)) return { checkpoints: [] }
  try {
    const raw = JSON.parse(readFileSync(p, 'utf8')) as CheckpointIndex
    const checkpoints = (Array.isArray(raw.checkpoints) ? raw.checkpoints : []).filter(
      (c): c is { id: string; createdAt: string; undone?: boolean } =>
        c != null && typeof c === 'object' && typeof (c as { id?: unknown }).id === 'string' &&
        CHECKPOINT_ID_RE.test((c as { id: string }).id)
    )
    return { checkpoints }
  } catch {
    return { checkpoints: [] }
  }
}

function saveIndex(runDir: string, index: CheckpointIndex): void {
  const dir = join(runDir, 'checkpoints')
  mkdirSync(dir, { recursive: true })
  atomicWriteJson(join(dir, 'index.json'), index)
}

function loadMeta(runDir: string, id: string): WriteCheckpointMeta | null {
  assertValidCheckpointId(id)
  const p = join(runDir, 'checkpoints', id, 'meta.json')
  if (!existsSync(p)) return null
  try {
    return JSON.parse(readFileSync(p, 'utf8')) as WriteCheckpointMeta
  } catch {
    return null
  }
}

/** Read checkpoint meta for IPC persistence / hydration. */
export function getWriteCheckpointMeta(
  runDir: string,
  checkpointId: string
): WriteCheckpointMeta | null {
  // Soft no-op resolveWrites may pass ''; avoid assert throw → IPC_HANDLER.
  if (!checkpointId.trim() || !CHECKPOINT_ID_RE.test(checkpointId)) return null
  return loadMeta(runDir, checkpointId)
}

/**
 * Every checkpoint of a run, oldest first, with its meta. Read-only view for
 * summaries (the navigator's "Ready for review"); unreadable entries are
 * skipped rather than thrown.
 */
export function listCheckpointMetas(runDir: string): WriteCheckpointMeta[] {
  const out: WriteCheckpointMeta[] = []
  for (const entry of loadIndex(runDir).checkpoints) {
    const meta = loadMeta(runDir, entry.id)
    if (meta) out.push(entry.undone && !meta.undone ? { ...meta, undone: true } : meta)
  }
  return out
}

/** Where a checkpoint keeps the before-image of one workspace-relative path. */
export function checkpointBeforeImagePath(runDir: string, checkpointId: string, relPath: string): string {
  assertValidCheckpointId(checkpointId)
  return blobPathFor(join(runDir, 'checkpoints', checkpointId), relPath)
}

function saveMeta(runDir: string, meta: WriteCheckpointMeta): void {
  assertValidCheckpointId(meta.id)
  const dir = join(runDir, 'checkpoints', meta.id)
  mkdirSync(dir, { recursive: true })
  atomicWriteJson(join(dir, 'meta.json'), meta)
}

/** One turn (invoke) of agent writes; first prior per path wins. */
export class InvokeWriteCheckpoint {
  readonly id: string
  readonly createdAt: string
  readonly anchorUserMessageIndex: number | undefined
  private readonly runDir: string
  private readonly workspaceRoot: string
  private readonly files = new Map<string, CheckpointFileEntry>()
  /** Rel-paths with an in-flight async snapshot so first-path-wins stays racy-safe. */
  private readonly pendingRels = new Set<string>()
  private finalized = false

  constructor(
    runDir: string,
    workspaceRoot: string,
    anchorUserMessageIndex?: number
  ) {
    this.id = randomUUID()
    this.createdAt = new Date().toISOString()
    this.runDir = runDir
    this.workspaceRoot = workspaceRoot
    this.anchorUserMessageIndex = anchorUserMessageIndex
  }

  /**
   * Distinct workspace files this invoke has touched. The authoritative
   * mutation signal: unlike the edit-family tool names, it also covers
   * terminal writes, MCP writers, merges and watched out-of-band changes.
   */
  get writtenFileCount(): number {
    return this.files.size
  }

  private realWorkspaceRoot(): string {
    return existsSync(this.workspaceRoot) ? realpathSync(this.workspaceRoot) : this.workspaceRoot
  }

  private relPathFromResolved(resolved: string): string {
    return normalizeRelPath(relative(this.realWorkspaceRoot(), resolved))
  }

  private checkpointDir(): string {
    return join(this.runDir, 'checkpoints', this.id)
  }

  /**
   * Snapshot prior content before a write or delete.
   * Async blob copy so the Electron main/UI thread is not blocked on disk I/O.
   * @param pathArg Path as the tool received it (workspace-relative or absolute inside root).
   */
  async recordPrior(
    pathArg: string,
    kind: 'write' | 'delete',
    opts?: { recursiveDir?: boolean }
  ): Promise<void> {
    if (this.finalized) return
    const resolved = resolveInsideWorkspace(this.workspaceRoot, pathArg)
    const rel = this.relPathFromResolved(resolved)
    if (!rel || rel.startsWith('..')) return
    // Recursive dir deletes are recorded as bare directory names (no extension).
    // Plausible-file checks reject those; still allow the checkpoint entry.
    if (!opts?.recursiveDir && !isPlausibleWorkspaceFilePath(rel)) return
    if (this.files.has(rel) || this.pendingRels.has(rel)) return
    this.pendingRels.add(rel)
    const filesBefore = this.files.size
    try {
      await this.snapshotPrior(resolved, rel, kind, opts)
    } finally {
      this.pendingRels.delete(rel)
      if (this.files.size > filesBefore) this.persistIncremental()
    }
  }

  private async snapshotPrior(
    resolved: string,
    rel: string,
    kind: 'write' | 'delete',
    opts?: { recursiveDir?: boolean }
  ): Promise<void> {
    let st: Awaited<ReturnType<typeof stat>> | null = null
    try {
      st = await stat(resolved)
    } catch {
      st = null
    }
    if (kind === 'write') {
      if (!st) {
        this.files.set(rel, { path: rel, action: 'created', undoable: true })
        return
      }
      if (st.isDirectory()) {
        // Writing through edit tools targets files; ignore dirs.
        return
      }
      const dest = blobPathFor(this.checkpointDir(), rel)
      await mkdir(dirname(dest), { recursive: true })
      await copyFile(resolved, dest)
      this.files.set(rel, { path: rel, action: 'modified', undoable: true })
      return
    }

    // delete
    if (!st) return
    if (st.isDirectory()) {
      // Snapshot the directory tree so the delete is undoable. Each file becomes
      // its own 'deleted' checkpoint entry; restoring them recreates the original
      // tree (v1 could not restore directories — now fixed).
      const maxDirRestoreFiles = 20000
      let fileCount = 0
      let overflow = false
      const recordedChildren: string[] = []
      const snapshotTree = async (absDir: string): Promise<void> => {
        if (overflow) return
        let entries
        try {
          entries = await readdir(absDir, { withFileTypes: true })
        } catch {
          return
        }
        for (const entry of entries) {
          const abs = join(absDir, entry.name)
          if (entry.isDirectory()) {
            // entry.isDirectory() is false for symlinks, so symlink dirs are not followed.
            await snapshotTree(abs)
            if (overflow) return
            continue
          }
          if (!entry.isFile()) continue // skip symlinks / sockets / devices
          if (fileCount >= maxDirRestoreFiles) {
            overflow = true
            return
          }
          fileCount++
          const childRel = this.relPathFromResolved(abs)
          if (!childRel || childRel.startsWith('..')) continue
          const dest = blobPathFor(this.checkpointDir(), childRel)
          try {
            await mkdir(dirname(dest), { recursive: true })
            await copyFile(abs, dest)
          } catch {
            continue
          }
          recordedChildren.push(childRel)
          this.files.set(childRel, { path: childRel, action: 'deleted', undoable: true })
        }
      }
      await snapshotTree(resolved)
      if (overflow) {
        // `overflow` can flip true only AFTER up to maxDirRestoreFiles children
        // were already recorded as undoable. Marking just the parent
        // non-undoable left Undo restoring that partial subtree and reporting
        // it as a completed undo — a directory silently missing most of its
        // files. If the tree cannot be restored whole, none of it is undoable.
        for (const childRel of recordedChildren) {
          const entry = this.files.get(childRel)
          if (entry) this.files.set(childRel, { ...entry, undoable: false })
        }
        logger.warn('Directory delete too large to snapshot for undo; marked non-undoable', {
          scope: 'agent',
          path: rel
        })
        this.files.set(rel, { path: rel, action: 'deleted', undoable: false })
      } else if (fileCount === 0) {
        // Empty directory: nothing to restore, but keep the entry for UI parity.
        this.files.set(rel, { path: rel, action: 'deleted', undoable: false })
      }
      return
    }
    const dest = blobPathFor(this.checkpointDir(), rel)
    await mkdir(dirname(dest), { recursive: true })
    await copyFile(resolved, dest)
    this.files.set(rel, { path: rel, action: 'deleted', undoable: true })
  }

  /**
   * Record a mutation observed after a tool ran (e.g. opaque terminal redirect).
   * First path wins — does not overwrite recordPrior entries.
   */
  async recordObservedMutation(
    pathArg: string,
    kind: 'created' | 'modified' | 'deleted',
    priorBlobPath?: string
  ): Promise<void> {
    if (this.finalized) return
    const resolved = resolveInsideWorkspace(this.workspaceRoot, pathArg)
    const rel = this.relPathFromResolved(resolved)
    if (!rel || rel.startsWith('..')) return
    if (!isPlausibleWorkspaceFilePath(rel)) return
    if (this.files.has(rel) || this.pendingRels.has(rel)) return
    this.pendingRels.add(rel)
    const filesBefore = this.files.size
    try {
      if (kind === 'created') {
        this.files.set(rel, { path: rel, action: 'created', undoable: true })
        return
      }

      let blobExists = false
      if (priorBlobPath) {
        try {
          await stat(priorBlobPath)
          blobExists = true
        } catch {
          blobExists = false
        }
      }
      if (!priorBlobPath || !blobExists) {
        this.files.set(rel, {
          path: rel,
          action: kind === 'modified' ? 'modified' : 'deleted',
          undoable: false
        })
        return
      }

      const dest = blobPathFor(this.checkpointDir(), rel)
      await mkdir(dirname(dest), { recursive: true })
      await copyFile(priorBlobPath, dest)
      this.files.set(rel, {
        path: rel,
        action: kind === 'modified' ? 'modified' : 'deleted',
        undoable: true
      })
    } finally {
      this.pendingRels.delete(rel)
      if (this.files.size > filesBefore) this.persistIncremental()
    }
  }

  private stampPostWriteHashes(): void {
    for (const file of this.files.values()) {
      if (!file.undoable || file.action === 'deleted') continue
      try {
        const resolved = resolveInsideWorkspace(this.workspaceRoot, file.path)
        const hash = hashExistingFile(resolved)
        if (hash) file.hash = hash
      } catch {
        // Leave unhashed; restore falls back to unguarded copy/delete.
      }
    }
  }

  /**
   * Persist the in-progress checkpoint (meta + index entry) so a crash or power
   * loss mid-turn cannot erase the turn's undo data. Post-write hashes are only
   * stamped by finalize(); the incremental meta restores the pre-crash content
   * without user-edit conflict detection, which is the best available outcome
   * after an unorderly death.
   */
  private persistIncremental(): void {
    if (this.finalized) return
    if (this.files.size === 0) return
    const meta: WriteCheckpointMeta = {
      id: this.id,
      createdAt: this.createdAt,
      ...(this.anchorUserMessageIndex !== undefined
        ? { anchorUserMessageIndex: this.anchorUserMessageIndex }
        : {}),
      files: [...this.files.values()]
    }
    try {
      saveMeta(this.runDir, meta)
      const index = loadIndex(this.runDir)
      if (!index.checkpoints.some((c) => c.id === this.id)) {
        index.checkpoints.push({ id: meta.id, createdAt: meta.createdAt })
        saveIndex(this.runDir, index)
      }
    } catch (err) {
      logger.warn('Failed to persist incremental write checkpoint', {
        scope: 'agent',
        correlationId: basename(this.runDir),
        checkpointId: this.id,
        err
      })
    }
  }

  /**
   * Drop entries the turn proved changed nothing.
   *
   * `recordPrior` runs *before* the write it is protecting, because the prior
   * content has to be captured while it still exists. When the write then
   * fails, the speculative entry stays: run 874dad8f's `str_replace index.md`
   * failed with "File not found" and left `index.md` recorded created and
   * undoable for a file that never existed. It reached the Changes panel, and
   * the receipt told the user (and any awaiting parent) the run wrote it. Undo
   * deletes what a `created` entry names, so had anything else produced that
   * path later, Undo would have destroyed it.
   *
   * Only disk state decides — an entry survives unless the workspace itself
   * shows no net change, so a real mutation can never be dropped here. Two
   * kinds are deliberately left alone: non-undoable entries (a directory delete
   * too large to snapshot) are real changes that simply cannot be reverted, and
   * `deleted` entries are recorded by callers with their own lifecycles
   * (`recordObservedMutation` from the post-tool watcher, instance merges)
   * rather than by a snapshot taken ahead of a write that might fail.
   */
  private dropUnchangedEntries(): void {
    for (const [rel, file] of [...this.files]) {
      if (!file.undoable) continue
      if (file.action === 'deleted') continue
      let resolved: string
      try {
        resolved = resolveInsideWorkspace(this.workspaceRoot, file.path)
      } catch {
        continue
      }
      if (file.action === 'created') {
        // Nothing at the path it claims to have created.
        if (!existsSync(resolved)) this.files.delete(rel)
        continue
      }
      // `modified` snapshotted the prior content, so identical bytes on disk
      // mean the write never landed.
      let priorHash: string | undefined
      try {
        priorHash = hashExistingFile(blobPathFor(this.checkpointDir(), file.path))
      } catch {
        continue
      }
      if (!priorHash) continue
      if (hashExistingFile(resolved) === priorHash) this.files.delete(rel)
    }
  }

  /** Remove a mid-turn persisted checkpoint that finalize found to be empty. */
  private discardPersistedCheckpoint(): void {
    try {
      const index = loadIndex(this.runDir)
      const next = index.checkpoints.filter((c) => c.id !== this.id)
      if (next.length !== index.checkpoints.length) {
        saveIndex(this.runDir, { ...index, checkpoints: next })
      }
      rmSync(this.checkpointDir(), { recursive: true, force: true })
    } catch (err) {
      logger.warn('Failed to discard an empty write checkpoint', {
        scope: 'agent',
        correlationId: basename(this.runDir),
        checkpointId: this.id,
        err
      })
    }
  }

  /** Persist if any files were recorded; returns meta or null. */
  finalize(): WriteCheckpointMeta | null {
    if (this.finalized) return null
    this.finalized = true
    if (this.files.size === 0) return null
    this.dropUnchangedEntries()
    if (this.files.size === 0) {
      // persistIncremental may already have written this id to disk mid-turn.
      // Leaving it there would keep the phantom in the Changes panel under a
      // checkpoint finalize has disowned.
      this.discardPersistedCheckpoint()
      return null
    }
    this.stampPostWriteHashes()

    const meta: WriteCheckpointMeta = {
      id: this.id,
      createdAt: this.createdAt,
      ...(this.anchorUserMessageIndex !== undefined
        ? { anchorUserMessageIndex: this.anchorUserMessageIndex }
        : {}),
      files: [...this.files.values()]
    }
    saveMeta(this.runDir, meta)
    const index = loadIndex(this.runDir)
    // Incremental persistence may already have registered this id mid-turn.
    if (!index.checkpoints.some((c) => c.id === meta.id)) {
      index.checkpoints.push({
        id: meta.id,
        createdAt: meta.createdAt
      })
      saveIndex(this.runDir, index)
    }
    return meta
  }
}

export function beginWriteCheckpoint(
  runDir: string,
  workspaceRoot: string,
  anchorUserMessageIndex?: number
): InvokeWriteCheckpoint {
  const existing = activeSessions.get(runDir)
  if (existing) {
    // Same turn, or no new anchor stated: keep accumulating into it.
    if (
      anchorUserMessageIndex === undefined ||
      existing.anchorUserMessageIndex === anchorUserMessageIndex
    ) {
      return existing
    }
    // A different anchor means a new turn started without the previous invoke
    // finalizing. Reusing the old session would file THIS turn's undo records
    // under the PREVIOUS turn's anchor, and report the previous turn's files
    // as this turn's mutations (writtenFileCount). Close it out under its own
    // anchor so both turns stay separately undoable.
    activeSessions.delete(runDir)
    try {
      existing.finalize()
    } catch (err) {
      logger.warn('Failed to finalize a stale write checkpoint before a new turn', {
        scope: 'agent',
        correlationId: basename(runDir),
        err
      })
    }
  }
  const session = new InvokeWriteCheckpoint(runDir, workspaceRoot, anchorUserMessageIndex)
  activeSessions.set(runDir, session)
  return session
}

export function getWriteCheckpoint(runDir: string | undefined): InvokeWriteCheckpoint | undefined {
  if (!runDir) return undefined
  return activeSessions.get(runDir)
}

export function finalizeWriteCheckpoint(runDir: string): WriteCheckpointMeta | null {
  const session = activeSessions.get(runDir)
  activeSessions.delete(runDir)
  if (!session) return null
  return session.finalize()
}

/** Drop an open session without persisting (e.g. tests). */
export function discardWriteCheckpoint(runDir: string): void {
  activeSessions.delete(runDir)
}

export type ResolveWritesResult = {
  checkpointId: string
  kept: string[]
  discarded: string[]
  skipped: string[]
  /**
   * Paths whose revert was refused because the file was edited by the user after
   * the agent wrote it (content no longer matches). These stay unresolved so the
   * UI can surface "can't auto-revert" instead of falsely marking them reverted.
   */
  conflicted: string[]
  fullyResolved: boolean
}

function resolveCheckpointId(runDir: string, checkpointId?: string): string | null {
  if (checkpointId) assertValidCheckpointId(checkpointId)
  const index = loadIndex(runDir)
  let id = checkpointId
  if (!id) {
    for (let i = index.checkpoints.length - 1; i >= 0; i--) {
      const entry = index.checkpoints[i]!
      const meta = loadMeta(runDir, entry.id)
      if (meta && !meta.undone && !meta.resolved) {
        id = entry.id
        break
      }
    }
  }
  if (!id) return null
  assertValidCheckpointId(id)
  return id
}

/**
 * Where a file stands against the agent's write: `edited` when someone changed
 * it after the agent did (restoring would destroy that change), `restored`
 * when it already holds what restoring would put there, else `writable`.
 * `current` is the file's content hash, undefined when there is no file.
 * Restore passes what is on disk; the rewind preview passes what the newer
 * restores in its walk would leave, so the dialog says what the rewind will do.
 */
function writeState(current: string | undefined, blob: string | null, file: CheckpointFileEntry): 'edited' | 'restored' | 'writable' {
  if (file.action === 'created') {
    return file.hash && current && current !== file.hash ? 'edited' : 'writable'
  }
  if (!current || !blob) return 'writable'
  if (file.action === 'modified') {
    if (!file.hash || current === file.hash) return 'writable'
    return current === hashExistingFile(blob) ? 'restored' : 'edited'
  }
  // Deleted by the agent and back on disk: already the old file, or someone else's.
  return current === hashExistingFile(blob) ? 'restored' : 'edited'
}

/**
 * Past a write that kept no copy, whether a rewind can take back the next,
 * older write: only where that destroys nothing but the older write's own
 * work. The file is gone, or holds just what that write left (its hash) or
 * found (its copy); anything else may be the uncopied write's work, or yours.
 * A further write with no copy passes too, since nothing is done to it.
 */
function goesPastNoCopy(current: string | undefined, blob: string | null, file: CheckpointFileEntry): boolean {
  if (!file.undoable || !current) return true
  if (file.hash && current === file.hash) return true
  return writeState(current, blob, file) === 'restored'
}

/** goesPastNoCopy for the file on disk. One it cannot read stops the walk. */
function goesPastNoCopyOnDisk(workspaceRoot: string, checkpointDir: string, file: CheckpointFileEntry): boolean {
  if (!file.undoable) return true
  try {
    const blob = file.action === 'created' ? null : blobPathFor(checkpointDir, file.path)
    return goesPastNoCopy(hashExistingFile(resolveInsideWorkspace(workspaceRoot, file.path)), blob, file)
  } catch {
    return false
  }
}

/**
 * How much of what a rewind overwrites it holds in memory to put back if a
 * later restore fails. Past this it copies files to a temp directory instead,
 * so a rewind over large files cannot run the main process out of memory.
 */
const REWIND_UNDO_MEMORY_BYTES = 64 * 1024 * 1024
let rewindUndoMemoryBytes = REWIND_UNDO_MEMORY_BYTES

/** @internal Test hook: 0 copies every file a rewind overwrites to disk. */
export function setRewindUndoMemoryBytesForTests(bytes: number | null): void {
  rewindUndoMemoryBytes = bytes ?? REWIND_UNDO_MEMORY_BYTES
}

/** A file as a restore found it: its size and time, to tell whether it was touched, and its content. */
type FileBefore = { size: number; mtimeMs: number; mode: number } & ({ bytes: Buffer } | { copy: string })

type RestoreUndo = {
  path: string
  resolved: string
  /** Null when there was no file at the path. */
  before: FileBefore | null
  /** Outermost directory that was missing, which the restore creates. */
  missingDir?: string
}

/**
 * What a rewind changed, so one that fails partway can leave the workspace as
 * it was. A restore records its path before touching it, the failing one
 * included: a copy that fails partway can leave its file truncated or gone.
 */
class RewindUndo {
  private readonly undos: RestoreUndo[] = []
  private heldBytes = 0
  private copyDir: string | null = null
  private keepCopies = false

  /** Note what `resolved` holds now. Throws, having touched nothing, when it cannot. */
  record(path: string, resolved: string): void {
    this.undos.push({
      path,
      resolved,
      before: this.capture(resolved),
      missingDir: outermostMissingDir(dirname(resolved))
    })
  }

  private capture(resolved: string): FileBefore | null {
    let st: Stats
    try {
      st = statSync(resolved)
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code === 'ENOENT') return null
      throw err
    }
    // Only a file can be put back, so restoring over anything else fails here.
    if (!st.isFile()) throw new Error('not a file')
    const seen = { size: st.size, mtimeMs: st.mtimeMs, mode: st.mode }
    if (this.heldBytes + st.size <= rewindUndoMemoryBytes) {
      const bytes = readFileSync(resolved)
      this.heldBytes += bytes.length
      return { ...seen, bytes }
    }
    this.copyDir ??= mkdtempSync(join(tmpdir(), 'vyotiq-rewind-undo-'))
    const copy = join(this.copyDir, String(this.undos.length))
    copyFileSync(resolved, copy)
    return { ...seen, copy }
  }

  /** Put every recorded path back, newest first. Returns the ones it could not. */
  rollBack(): string[] {
    const notPutBack: string[] = []
    for (const undo of [...this.undos].reverse()) {
      try {
        putBack(undo)
      } catch (err) {
        logger.error('Rewind could not put a file back as it was', {
          scope: 'agent',
          path: undo.path,
          err
        })
        notPutBack.push(undo.path)
      }
    }
    // A copy may now be the only one left of a file it could not put back.
    this.keepCopies = notPutBack.length > 0
    return notPutBack
  }

  dispose(): void {
    if (!this.copyDir) return
    if (this.keepCopies) {
      logger.warn('Kept the rewind copies of files it could not put back', {
        scope: 'agent',
        path: this.copyDir
      })
      return
    }
    try {
      rmSync(this.copyDir, { recursive: true, force: true })
    } catch (err) {
      logger.warn('Failed to remove rewind copies', { scope: 'agent', path: this.copyDir, err })
    }
  }
}

/**
 * The outermost directory missing on the way to `dir`: what mkdir will create.
 * Not mkdirSync's own return value, which on Windows is the `\\?\` form and
 * never equals a path walked up with dirname().
 */
function outermostMissingDir(dir: string): string | undefined {
  let missing: string | undefined
  for (let d = dir; !existsSync(d); d = dirname(d)) {
    missing = d
    if (dirname(d) === d) break
  }
  return missing
}

/** True when the path still holds what the restore found there: it never got that far. */
function stillAsFound(undo: RestoreUndo): boolean {
  let st: Stats
  try {
    st = statSync(undo.resolved)
  } catch (err) {
    return undo.before === null && (err as NodeJS.ErrnoException).code === 'ENOENT'
  }
  const before = undo.before
  return before !== null && st.isFile() && st.size === before.size && st.mtimeMs === before.mtimeMs
}

function putBack(undo: RestoreUndo): void {
  const { resolved, before } = undo
  if (!stillAsFound(undo)) {
    if (!before) {
      rmSync(resolved, { force: true })
    } else if ('copy' in before) {
      copyFileSync(before.copy, resolved)
    } else {
      const mode = before.mode & 0o7777
      writeFileSync(resolved, before.bytes, { mode })
      // A file that is still there keeps the mode the restore gave it.
      if ((statSync(resolved).mode & 0o7777) !== mode) chmodSync(resolved, mode)
    }
  }
  if (undo.missingDir) removeEmptyDirs(dirname(resolved), undo.missingDir)
}

/** Remove `dir` and its parents up to `outermost` while they are empty. */
function removeEmptyDirs(dir: string, outermost: string): void {
  for (let d = dir; ; d = dirname(d)) {
    try {
      rmdirSync(d)
    } catch {
      return
    }
    if (d === outermost || dirname(d) === d) return
  }
}

type RestoreOutcome = 'restored' | 'skipped' | 'conflict'

/**
 * Put one file back as it was before the agent's write. Throws when it cannot:
 * a missing copy or an I/O error. With `undo`, notes what the path held before
 * changing it.
 */
function restoreFile(
  workspaceRoot: string,
  checkpointDir: string,
  file: CheckpointFileEntry,
  undo?: RewindUndo
): RestoreOutcome {
  if (!file.undoable) return 'skipped'
  const resolved = resolveInsideWorkspace(workspaceRoot, file.path)
  if (file.action === 'created') {
    if (writeState(hashExistingFile(resolved), null, file) === 'edited') {
      // User edited the file the agent created — refuse to delete their work.
      logger.warn('Skipping checkpoint restore; file changed after the agent write', {
        scope: 'agent',
        path: file.path
      })
      return 'conflict'
    }
    if (existsSync(resolved)) {
      undo?.record(file.path, resolved)
      rmSync(resolved, { force: true })
    }
    return 'restored'
  }
  const blob = blobPathFor(checkpointDir, file.path)
  if (!existsSync(blob)) throw new Error('its saved copy is missing')

  // A missing file falls through: the prior blob is restored, recreating what
  // the agent changed or deleted rather than leaving the deletion in place.
  const state = writeState(hashExistingFile(resolved), blob, file)
  if (state === 'restored') return 'restored'
  if (state === 'edited') {
    // Changed after the agent's write (or, for a delete, put back with other
    // content) — refuse to clobber it.
    logger.warn('Skipping checkpoint restore; file changed after the agent write', {
      scope: 'agent',
      path: file.path
    })
    return 'conflict'
  }

  undo?.record(file.path, resolved)
  mkdirSync(dirname(resolved), { recursive: true })
  copyFileSync(blob, resolved)
  return 'restored'
}

/** restoreFile for Undo, where a file that fails stays unresolved and the rest go on. */
function restoreOneFile(
  workspaceRoot: string,
  checkpointDir: string,
  file: CheckpointFileEntry
): RestoreOutcome | 'failed' {
  try {
    return restoreFile(workspaceRoot, checkpointDir, file)
  } catch (err) {
    logger.warn('Failed to restore checkpoint file', {
      scope: 'agent',
      path: file.path,
      err
    })
    return 'failed'
  }
}

function markCheckpointFullyResolved(runDir: string, meta: WriteCheckpointMeta): void {
  const idx = loadIndex(runDir)
  const entry = idx.checkpoints.find((c) => c.id === meta.id)
  if (entry) entry.undone = true
  saveIndex(runDir, idx)
  meta.resolved = true
  meta.undone = true
  saveMeta(runDir, meta)
}

/**
 * Keep and/or discard specific paths (or all unresolved when paths omitted for discard/keep all).
 *
 * Resolution is scoped to `checkpointId` when provided. When `checkpointId` is
 * omitted but `paths` are given, each path is resolved within the newest
 * unresolved checkpoint that recorded it — so a user can Keep/Discard a file
 * from any turn, not just the latest one. When both are omitted the latest
 * unresolved checkpoint is fully resolved (Undo / Keep-all / Discard-all).
 */
export function resolveWrites(
  runDir: string,
  workspaceRoot: string,
  opts: {
    checkpointId?: string
    action: 'keep' | 'discard'
    /** When omitted, applies to all unresolved files. */
    paths?: string[]
  }
): ResolveWritesResult {
  if (opts.checkpointId) {
    return resolveWritesInCheckpoint(runDir, workspaceRoot, opts.checkpointId, opts.action, opts.paths ?? null)
  }

  if (opts.paths && opts.paths.length > 0) {
    const index = loadIndex(runDir)
    const byCheckpoint = new Map<string, string[]>()
    for (const p of opts.paths) {
      const rel = toCheckpointRelPath(workspaceRoot, p)
      const cpId = findNewestUnresolvedCheckpointForPath(runDir, index, rel)
      if (!cpId) continue
      const arr = byCheckpoint.get(cpId) ?? []
      arr.push(rel)
      byCheckpoint.set(cpId, arr)
    }
    if (byCheckpoint.size === 0) {
      // Soft no-op: none of the paths are part of an actionable checkpoint.
      return {
        checkpointId: '',
        kept: [],
        discarded: [],
        skipped: [...opts.paths],
        conflicted: [],
        fullyResolved: true
      }
    }
    const kept: string[] = []
    const discarded: string[] = []
    const skipped: string[] = []
    const conflicted: string[] = []
    let allFullyResolved = true
    for (const [cpId, rels] of byCheckpoint) {
      const r = resolveWritesInCheckpoint(runDir, workspaceRoot, cpId, opts.action, rels)
      kept.push(...r.kept)
      discarded.push(...r.discarded)
      skipped.push(...r.skipped)
      conflicted.push(...r.conflicted)
      if (!r.fullyResolved) allFullyResolved = false
    }
    return {
      checkpointId: '',
      kept,
      discarded,
      skipped,
      conflicted,
      fullyResolved: allFullyResolved
    }
  }

  const id = resolveCheckpointId(runDir, undefined)
  if (!id) {
    // Soft no-op: UI may call Keep/Discard after the banner cleared or with no writes.
    return {
      checkpointId: '',
      kept: [],
      discarded: [],
      skipped: [],
      conflicted: [],
      fullyResolved: true
    }
  }
  return resolveWritesInCheckpoint(runDir, workspaceRoot, id, opts.action, null)
}

/** Newest unresolved checkpoint that still has an unresolved entry for `relPath`. */
function findNewestUnresolvedCheckpointForPath(
  runDir: string,
  index: CheckpointIndex,
  relPath: string
): string | null {
  for (let i = index.checkpoints.length - 1; i >= 0; i--) {
    const entry = index.checkpoints[i]!
    const meta = loadMeta(runDir, entry.id)
    if (!meta || meta.undone || meta.resolved) continue
    if (meta.files.some((f) => f.path === relPath && !f.resolved)) return meta.id
  }
  return null
}

function resolveWritesInCheckpoint(
  runDir: string,
  workspaceRoot: string,
  checkpointId: string,
  action: 'keep' | 'discard',
  paths: string[] | null
): ResolveWritesResult {
  const meta = loadMeta(runDir, checkpointId)
  if (!meta) throw new Error(`Checkpoint not found: ${checkpointId}`)
  if (meta.undone || meta.resolved) throw new Error('That checkpoint was already resolved')

  const targetPaths =
    paths && paths.length > 0
      ? new Set(paths.map((p) => toCheckpointRelPath(workspaceRoot, p)))
      : null

  const checkpointDir = join(runDir, 'checkpoints', checkpointId)
  const kept: string[] = []
  const discarded: string[] = []
  const skipped: string[] = []
  const conflicted: string[] = []

  for (const file of meta.files) {
    if (targetPaths && !targetPaths.has(file.path)) continue
    if (file.resolved) {
      skipped.push(file.path)
      continue
    }
    if (action === 'keep') {
      file.resolved = 'kept'
      kept.push(file.path)
      continue
    }
    const outcome = restoreOneFile(workspaceRoot, checkpointDir, file)
    if (outcome === 'restored') {
      file.resolved = 'discarded'
      discarded.push(file.path)
    } else if (outcome === 'conflict') {
      // User edited the file after the agent wrote it; leave it unresolved and
      // surface it so the UI can explain why it cannot be auto-reverted.
      file.conflicted = true
      conflicted.push(file.path)
    } else if (outcome === 'failed') {
      // Undoable file whose restore failed (missing prior blob / I/O error):
      // keep it unresolved so the user can retry instead of falsely marking it
      // as reverted.
      skipped.push(file.path)
    } else {
      // Non-undoable: still mark discarded so the UI can clear it.
      file.resolved = 'discarded'
      skipped.push(file.path)
    }
  }

  // When every undoable file is handled, stamp leftover non-undoable as kept so
  // disk meta.resolved matches the UI fullyResolved banner clear.
  const undoablesDone = meta.files.every((f) => Boolean(f.resolved) || !f.undoable)
  if (undoablesDone) {
    for (const file of meta.files) {
      if (!file.resolved && !file.undoable) file.resolved = 'kept'
    }
  }
  const allHandled = meta.files.every((f) => Boolean(f.resolved))
  if (allHandled) {
    markCheckpointFullyResolved(runDir, meta)
  } else {
    saveMeta(runDir, meta)
  }

  return {
    checkpointId,
    kept,
    discarded,
    skipped,
    conflicted,
    fullyResolved: allHandled
  }
}

/**
 * A file is in at most one of restored, skipped and edited, however many
 * rewound runs changed it: the one that says where the rewind left it.
 */
export type RewindWritesResult = {
  checkpointIds: string[]
  /** Back to how they were before the rewound runs. */
  restored: string[]
  /** Changed by a write that kept no copy (not undoable), which the rewind could not get past. */
  skipped: string[]
  /** Changed after an agent's write: the rewind stops at that change and leaves it. */
  edited: string[]
  /**
   * True when an undoable file could not be restored — a missing copy or an
   * I/O error. The rewind then leaves the workspace as it was: files it had
   * already restored are put back, and no checkpoint is marked.
   */
  undoableRestoreFailed: boolean
  /** The file that stopped the rewind, and why: an error code, or what is missing. */
  failure?: { path: string; reason: string }
  /** Files the failed rewind changed and then could not put back as they were. */
  notPutBack?: string[]
}

/** Where the rewind will leave one file, in the terms of RewindWritesResult. */
export type RewindWritesPlanFile = {
  path: string
  /**
   * What the rewind undoes, as git would letter it: created (it removes the
   * file), modified (puts it back), deleted (brings it back).
   */
  action: CheckpointFileAction
  /** False when the rewind stops at a write that kept no copy (skipped). */
  undoable: boolean
  /** Changed after an agent's write: the rewind stops at that change (edited). */
  edited?: boolean
  /**
   * Stops (edited, or no copy) only after taking off later runs' writes: the
   * file changes, but not all the way back.
   */
  partway?: boolean
}

export type RewindWritesPlan = {
  checkpointIds: string[]
  files: RewindWritesPlanFile[]
}

/**
 * Selection rule for a rewind to `fromUserMessageIndex`, shared by the preview
 * (planRewindWrites) and execution (rewindWritesFrom) so they can never diverge.
 * Checkpoints without `anchorUserMessageIndex` (legacy runs) are only rewound
 * when rewinding to the start of the transcript (`fromUserMessageIndex === 0`).
 */
function isRewoundCheckpoint(meta: WriteCheckpointMeta, fromUserMessageIndex: number): boolean {
  const anchor = meta.anchorUserMessageIndex
  if (anchor !== undefined) return anchor >= fromUserMessageIndex
  return fromUserMessageIndex === 0
}

/** Per-run checkpoint selection for a rewind that spans multiple runs. */
export type RewindRunScope = {
  runDir: string
  /**
   * 'anchored' keeps the parent-run rule (isRewoundCheckpoint against the
   * rewind point); 'all' restores every checkpoint in the run — used for
   * inline instance runs whose entire recorded work is being undone.
   */
  selection: 'anchored' | 'all'
}

type RewindEntry = {
  runDir: string
  meta: WriteCheckpointMeta
  createdAtMs: number
  scopeSeq: number
  indexPos: number
}

function collectRewindEntries(
  scopes: RewindRunScope[],
  fromUserMessageIndex: number
): RewindEntry[] {
  const entries: RewindEntry[] = []
  for (let scopeSeq = 0; scopeSeq < scopes.length; scopeSeq++) {
    const scope = scopes[scopeSeq]!
    const index = loadIndex(scope.runDir)
    for (let indexPos = index.checkpoints.length - 1; indexPos >= 0; indexPos--) {
      const entry = index.checkpoints[indexPos]!
      const meta = loadMeta(scope.runDir, entry.id)
      if (!meta) continue
      if (scope.selection === 'anchored' && !isRewoundCheckpoint(meta, fromUserMessageIndex)) {
        continue
      }
      const ts = Date.parse(meta.createdAt)
      entries.push({
        runDir: scope.runDir,
        meta,
        createdAtMs: Number.isFinite(ts) ? ts : 0,
        scopeSeq,
        indexPos
      })
    }
  }
  // Restore the newest action first: each restore's post-write hash guard
  // expects exactly the content produced by the next-newer undone write, so
  // strict reverse-chronological order keeps the guard chain verifiable even
  // when a parent run and its inline instances touched the same files.
  entries.sort(
    (a, b) => b.createdAtMs - a.createdAtMs || a.scopeSeq - b.scopeSeq || b.indexPos - a.indexPos
  )
  return entries
}

/** One rewound write of a file, and the checkpoint that holds its copy. */
type RewoundWrite = { file: CheckpointFileEntry; checkpointDir: string }

/**
 * Read-only preview of where rewindWritesFromScopes will leave each file;
 * mutates nothing. With the workspace it walks each file's rewound writes as
 * the rewind does. Without it there is nothing to walk on, so a file's newest
 * rewound write stands for it and nothing is marked edited.
 */
export function planRewindWritesAcrossRuns(
  scopes: RewindRunScope[],
  fromUserMessageIndex: number,
  workspaceRoot?: string
): RewindWritesPlan {
  const entries = collectRewindEntries(scopes, fromUserMessageIndex)
  // Each file's rewound writes in the order the rewind takes them: newest first.
  const writesByPath = new Map<string, RewoundWrite[]>()
  for (const entry of entries) {
    const checkpointDir = join(entry.runDir, 'checkpoints', entry.meta.id)
    for (const file of [...entry.meta.files].reverse()) {
      const writes = writesByPath.get(file.path)
      if (writes) writes.push({ file, checkpointDir })
      else writesByPath.set(file.path, [{ file, checkpointDir }])
    }
  }
  const files = [...writesByPath.values()].map((writes) => {
    const newest = writes[0]!.file
    const asNewest = { path: newest.path, action: newest.action, undoable: newest.undoable }
    return workspaceRoot ? (planFileRewind(workspaceRoot, writes) ?? asNewest) : asNewest
  })
  return {
    checkpointIds: entries.map((entry) => entry.meta.id),
    files: files.sort((a, b) => a.path.localeCompare(b.path))
  }
}

/**
 * Walk one file's rewound writes, newest first, on content hashes: the walk
 * rewindWritesFromScopes makes on disk. Each restore takes the file back a
 * run. A change made since stops it; a write with no copy stops it unless
 * the next write can be taken back past it (goesPastNoCopy).
 * Null when the file cannot be read to walk on.
 */
function planFileRewind(workspaceRoot: string, writes: RewoundWrite[]): RewindWritesPlanFile | null {
  const newest = writes[0]!.file
  try {
    const now = hashExistingFile(resolveInsideWorkspace(workspaceRoot, newest.path))
    let content = now
    const taken: CheckpointFileEntry[] = []
    // Writes with no copy the walk has reached but not yet got past.
    let noCopy: CheckpointFileEntry[] = []
    let edited = false
    for (const { file, checkpointDir } of writes) {
      if (!file.undoable) {
        noCopy.push(file)
        continue
      }
      const blob = file.action === 'created' ? null : blobPathFor(checkpointDir, file.path)
      if (noCopy.length > 0 && !goesPastNoCopy(content, blob, file)) break
      const state = writeState(content, blob, file)
      if (state === 'edited') {
        edited = true
        break
      }
      // 'restored' leaves the file as it is: it already holds this write's copy.
      if (state === 'writable') content = blob ? hashExistingFile(blob) : undefined
      taken.push(...noCopy, file)
      noCopy = []
    }
    const stopped = edited || noCopy.length > 0
    return {
      path: newest.path,
      action: taken.length > 0 ? undoneAction(taken) : newest.action,
      undoable: noCopy.length === 0,
      ...(edited ? { edited: true } : {}),
      ...(stopped && content !== now ? { partway: true } : {})
    }
  } catch {
    return null
  }
}

/**
 * The letter for what taking back `taken` (newest first) undoes: a file the
 * oldest of them created goes, one the newest deleted comes back, and any
 * other is put back as it was.
 */
function undoneAction(taken: CheckpointFileEntry[]): CheckpointFileAction {
  if (taken[taken.length - 1]!.action === 'created') return 'created'
  return taken[0]!.action === 'deleted' ? 'deleted' : 'modified'
}

/**
 * Force-restore every selected write checkpoint (newest first), each file
 * until a change made since stops it, or a write with no copy it cannot get
 * past without destroying more than older runs' own work. Selection is
 * per scope: parent runs filter by the rewind anchor, inline instance runs are
 * included whole. Ignores UI Keep/Discard and prior undone flags so
 * edit-and-resend can rewind multi-turn history.
 *
 * Checkpoints without `anchorUserMessageIndex` (legacy runs) are only restored
 * when rewinding to the start of the transcript (`fromUserMessageIndex === 0`).
 * Including them on a mid-history rewind would undo earlier-turn writes.
 *
 * All or nothing: when an undoable file cannot be restored, the files already
 * restored are put back and `undoableRestoreFailed` is set.
 */
export function rewindWritesFromScopes(
  workspaceRoot: string,
  scopes: RewindRunScope[],
  fromUserMessageIndex: number
): RewindWritesResult {
  for (const scope of scopes) discardWriteCheckpoint(scope.runDir)
  // Where the rewind leaves each file, newest first: one entry per file, as
  // in the preview, however many rewound runs changed it. Each restore takes
  // the file back a run; the first thing to stop it after that (a change made
  // since, or a write with no copy) says why it is not all the way back.
  const leftAs = new Map<string, RestoreOutcome>()
  // Files whose walk has stopped: older runs leave them as they are. Their
  // copies would go back over a change made since, unguarded when a run never
  // finalized (a crash leaves no hash). Past a write with no copy the walk
  // goes on only where that destroys nothing (goesPastNoCopy).
  const stopped = new Set<string>()

  const entries = collectRewindEntries(scopes, fromUserMessageIndex)
  // A copy that is gone would fail its restore halfway through, after newer
  // files were already put back. Check them all first and touch nothing.
  for (const entry of entries) {
    const checkpointDir = join(entry.runDir, 'checkpoints', entry.meta.id)
    for (const file of entry.meta.files) {
      if (!file.undoable || file.action === 'created') continue
      if (!existsSync(blobPathFor(checkpointDir, file.path))) {
        logger.warn('Rewind stopped before restoring: a checkpoint copy is missing', {
          scope: 'agent',
          path: file.path
        })
        return rewindFailed({ path: file.path, reason: 'its saved copy is missing' }, [])
      }
    }
  }

  // An I/O error (EPERM, EBUSY, a full disk) only shows up while writing, so
  // each restore notes what it overwrites first, a failure puts all of it back,
  // and no checkpoint is marked until every file is through.
  const undo = new RewindUndo()
  try {
    for (const entry of entries) {
      const checkpointDir = join(entry.runDir, 'checkpoints', entry.meta.id)
      for (const file of [...entry.meta.files].reverse()) {
        if (
          !stopped.has(file.path) &&
          leftAs.get(file.path) === 'skipped' &&
          !goesPastNoCopyOnDisk(workspaceRoot, checkpointDir, file)
        ) {
          stopped.add(file.path)
        }
        if (stopped.has(file.path)) {
          // A newer run stopped the walk: this run's write stays under it.
          file.resolved = 'kept'
          continue
        }
        let outcome: RestoreOutcome
        try {
          outcome = restoreFile(workspaceRoot, checkpointDir, file, undo)
        } catch (err) {
          logger.warn('Rewind could not restore a file; putting back what it changed', {
            scope: 'agent',
            path: file.path,
            err
          })
          return rewindFailed({ path: file.path, reason: failureReason(err) }, undo.rollBack())
        }
        if (outcome === 'restored') {
          file.resolved = 'discarded'
        } else if (outcome === 'conflict') {
          // Changed after the agent wrote it: left as it is, by older runs
          // too. The rewind goes on with the other files.
          file.resolved = 'kept'
          stopped.add(file.path)
        }
        leftAs.set(file.path, outcome)
      }
    }
  } finally {
    undo.dispose()
  }

  for (const entry of entries) markCheckpointFullyResolved(entry.runDir, entry.meta)
  const leftAsOf = (outcome: RestoreOutcome): string[] =>
    [...leftAs].filter(([, left]) => left === outcome).map(([path]) => path)
  return {
    checkpointIds: entries.map((entry) => entry.meta.id),
    restored: leftAsOf('restored'),
    skipped: leftAsOf('skipped'),
    edited: leftAsOf('conflict'),
    undoableRestoreFailed: false
  }
}

function rewindFailed(failure: { path: string; reason: string }, notPutBack: string[]): RewindWritesResult {
  return {
    checkpointIds: [],
    restored: [],
    skipped: [],
    edited: [],
    undoableRestoreFailed: true,
    failure,
    ...(notPutBack.length > 0 ? { notPutBack } : {})
  }
}

/** A short why for the user: the error code when there is one. */
function failureReason(err: unknown): string {
  const code = (err as NodeJS.ErrnoException | null)?.code
  if (typeof code === 'string' && code) return code
  return err instanceof Error ? err.message : String(err)
}

/** Single-run rewind (parent scope) — see rewindWritesFromScopes. */
export function rewindWritesFrom(
  runDir: string,
  workspaceRoot: string,
  fromUserMessageIndex: number
): RewindWritesResult {
  return rewindWritesFromScopes(
    workspaceRoot,
    [{ runDir, selection: 'anchored' }],
    fromUserMessageIndex
  )
}

/** Single-run preview (parent scope) — see planRewindWritesAcrossRuns. */
export function planRewindWrites(runDir: string, fromUserMessageIndex: number): RewindWritesPlan {
  return planRewindWritesAcrossRuns([{ runDir, selection: 'anchored' }], fromUserMessageIndex)
}

/** Test helper: clear all active sessions. */
export function resetWriteCheckpointsForTests(): void {
  activeSessions.clear()
}
