import {
  chmodSync,
  copyFileSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  realpathSync,
  rmdirSync,
  rmSync,
  statSync,
  writeFileSync,
  type Stats
} from 'fs'
import { copyFile, mkdir, readFile, readdir, rm, stat } from 'fs/promises'
import { tmpdir } from 'os'
import { basename, dirname, join, relative } from 'path'
import { createHash, randomUUID } from 'crypto'
import { realpathIfExists, resolveInsideWorkspace } from '../workspace/safePath'
import { atomicWriteFile, atomicWriteJson } from '@main/storage/atomicWrite'
import { logger } from '../../shared/logger'
import { readJsonDocCached } from './jsonDocCache'
import { looksLikeWorkspacePath } from './pathPlausibility'
import { extraRootFor, isAbsolutePathLike, isPathInsideRoot, slashPath } from '../../shared/extraRoots'

export type CheckpointFileAction = 'created' | 'modified' | 'deleted'

export type CheckpointFileResolution = 'kept' | 'discarded'

export type CheckpointFileEntry = {
  /** Workspace-relative path using forward slashes. */
  path: string
  action: CheckpointFileAction
  /** False for recursive directory deletes (v1 cannot restore). */
  undoable: boolean
  /**
   * SHA-256 of workspace content after the write (created/modified).
   * Restore skips when current content differs (user edit after the agent).
   */
  hash?: string
  /** Set when the user Keep/Discard resolves this path. */
  resolved?: CheckpointFileResolution
  /** Revert was refused because the file was edited after the agent wrote it. */
  conflicted?: boolean
  /**
   * What an Undo found where the agent's write was, so it can be brought back:
   * `copy`, the agent's version is kept under `after/`; `absent`, the agent
   * had deleted the file. Absent when the Undo changed nothing to bring back.
   */
  redo?: 'copy' | 'absent'
  /** Settled by a rewind, not by Keep or Undo: it is never reopened for review. */
  rewound?: boolean
  /**
   * When this path entered the checkpoint — its first write this invoke. The
   * `writes_checkpoint` event is only flushed at invoke end, after every
   * check the turn ran, so the receipt dates the mutation by this instead.
   * Absent on checkpoints written before the field existed.
   */
  recordedAt?: string
  /**
   * The latest write to a path already in the checkpoint by a tool the
   * verification tracker cannot see by name (terminal, MCP, lsp rename,
   * merge, git_apply, the watcher). Edit tools re-dating a path is left to
   * their own tool_result. Absent when the path was written once.
   */
  lastMutatedAt?: string
}

export type WriteCheckpointMeta = {
  id: string
  createdAt: string
  undone?: boolean
  /** True when every file is Keep/Discard resolved (or discarded via Undo). */
  resolved?: boolean
  /**
   * Index of the user message this invoke was answering (messages already include
   * that user turn when the checkpoint session starts). Used by edit-and-rewind.
   */
  anchorUserMessageIndex?: number
  /**
   * The task's added folders when this turn ran (extraRoots.ts). A file in
   * one is keyed by its absolute path, forward slashes, and is restored only
   * while it is still inside a folder listed here.
   */
  extraRoots?: string[]
  files: CheckpointFileEntry[]
}

export type CheckpointIndex = {
  checkpoints: Array<{ id: string; createdAt: string; undone?: boolean }>
}

const activeSessions = new Map<string, InvokeWriteCheckpoint>()

/** Checkpoint IDs are UUIDs generated by this module; never trust external input. */
const CHECKPOINT_ID_RE = /^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/

function assertValidCheckpointId(id: string): void {
  if (!CHECKPOINT_ID_RE.test(id)) {
    throw new Error(`Invalid checkpoint id: ${id.slice(0, 64)}`)
  }
}

function normalizeRelPath(rel: string): string {
  return rel.replace(/\\/g, '/')
}

function toCheckpointRelPath(workspaceRoot: string, pathArg: string): string {
  try {
    const resolved = resolveInsideWorkspace(workspaceRoot, pathArg)
    const rel = normalizeRelPath(relative(realpathIfExists(workspaceRoot), resolved))
    if (rel && !rel.startsWith('..')) return rel
  } catch {
    /* fall through to slash-normalize */
  }
  return normalizeRelPath(pathArg)
}

/**
 * Where a checkpoint key points. A workspace file's key is relative to the
 * workspace; a file in an added folder (extraRoots.ts) is keyed by its
 * absolute path and resolves only inside one of `extraRoots`, under the same
 * symlink-escape check as the workspace.
 */
export function resolveCheckpointPath(
  workspaceRoot: string,
  key: string,
  extraRoots: readonly string[] | undefined
): string {
  if (!isAbsolutePathLike(key) || !extraRoots?.length) return resolveInsideWorkspace(workspaceRoot, key)
  try {
    return resolveInsideWorkspace(workspaceRoot, key)
  } catch (err) {
    const root = extraRootFor(key, extraRoots)
    if (!root) throw err
    return resolveInsideWorkspace(root, key)
  }
}

/** The added folders a checkpoint recorded, read once per checkpoint dir. */
const checkpointRootsCache = new Map<string, string[]>()

function checkpointExtraRoots(checkpointDir: string): string[] {
  const hit = checkpointRootsCache.get(checkpointDir)
  if (hit) return hit
  let roots: string[] = []
  try {
    const meta = JSON.parse(readFileSync(join(checkpointDir, 'meta.json'), 'utf8')) as { extraRoots?: unknown }
    if (Array.isArray(meta.extraRoots)) roots = meta.extraRoots.filter((r): r is string => typeof r === 'string')
  } catch {
    roots = []
  }
  if (checkpointRootsCache.size >= 256) checkpointRootsCache.clear()
  checkpointRootsCache.set(checkpointDir, roots)
  return roots
}

/** resolveCheckpointPath for a restore that has only the checkpoint's dir. */
function resolveEntryPath(workspaceRoot: string, checkpointDir: string, key: string): string {
  if (!isAbsolutePathLike(key)) return resolveInsideWorkspace(workspaceRoot, key)
  return resolveCheckpointPath(workspaceRoot, key, checkpointExtraRoots(checkpointDir))
}

/** A key for a file in an added folder: absolute, so it cannot collide with a workspace path. */
function isExtraRootKey(key: string): boolean {
  return isAbsolutePathLike(key)
}

/**
 * Hashes already taken, keyed by path and the exact file version they were
 * taken at. One path gets hashed repeatedly: a turn stamps its writes, a
 * restore compares the file against its copy, and a rewind preview and the
 * rewind itself re-walk the same writes. A restore reads a file and then
 * writes it, so an entry is only reusable while the file is provably the same
 * one — nanosecond mtime/ctime (two same-size writes inside one millisecond
 * are ordinary on a fast disk) plus the size. A stale hit here would read a
 * user's change as the agent's output and let a restore overwrite it, so a
 * mismatch re-reads rather than trusts.
 */
const hashCache = new Map<string, { size: number; mtimeNs: number; ctimeNs: number; hash: string }>()
const HASH_CACHE_MAX = 512

/** The digest of `path` when it is byte for byte the version last read. */
function hashFromCache(path: string, st: Stats): string | undefined {
  const hit = hashCache.get(path)
  if (!hit) return undefined
  if (hit.size !== st.size) return undefined
  if (hit.mtimeNs !== Math.trunc(st.mtimeMs * 1e6)) return undefined
  if (hit.ctimeNs !== Math.trunc(st.ctimeMs * 1e6)) return undefined
  return hit.hash
}

function rememberHash(path: string, st: Stats, hash: string): void {
  if (hashCache.size >= HASH_CACHE_MAX && !hashCache.has(path)) {
    const oldest = hashCache.keys().next().value
    if (oldest !== undefined) hashCache.delete(oldest)
  }
  hashCache.set(path, {
    size: st.size,
    mtimeNs: Math.trunc(st.mtimeMs * 1e6),
    ctimeNs: Math.trunc(st.ctimeMs * 1e6),
    hash
  })
}

/** sha256 of a file's bytes, or undefined when there is no file to read. */
function hashExistingFile(path: string): string | undefined {
  let st: Stats
  try {
    st = statSync(path)
  } catch {
    hashCache.delete(path)
    return undefined
  }
  if (!st.isFile()) return undefined
  const hit = hashFromCache(path, st)
  if (hit) return hit
  try {
    const hash = createHash('sha256').update(readFileSync(path)).digest('hex')
    rememberHash(path, st, hash)
    return hash
  } catch {
    return undefined
  }
}

/**
 * hashExistingFile without blocking the main thread: `fs/promises` only, same
 * digest and same `undefined` for a path that is not a readable file. The
 * turn's own stamping and the rewind's per-file walk use this, so neither
 * waits on disk reads.
 */
async function hashExistingFileAsync(path: string): Promise<string | undefined> {
  let st: Stats
  try {
    st = await stat(path)
  } catch {
    return undefined
  }
  if (!st.isFile()) return undefined
  const hit = hashFromCache(path, st)
  if (hit) return hit
  try {
    const hash = createHash('sha256').update(await readFile(path)).digest('hex')
    rememberHash(path, st, hash)
    return hash
  } catch {
    return undefined
  }
}

/**
 * An added-folder file's copy: flat under `_extra/`, named by its key's hash.
 * Its absolute key (a drive letter, a leading slash) cannot be a folder path
 * under the checkpoint, and must not land beside the workspace's copies.
 */
function extraBlobPathFor(checkpointDir: string, area: 'files' | 'after', key: string): string {
  return join(checkpointDir, area, '_extra', createHash('sha256').update(slashPath(key)).digest('hex'))
}

function blobPathFor(checkpointDir: string, relPath: string): string {
  if (isExtraRootKey(relPath)) return extraBlobPathFor(checkpointDir, 'files', relPath)
  const parts = normalizeRelPath(relPath).split('/').filter(Boolean)
  if (parts.some((p) => p === '..')) {
    throw new Error('Invalid checkpoint path')
  }
  return join(checkpointDir, 'files', ...parts)
}

/** Where an Undo keeps the agent's version of a path, to bring it back. */
function afterImagePathFor(checkpointDir: string, relPath: string): string {
  if (isExtraRootKey(relPath)) return extraBlobPathFor(checkpointDir, 'after', relPath)
  const parts = normalizeRelPath(relPath).split('/').filter(Boolean)
  if (parts.some((p) => p === '..')) {
    throw new Error('Invalid checkpoint path')
  }
  return join(checkpointDir, 'after', ...parts)
}

/** Most files a directory delete snapshots for undo; past it, none of the tree is undoable. */
const DIR_RESTORE_FILE_CAP = 20_000
let dirRestoreFileCap = DIR_RESTORE_FILE_CAP

/** Test helper — a small cap, so the overflow path runs without 20,000 files. */
export function setDirRestoreFileCapForTests(cap: number | null): void {
  dirRestoreFileCap = cap ?? DIR_RESTORE_FILE_CAP
}

/** Delete these paths' copies, a batch at a time so thousands do not queue at once. */
async function removeBlobs(checkpointDir: string, relPaths: readonly string[]): Promise<void> {
  for (let i = 0; i < relPaths.length; i += 64) {
    await Promise.all(
      relPaths
        .slice(i, i + 64)
        .map((relPath) => rm(blobPathFor(checkpointDir, relPath), { force: true }).catch(() => undefined))
    )
  }
}

/** The index's well-formed entries; anything else in it is ignored. */
function indexEntries(raw: unknown): CheckpointIndex['checkpoints'] {
  const list = (raw as { checkpoints?: unknown } | null)?.checkpoints
  return (Array.isArray(list) ? list : []).filter(
    (c): c is { id: string; createdAt: string; undone?: boolean } =>
      c != null && typeof c === 'object' && typeof (c as { id?: unknown }).id === 'string' &&
      CHECKPOINT_ID_RE.test((c as { id: string }).id)
  )
}

/** runDirs whose index.json was unreadable and has been rebuilt from disk. */
const rebuiltIndexRuns = new Set<string>()

/**
 * The index is the only way back to a run's checkpoints, and it is one JSON
 * file that a crash or a full disk can leave half-written. Reading it used to
 * swallow the parse error and answer "no checkpoints", so the next save wrote a
 * fresh index over the only record of every earlier turn's undo copies — each
 * still on disk, none of them reachable. An unreadable index is rebuilt from
 * the checkpoint dirs beside it instead, and the file it replaced is kept.
 */
function loadIndex(runDir: string): CheckpointIndex {
  const p = join(runDir, 'checkpoints', 'index.json')
  if (!existsSync(p)) return { checkpoints: [] }
  try {
    return { checkpoints: indexEntries(JSON.parse(readFileSync(p, 'utf8'))) }
  } catch (err) {
    const recovered = indexEntriesFromDirs(join(runDir, 'checkpoints'))
    if (recovered.length > 0) rebuiltIndexRuns.add(runDir)
    logger.warn('Checkpoint index unreadable; recovered its entries from the checkpoint dirs', {
      scope: 'agent',
      correlationId: basename(runDir),
      code: 'CHECKPOINT_INDEX_UNREADABLE',
      recovered: recovered.length,
      err
    })
    return { checkpoints: recovered }
  }
}

/** Every checkpoint dir beside the index that still has a readable meta, oldest first. */
function indexEntriesFromDirs(dir: string): CheckpointIndex['checkpoints'] {
  let names: string[]
  try {
    names = readdirSync(dir)
  } catch {
    return []
  }
  const out: CheckpointIndex['checkpoints'] = []
  for (const name of names) {
    if (!CHECKPOINT_ID_RE.test(name)) continue
    let meta: WriteCheckpointMeta
    try {
      meta = JSON.parse(readFileSync(join(dir, name, 'meta.json'), 'utf8')) as WriteCheckpointMeta
    } catch {
      continue
    }
    if (typeof meta.createdAt !== 'string') continue
    out.push({ id: name, createdAt: meta.createdAt, ...(meta.undone ? { undone: true } : {}) })
  }
  out.sort((a, b) => Date.parse(a.createdAt) - Date.parse(b.createdAt) || a.id.localeCompare(b.id))
  return out
}

function saveIndex(runDir: string, index: CheckpointIndex): void {
  const dir = join(runDir, 'checkpoints')
  mkdirSync(dir, { recursive: true })
  // One repair per rebuild: keep the file that could not be read beside the
  // one that replaces it, then write the rebuilt index. A backup that fails
  // leaves the unreadable file exactly as it was — the rebuild is repeated on
  // the next load rather than trading one lost record for another.
  if (rebuiltIndexRuns.delete(runDir) && !keepUnreadableIndex(join(dir, 'index.json'))) return
  atomicWriteJson(join(dir, 'index.json'), index)
}

/**
 * Keep the index a recovery is about to replace, beside it. False means the
 * copy failed, and the caller leaves the unreadable file in place rather than
 * destroying the only record of what it held.
 */
function keepUnreadableIndex(p: string): boolean {
  const backup = `${p}.unreadable-${Date.now()}`
  try {
    copyFileSync(p, backup)
    logger.warn('Kept an unreadable checkpoint index as a backup', {
      scope: 'storage',
      code: 'CHECKPOINT_INDEX_UNREADABLE',
      backup
    })
    return true
  } catch (err) {
    logger.warn('Could not back up an unreadable checkpoint index; leaving it untouched', {
      scope: 'storage',
      code: 'CHECKPOINT_INDEX_UNREADABLE',
      err
    })
    return false
  }
}

function loadMeta(runDir: string, id: string): WriteCheckpointMeta | null {
  assertValidCheckpointId(id)
  const p = join(runDir, 'checkpoints', id, 'meta.json')
  if (!existsSync(p)) return null
  try {
    return JSON.parse(readFileSync(p, 'utf8')) as WriteCheckpointMeta
  } catch {
    return null
  }
}

/** Read checkpoint meta for IPC persistence / hydration. */
export function getWriteCheckpointMeta(
  runDir: string,
  checkpointId: string
): WriteCheckpointMeta | null {
  // Soft no-op resolveWrites may pass ''; avoid assert throw → IPC_HANDLER.
  if (!checkpointId.trim() || !CHECKPOINT_ID_RE.test(checkpointId)) return null
  return loadMeta(runDir, checkpointId)
}

/**
 * Every checkpoint of a run, oldest first, with its meta. Read-only view for
 * summaries (the navigator's "Ready for review"); unreadable entries are
 * skipped rather than thrown.
 */
export function listCheckpointMetas(runDir: string): WriteCheckpointMeta[] {
  const out: WriteCheckpointMeta[] = []
  for (const entry of loadIndex(runDir).checkpoints) {
    const meta = loadMeta(runDir, entry.id)
    if (meta) out.push(entry.undone && !meta.undone ? { ...meta, undone: true } : meta)
  }
  return out
}

/**
 * listCheckpointMetas without blocking, for summaries asked for again and
 * again (the Changes list, the navigator). Reads go through the parse cache,
 * so a meta that has not changed is not read or parsed again — one large
 * directory delete's meta is 4 MB. The metas are shared between callers:
 * read them, never change them.
 */
export async function listCheckpointMetasAsync(runDir: string): Promise<readonly WriteCheckpointMeta[]> {
  const dir = join(runDir, 'checkpoints')
  const index = await readJsonDocCached(join(dir, 'index.json'))
  if (!index.ok) return []
  const out: WriteCheckpointMeta[] = []
  for (const entry of indexEntries(index.doc)) {
    const doc = await readJsonDocCached(join(dir, entry.id, 'meta.json'))
    if (!doc.ok || doc.doc == null || typeof doc.doc !== 'object') continue
    const meta = doc.doc as WriteCheckpointMeta
    out.push(entry.undone && !meta.undone ? { ...meta, undone: true } : meta)
  }
  return out
}

/** Where a checkpoint keeps the before-image of one workspace-relative path. */
export function checkpointBeforeImagePath(runDir: string, checkpointId: string, relPath: string): string {
  assertValidCheckpointId(checkpointId)
  return blobPathFor(join(runDir, 'checkpoints', checkpointId), relPath)
}

function saveMeta(runDir: string, meta: WriteCheckpointMeta): void {
  assertValidCheckpointId(meta.id)
  const dir = join(runDir, 'checkpoints', meta.id)
  mkdirSync(dir, { recursive: true })
  atomicWriteJson(join(dir, 'meta.json'), meta)
}

/** One turn (invoke) of agent writes; first prior per path wins. */
export class InvokeWriteCheckpoint {
  readonly id: string
  readonly createdAt: string
  readonly anchorUserMessageIndex: number | undefined
  private readonly runDir: string
  private readonly workspaceRoot: string
  private readonly files = new Map<string, CheckpointFileEntry>()
  /** Rel-paths with an in-flight async snapshot so first-path-wins stays racy-safe. */
  private readonly pendingRels = new Set<string>()
  private finalized = false
  /** See {@link otherWriteCount}. */
  private otherWrites = 0

  /** The task's added folders (extraRoots.ts): their files are keyed by absolute path. */
  private readonly extraRoots: readonly string[]

  constructor(
    runDir: string,
    workspaceRoot: string,
    anchorUserMessageIndex?: number,
    extraRoots: readonly string[] = []
  ) {
    this.id = randomUUID()
    this.createdAt = new Date().toISOString()
    this.runDir = runDir
    this.workspaceRoot = workspaceRoot
    this.anchorUserMessageIndex = anchorUserMessageIndex
    this.extraRoots = extraRoots
  }

  /** The tool's path resolved against the workspace, or the added folder it names. */
  private resolveArg(pathArg: string): string {
    return resolveCheckpointPath(this.workspaceRoot, pathArg, this.extraRoots)
  }

  /** What every meta this checkpoint writes carries besides its files. */
  private metaExtraRoots(): Pick<WriteCheckpointMeta, 'extraRoots'> {
    return this.extraRoots.length > 0 ? { extraRoots: [...this.extraRoots] } : {}
  }

  /**
   * Distinct workspace files this invoke has touched. The authoritative
   * mutation signal: unlike the edit-family tool names, it also covers
   * terminal writes, MCP writers, merges and watched out-of-band changes.
   */
  get writtenFileCount(): number {
    return this.files.size
  }

  /**
   * Writes recorded for tools other than the edit family (terminal, MCP, lsp
   * rename, merges, git_apply, the watcher), re-writes of an already-recorded
   * path included. The verification tracker sees edit tools by name; this is
   * how it sees everything else, per tool call, in the order it happened.
   * Edit tools stay out of it: their snapshot is taken before the write, so a
   * str_replace that then fails would otherwise read as a mutation.
   */
  get otherWriteCount(): number {
    return this.otherWrites
  }

  /** A non-edit-tool write to `rel`: count it, and date it if the path was already recorded. */
  private noteOtherWrite(rel: string): void {
    this.otherWrites += 1
    const existing = this.files.get(rel)
    if (existing) this.files.set(rel, { ...existing, lastMutatedAt: new Date().toISOString() })
  }

  /** Every entry goes through here so `recordedAt` is stamped once, on first write. */
  private putFile(rel: string, entry: CheckpointFileEntry): void {
    const recordedAt = this.files.get(rel)?.recordedAt ?? entry.recordedAt ?? new Date().toISOString()
    this.files.set(rel, { ...entry, recordedAt })
  }

  private realWorkspaceRoot(): string {
    return existsSync(this.workspaceRoot) ? realpathSync(this.workspaceRoot) : this.workspaceRoot
  }

  private relPathFromResolved(resolved: string): string {
    const rel = normalizeRelPath(relative(this.realWorkspaceRoot(), resolved))
    if (rel && !rel.startsWith('..') && !isAbsolutePathLike(rel)) return rel
    // Outside the workspace: an added folder's file keeps its absolute path.
    if (this.extraRoots.some((root) => isPathInsideRoot(resolved, root) && !isPathInsideRoot(root, resolved))) {
      return slashPath(resolved)
    }
    return rel
  }

  private checkpointDir(): string {
    return join(this.runDir, 'checkpoints', this.id)
  }

  /**
   * Snapshot prior content before a write or delete.
   * Async blob copy so the Electron main/UI thread is not blocked on disk I/O.
   * @param pathArg Path as the tool received it (workspace-relative or absolute inside root).
   */
  async recordPrior(
    pathArg: string,
    kind: 'write' | 'delete',
    opts?: {
      recursiveDir?: boolean
      /** The writer is not an edit-family tool — see {@link otherWriteCount}. */
      nonEditTool?: boolean
    }
  ): Promise<void> {
    if (this.finalized) return
    const resolved = this.resolveArg(pathArg)
    const rel = this.relPathFromResolved(resolved)
    if (!rel || rel.startsWith('..')) return
    // Recursive dir deletes are recorded as bare directory names (no extension
    // and no slash), which `looksLikeWorkspacePath` rejects; still allow the
    // checkpoint entry.
    if (!opts?.recursiveDir && !looksLikeWorkspacePath(rel)) return
    if (opts?.nonEditTool) this.noteOtherWrite(rel)
    if (this.files.has(rel) || this.pendingRels.has(rel)) return
    this.pendingRels.add(rel)
    const filesBefore = this.files.size
    try {
      await this.snapshotPrior(resolved, rel, kind, opts)
    } finally {
      this.pendingRels.delete(rel)
      // The write this protects has not happened yet, so `rel` is not hashed
      // here — hashing it would stamp the pre-write content as the agent's.
      if (this.files.size > filesBefore) await this.persistIncremental(rel)
    }
  }

  private async snapshotPrior(
    resolved: string,
    rel: string,
    kind: 'write' | 'delete',
    opts?: { recursiveDir?: boolean }
  ): Promise<void> {
    let st: Awaited<ReturnType<typeof stat>> | null = null
    try {
      st = await stat(resolved)
    } catch {
      st = null
    }
    if (kind === 'write') {
      if (!st) {
        this.putFile(rel, { path: rel, action: 'created', undoable: true })
        return
      }
      if (st.isDirectory()) {
        // Writing through edit tools targets files; ignore dirs.
        return
      }
      const dest = blobPathFor(this.checkpointDir(), rel)
      await mkdir(dirname(dest), { recursive: true })
      await copyFile(resolved, dest)
      this.putFile(rel, { path: rel, action: 'modified', undoable: true })
      return
    }

    // delete
    if (!st) return
    if (st.isDirectory()) {
      // Snapshot the directory tree so the delete is undoable. Each file becomes
      // its own 'deleted' checkpoint entry; restoring them recreates the original
      // tree (v1 could not restore directories — now fixed).
      let fileCount = 0
      let overflow = false
      const recordedChildren: string[] = []
      const snapshotTree = async (absDir: string): Promise<void> => {
        if (overflow) return
        let entries
        try {
          entries = await readdir(absDir, { withFileTypes: true })
        } catch {
          return
        }
        for (const entry of entries) {
          const abs = join(absDir, entry.name)
          if (entry.isDirectory()) {
            // entry.isDirectory() is false for symlinks, so symlink dirs are not followed.
            await snapshotTree(abs)
            if (overflow) return
            continue
          }
          if (!entry.isFile()) continue // skip symlinks / sockets / devices
          if (fileCount >= dirRestoreFileCap) {
            overflow = true
            return
          }
          fileCount++
          const childRel = this.relPathFromResolved(abs)
          if (!childRel || childRel.startsWith('..')) continue
          const dest = blobPathFor(this.checkpointDir(), childRel)
          try {
            await mkdir(dirname(dest), { recursive: true })
            await copyFile(abs, dest)
          } catch {
            continue
          }
          recordedChildren.push(childRel)
          this.putFile(childRel, { path: childRel, action: 'deleted', undoable: true })
        }
      }
      await snapshotTree(resolved)
      if (overflow) {
        // `overflow` can flip true only AFTER up to dirRestoreFileCap children
        // were already recorded as undoable. Marking just the parent
        // non-undoable left Undo restoring that partial subtree and reporting
        // it as a completed undo — a directory silently missing most of its
        // files. If the tree cannot be restored whole, none of it is undoable.
        for (const childRel of recordedChildren) {
          const entry = this.files.get(childRel)
          if (entry) this.putFile(childRel, { ...entry, undoable: false })
        }
        // Nothing reads a non-undoable entry's copy, so the copies already made
        // are dead weight — 119 MB for one 20,000-file node_modules delete.
        await removeBlobs(this.checkpointDir(), recordedChildren)
        logger.warn('Directory delete too large to snapshot for undo; marked non-undoable', {
          scope: 'agent',
          path: rel
        })
        this.putFile(rel, { path: rel, action: 'deleted', undoable: false })
      } else if (fileCount === 0) {
        // Empty directory: nothing to restore, but keep the entry for UI parity.
        this.putFile(rel, { path: rel, action: 'deleted', undoable: false })
      }
      return
    }
    const dest = blobPathFor(this.checkpointDir(), rel)
    await mkdir(dirname(dest), { recursive: true })
    await copyFile(resolved, dest)
    this.putFile(rel, { path: rel, action: 'deleted', undoable: true })
  }

  /**
   * Record a mutation observed after a tool ran (e.g. opaque terminal redirect).
   * First path wins — does not overwrite recordPrior entries.
   */
  async recordObservedMutation(
    pathArg: string,
    kind: 'created' | 'modified' | 'deleted',
    priorBlobPath?: string
  ): Promise<void> {
    if (this.finalized) return
    const resolved = this.resolveArg(pathArg)
    const rel = this.relPathFromResolved(resolved)
    if (!rel || rel.startsWith('..')) return
    if (!looksLikeWorkspacePath(rel)) return
    this.noteOtherWrite(rel)
    if (this.files.has(rel) || this.pendingRels.has(rel)) return
    this.pendingRels.add(rel)
    const filesBefore = this.files.size
    try {
      if (kind === 'created') {
        this.putFile(rel, { path: rel, action: 'created', undoable: true })
        return
      }

      let blobExists = false
      if (priorBlobPath) {
        try {
          await stat(priorBlobPath)
          blobExists = true
        } catch {
          blobExists = false
        }
      }
      if (!priorBlobPath || !blobExists) {
        this.putFile(rel, {
          path: rel,
          action: kind === 'modified' ? 'modified' : 'deleted',
          undoable: false
        })
        return
      }

      const dest = blobPathFor(this.checkpointDir(), rel)
      await mkdir(dirname(dest), { recursive: true })
      await copyFile(priorBlobPath, dest)
      this.putFile(rel, {
        path: rel,
        action: kind === 'modified' ? 'modified' : 'deleted',
        undoable: true
      })
    } finally {
      this.pendingRels.delete(rel)
      if (this.files.size > filesBefore) await this.persistIncremental()
    }
  }

  /**
   * Stamp every entry that can carry a post-write hash, except `skipRel`.
   * The turn's own persistence, off the main thread.
   */
  private async stampPostWriteHashesAsync(skipRel?: string): Promise<void> {
    for (const file of this.files.values()) {
      if (!this.needsPostWriteHash(file, skipRel)) continue
      await this.stampPostWriteHashAsync(file)
    }
  }

  /**
   * The same pass for finalize(), which is synchronous. One read per file the
   * turn left unhashed — the mid-turn persistence already stamped the rest.
   */
  private stampPostWriteHashesSync(): void {
    for (const file of this.files.values()) {
      if (!this.needsPostWriteHash(file)) continue
      this.stampPostWriteHashSync(file)
    }
  }

  private needsPostWriteHash(file: CheckpointFileEntry, skipRel?: string): boolean {
    return Boolean(file.undoable) && file.action !== 'deleted' && !file.hash && file.path !== skipRel
  }

  private async stampPostWriteHashAsync(file: CheckpointFileEntry): Promise<void> {
    try {
      const resolved = this.resolveArg(file.path)
      if (file.action === 'modified') {
        const prior = await hashExistingFileAsync(blobPathFor(this.checkpointDir(), file.path))
        if (prior && prior === (await hashExistingFileAsync(resolved))) return
      }
      const stamped = await hashExistingFileAsync(resolved)
      if (stamped) file.hash = stamped
    } catch {
      // Leave unhashed; restore then refuses rather than overwrites.
    }
  }

  private stampPostWriteHashSync(file: CheckpointFileEntry): void {
    try {
      const resolved = this.resolveArg(file.path)
      if (file.action === 'modified') {
        const prior = hashExistingFile(blobPathFor(this.checkpointDir(), file.path))
        if (prior && prior === hashExistingFile(resolved)) return
      }
      const stamped = hashExistingFile(resolved)
      if (stamped) file.hash = stamped
    } catch {
      // Leave unhashed; restore then refuses rather than overwrites.
    }
  }

  /**
   * Persist the in-progress checkpoint (meta + index entry) so a crash or power
   * loss mid-turn cannot erase the turn's undo data. Post-write hashes are
   * stamped here for the paths already written, so a turn that dies before
   * finalize still leaves meta that can tell the agent's output from a later
   * edit; an entry whose write has not landed is left unhashed, and an
   * unhashed entry is refused on restore rather than copied over.
   */
  private async persistIncremental(skipRel?: string): Promise<void> {
    if (this.finalized) return
    if (this.files.size === 0) return
    await this.stampPostWriteHashesAsync(skipRel)
    const meta: WriteCheckpointMeta = {
      id: this.id,
      createdAt: this.createdAt,
      ...(this.anchorUserMessageIndex !== undefined
        ? { anchorUserMessageIndex: this.anchorUserMessageIndex }
        : {}),
      ...this.metaExtraRoots(),
      files: [...this.files.values()]
    }
    try {
      saveMeta(this.runDir, meta)
      this.indexCheckpoint(meta)
    } catch (err) {
      logger.warn('Failed to persist incremental write checkpoint', {
        scope: 'agent',
        correlationId: basename(this.runDir),
        checkpointId: this.id,
        err
      })
    }
  }

  /**
   * Put this checkpoint in the run's index. An index that could not be read is
   * written back even when the entry is already there: a rebuild reads the
   * checkpoint dirs beside the index, and this checkpoint's own dir is one of
   * them, so "already listed" is exactly the case where the unreadable file on
   * disk would otherwise have been left in place unrepaired.
   */
  private indexCheckpoint(meta: WriteCheckpointMeta): void {
    const index = loadIndex(this.runDir)
    const listed = index.checkpoints.some((c) => c.id === meta.id)
    if (!listed) index.checkpoints.push({ id: meta.id, createdAt: meta.createdAt })
    if (listed && !rebuiltIndexRuns.has(this.runDir)) return
    saveIndex(this.runDir, index)
  }

  /**
   * Drop entries the turn proved changed nothing.
   *
   * `recordPrior` runs *before* the write it is protecting, because the prior
   * content has to be captured while it still exists. When the write then
   * fails, the speculative entry stays: run 874dad8f's `str_replace index.md`
   * failed with "File not found" and left `index.md` recorded created and
   * undoable for a file that never existed. It reached the Changes panel, and
   * the receipt told the user (and any awaiting parent) the run wrote it. Undo
   * deletes what a `created` entry names, so had anything else produced that
   * path later, Undo would have destroyed it.
   *
   * Only disk state decides — an entry survives unless the workspace itself
   * shows no net change, so a real mutation can never be dropped here. Two
   * kinds are deliberately left alone: non-undoable entries (a directory delete
   * too large to snapshot) are real changes that simply cannot be reverted, and
   * `deleted` entries are recorded by callers with their own lifecycles
   * (`recordObservedMutation` from the post-tool watcher, instance merges)
   * rather than by a snapshot taken ahead of a write that might fail.
   */
  private dropUnchangedEntries(): void {
    for (const [rel, file] of [...this.files]) {
      if (!file.undoable) continue
      if (file.action === 'deleted') continue
      let resolved: string
      try {
        resolved = this.resolveArg(file.path)
      } catch {
        continue
      }
      if (file.action === 'created') {
        // Nothing at the path it claims to have created.
        if (!existsSync(resolved)) this.files.delete(rel)
        continue
      }
      // `modified` snapshotted the prior content, so identical bytes on disk
      // mean the write never landed.
      let priorHash: string | undefined
      try {
        priorHash = hashExistingFile(blobPathFor(this.checkpointDir(), file.path))
      } catch {
        continue
      }
      if (!priorHash) continue
      if (hashExistingFile(resolved) === priorHash) this.files.delete(rel)
    }
  }

  /** Remove a mid-turn persisted checkpoint that finalize found to be empty. */
  private discardPersistedCheckpoint(): void {
    try {
      const index = loadIndex(this.runDir)
      const next = index.checkpoints.filter((c) => c.id !== this.id)
      if (next.length !== index.checkpoints.length) {
        saveIndex(this.runDir, { ...index, checkpoints: next })
      }
      rmSync(this.checkpointDir(), { recursive: true, force: true })
    } catch (err) {
      logger.warn('Failed to discard an empty write checkpoint', {
        scope: 'agent',
        correlationId: basename(this.runDir),
        checkpointId: this.id,
        err
      })
    }
  }

  /** Persist if any files were recorded; returns meta or null. */
  finalize(): WriteCheckpointMeta | null {
    if (this.finalized) return null
    this.finalized = true
    if (this.files.size === 0) return null
    this.dropUnchangedEntries()
    if (this.files.size === 0) {
      // persistIncremental may already have written this id to disk mid-turn.
      // Leaving it there would keep the phantom in the Changes panel under a
      // checkpoint finalize has disowned.
      this.discardPersistedCheckpoint()
      return null
    }
    this.stampPostWriteHashesSync()

    const meta: WriteCheckpointMeta = {
      id: this.id,
      createdAt: this.createdAt,
      ...(this.anchorUserMessageIndex !== undefined
        ? { anchorUserMessageIndex: this.anchorUserMessageIndex }
        : {}),
      ...this.metaExtraRoots(),
      files: [...this.files.values()]
    }
    saveMeta(this.runDir, meta)
    // Incremental persistence may already have registered this id mid-turn.
    this.indexCheckpoint(meta)
    return meta
  }
}

export function beginWriteCheckpoint(
  runDir: string,
  workspaceRoot: string,
  anchorUserMessageIndex?: number,
  /** The task's added folders this turn (extraRoots.ts). */
  extraRoots: readonly string[] = []
): InvokeWriteCheckpoint {
  const existing = activeSessions.get(runDir)
  if (existing) {
    // Same turn, or no new anchor stated: keep accumulating into it.
    if (
      anchorUserMessageIndex === undefined ||
      existing.anchorUserMessageIndex === anchorUserMessageIndex
    ) {
      return existing
    }
    // A different anchor means a new turn started without the previous invoke
    // finalizing. Reusing the old session would file THIS turn's undo records
    // under the PREVIOUS turn's anchor, and report the previous turn's files
    // as this turn's mutations (writtenFileCount). Close it out under its own
    // anchor so both turns stay separately undoable.
    activeSessions.delete(runDir)
    try {
      existing.finalize()
    } catch (err) {
      logger.warn('Failed to finalize a stale write checkpoint before a new turn', {
        scope: 'agent',
        correlationId: basename(runDir),
        err
      })
    }
  }
  const session = new InvokeWriteCheckpoint(runDir, workspaceRoot, anchorUserMessageIndex, extraRoots)
  activeSessions.set(runDir, session)
  return session
}

export function getWriteCheckpoint(runDir: string | undefined): InvokeWriteCheckpoint | undefined {
  if (!runDir) return undefined
  return activeSessions.get(runDir)
}

export function finalizeWriteCheckpoint(runDir: string): WriteCheckpointMeta | null {
  const session = activeSessions.get(runDir)
  activeSessions.delete(runDir)
  if (!session) return null
  return session.finalize()
}

/** Drop an open session without persisting (e.g. tests). */
export function discardWriteCheckpoint(runDir: string): void {
  activeSessions.delete(runDir)
}

export type ResolveWritesResult = {
  checkpointId: string
  kept: string[]
  discarded: string[]
  skipped: string[]
  /**
   * Paths whose revert was refused because the file was edited by the user after
   * the agent wrote it (content no longer matches). These stay unresolved so the
   * UI can surface "can't auto-revert" instead of falsely marking them reverted.
   */
  conflicted: string[]
  fullyResolved: boolean
}

function resolveCheckpointId(runDir: string, checkpointId?: string): string | null {
  if (checkpointId) assertValidCheckpointId(checkpointId)
  const index = loadIndex(runDir)
  let id = checkpointId
  if (!id) {
    for (let i = index.checkpoints.length - 1; i >= 0; i--) {
      const entry = index.checkpoints[i]!
      const meta = loadMeta(runDir, entry.id)
      if (meta && !meta.undone && !meta.resolved) {
        id = entry.id
        break
      }
    }
  }
  if (!id) return null
  assertValidCheckpointId(id)
  return id
}

/**
 * Where a file stands against the agent's write: `edited` when someone changed
 * it after the agent did (restoring would destroy that change), `restored`
 * when it already holds what restoring would put there, else `writable`.
 * `current` is the file's content hash, undefined when there is no file.
 * Restore passes what is on disk; the rewind preview passes what the newer
 * restores in its walk would leave, so the dialog says what the rewind will do.
 *
 * A write with no post-write hash is `edited` whenever the path holds content:
 * a checkpoint whose meta was persisted mid-turn (a crash before finalize
 * stamped hashes) cannot tell the agent's output from anything written after
 * it, so it must not copy over or delete what is there. With no file on disk
 * there is nothing to destroy and the copy still recreates the old one.
 */
function writeState(current: string | undefined, blob: string | null, file: CheckpointFileEntry): 'edited' | 'restored' | 'writable' {
  if (file.action === 'created') {
    if (!current) return 'writable'
    return !file.hash || current !== file.hash ? 'edited' : 'writable'
  }
  if (!current || !blob) return 'writable'
  if (file.action === 'modified') {
    if (!file.hash) return 'edited'
    if (current === file.hash) return 'writable'
    return current === hashExistingFile(blob) ? 'restored' : 'edited'
  }
  // Deleted by the agent and back on disk: already the old file, or someone else's.
  return current === hashExistingFile(blob) ? 'restored' : 'edited'
}

/**
 * Past a write that kept no copy, whether a rewind can take back the next,
 * older write: only where that destroys nothing but the older write's own
 * work. The file is gone, or holds just what that write left (its hash) or
 * found (its copy); anything else may be the uncopied write's work, or yours.
 * A further write with no copy passes too, since nothing is done to it.
 */
function goesPastNoCopy(current: string | undefined, blob: string | null, file: CheckpointFileEntry): boolean {
  if (!file.undoable || !current) return true
  if (file.hash && current === file.hash) return true
  return writeState(current, blob, file) === 'restored'
}

/** goesPastNoCopy for the file on disk. One it cannot read stops the walk. */
function goesPastNoCopyOnDisk(workspaceRoot: string, checkpointDir: string, file: CheckpointFileEntry): boolean {
  if (!file.undoable) return true
  try {
    const blob = file.action === 'created' ? null : blobPathFor(checkpointDir, file.path)
    return goesPastNoCopy(hashExistingFile(resolveEntryPath(workspaceRoot, checkpointDir, file.path)), blob, file)
  } catch {
    return false
  }
}

/**
 * How much of what a rewind overwrites it holds in memory to put back if a
 * later restore fails. Past this it copies files to a temp directory instead,
 * so a rewind over large files cannot run the main process out of memory.
 */
const REWIND_UNDO_MEMORY_BYTES = 64 * 1024 * 1024
let rewindUndoMemoryBytes = REWIND_UNDO_MEMORY_BYTES

/** @internal Test hook: 0 copies every file a rewind overwrites to disk. */
export function setRewindUndoMemoryBytesForTests(bytes: number | null): void {
  rewindUndoMemoryBytes = bytes ?? REWIND_UNDO_MEMORY_BYTES
}

/** A file as a restore found it: its size and time, to tell whether it was touched, and its content. */
type FileBefore = { size: number; mtimeMs: number; mode: number } & ({ bytes: Buffer } | { copy: string })

type RestoreUndo = {
  path: string
  resolved: string
  /** Null when there was no file at the path. */
  before: FileBefore | null
  /** Outermost directory that was missing, which the restore creates. */
  missingDir?: string
}

/**
 * What a rewind changed, so one that fails partway can leave the workspace as
 * it was. A restore records its path before touching it, the failing one
 * included: a copy that fails partway can leave its file truncated or gone.
 */
class RewindUndo {
  private readonly undos: RestoreUndo[] = []
  private heldBytes = 0
  private copyDir: string | null = null
  private keepCopies = false

  /** Note what `resolved` holds now. Throws, having touched nothing, when it cannot. */
  record(path: string, resolved: string): void {
    this.undos.push({
      path,
      resolved,
      before: this.capture(resolved),
      missingDir: outermostMissingDir(dirname(resolved))
    })
  }

  private capture(resolved: string): FileBefore | null {
    let st: Stats
    try {
      st = statSync(resolved)
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code === 'ENOENT') return null
      throw err
    }
    // Only a file can be put back, so restoring over anything else fails here.
    if (!st.isFile()) throw new Error('not a file')
    const seen = { size: st.size, mtimeMs: st.mtimeMs, mode: st.mode }
    if (this.heldBytes + st.size <= rewindUndoMemoryBytes) {
      const bytes = readFileSync(resolved)
      this.heldBytes += bytes.length
      return { ...seen, bytes }
    }
    this.copyDir ??= mkdtempSync(join(tmpdir(), 'vyotiq-rewind-undo-'))
    const copy = join(this.copyDir, String(this.undos.length))
    copyFileSync(resolved, copy)
    return { ...seen, copy }
  }

  /** Put every recorded path back, newest first. Returns the ones it could not. */
  rollBack(): string[] {
    const notPutBack: string[] = []
    for (const undo of [...this.undos].reverse()) {
      try {
        putBack(undo)
      } catch (err) {
        logger.error('Rewind could not put a file back as it was', {
          scope: 'agent',
          path: undo.path,
          err
        })
        notPutBack.push(undo.path)
      }
    }
    // A copy may now be the only one left of a file it could not put back.
    this.keepCopies = notPutBack.length > 0
    return notPutBack
  }

  dispose(): void {
    if (!this.copyDir) return
    if (this.keepCopies) {
      logger.warn('Kept the rewind copies of files it could not put back', {
        scope: 'agent',
        path: this.copyDir
      })
      return
    }
    try {
      rmSync(this.copyDir, { recursive: true, force: true })
    } catch (err) {
      logger.warn('Failed to remove rewind copies', { scope: 'agent', path: this.copyDir, err })
    }
  }
}

/**
 * The outermost directory missing on the way to `dir`: what mkdir will create.
 * Not mkdirSync's own return value, which on Windows is the `\\?\` form and
 * never equals a path walked up with dirname().
 */
function outermostMissingDir(dir: string): string | undefined {
  let missing: string | undefined
  for (let d = dir; !existsSync(d); d = dirname(d)) {
    missing = d
    if (dirname(d) === d) break
  }
  return missing
}

/** True when the path still holds what the restore found there: it never got that far. */
function stillAsFound(undo: RestoreUndo): boolean {
  let st: Stats
  try {
    st = statSync(undo.resolved)
  } catch (err) {
    return undo.before === null && (err as NodeJS.ErrnoException).code === 'ENOENT'
  }
  const before = undo.before
  return before !== null && st.isFile() && st.size === before.size && st.mtimeMs === before.mtimeMs
}

function putBack(undo: RestoreUndo): void {
  const { resolved, before } = undo
  if (!stillAsFound(undo)) {
    if (!before) {
      rmSync(resolved, { force: true })
    } else if ('copy' in before) {
      copyFileSync(before.copy, resolved)
    } else {
      const mode = before.mode & 0o7777
      writeFileSync(resolved, before.bytes, { mode })
      // A file that is still there keeps the mode the restore gave it.
      if ((statSync(resolved).mode & 0o7777) !== mode) chmodSync(resolved, mode)
    }
  }
  if (undo.missingDir) removeEmptyDirs(dirname(resolved), undo.missingDir)
}

/** Remove `dir` and its parents up to `outermost` while they are empty. */
function removeEmptyDirs(dir: string, outermost: string): void {
  for (let d = dir; ; d = dirname(d)) {
    try {
      rmdirSync(d)
    } catch {
      return
    }
    if (d === outermost || dirname(d) === d) return
  }
}

type RestoreOutcome = 'restored' | 'skipped' | 'conflict'

/**
 * Put one file back as it was before the agent's write. Throws when it cannot:
 * a missing copy or an I/O error. With `undo`, notes what the path held before
 * changing it.
 */
function restoreFile(
  workspaceRoot: string,
  checkpointDir: string,
  file: CheckpointFileEntry,
  undo?: RewindUndo
): RestoreOutcome {
  if (!file.undoable) return 'skipped'
  const resolved = resolveEntryPath(workspaceRoot, checkpointDir, file.path)
  if (file.action === 'created') {
    if (writeState(hashExistingFile(resolved), null, file) === 'edited') {
      // User edited the file the agent created — refuse to delete their work.
      logger.warn('Skipping checkpoint restore; file changed after the agent write', {
        scope: 'agent',
        path: file.path
      })
      return 'conflict'
    }
    if (existsSync(resolved)) {
      undo?.record(file.path, resolved)
      rmSync(resolved, { force: true })
    }
    return 'restored'
  }
  const blob = blobPathFor(checkpointDir, file.path)
  if (!existsSync(blob)) throw new Error('its saved copy is missing')

  // A missing file falls through: the prior blob is restored, recreating what
  // the agent changed or deleted rather than leaving the deletion in place.
  const state = writeState(hashExistingFile(resolved), blob, file)
  if (state === 'restored') return 'restored'
  if (state === 'edited') {
    // Changed after the agent's write (or, for a delete, put back with other
    // content) — refuse to clobber it.
    logger.warn('Skipping checkpoint restore; file changed after the agent write', {
      scope: 'agent',
      path: file.path
    })
    return 'conflict'
  }

  undo?.record(file.path, resolved)
  mkdirSync(dirname(resolved), { recursive: true })
  copyFileSync(blob, resolved)
  return 'restored'
}

/** restoreFile for Undo, where a file that fails stays unresolved and the rest go on. */
function restoreOneFile(
  workspaceRoot: string,
  checkpointDir: string,
  file: CheckpointFileEntry
): RestoreOutcome | 'failed' {
  try {
    return restoreFile(workspaceRoot, checkpointDir, file)
  } catch (err) {
    logger.warn('Failed to restore checkpoint file', {
      scope: 'agent',
      path: file.path,
      err
    })
    return 'failed'
  }
}

function markCheckpointFullyResolved(runDir: string, meta: WriteCheckpointMeta): void {
  const idx = loadIndex(runDir)
  const entry = idx.checkpoints.find((c) => c.id === meta.id)
  if (entry) entry.undone = true
  saveIndex(runDir, idx)
  meta.resolved = true
  meta.undone = true
  saveMeta(runDir, meta)
}

/**
 * Keep and/or discard specific paths (or all unresolved when paths omitted for discard/keep all).
 *
 * Resolution is scoped to `checkpointId` when provided. When `checkpointId` is
 * omitted but `paths` are given, each path is resolved within the newest
 * unresolved checkpoint that recorded it — so a user can Keep/Discard a file
 * from any turn, not just the latest one. When both are omitted the latest
 * unresolved checkpoint is fully resolved (Undo / Keep-all / Discard-all).
 */
export function resolveWrites(
  runDir: string,
  workspaceRoot: string,
  opts: {
    checkpointId?: string
    action: 'keep' | 'discard'
    /** When omitted, applies to all unresolved files. */
    paths?: string[]
  }
): ResolveWritesResult {
  if (opts.checkpointId) {
    return resolveWritesInCheckpoint(runDir, workspaceRoot, opts.checkpointId, opts.action, opts.paths ?? null)
  }

  if (opts.paths && opts.paths.length > 0) {
    const index = loadIndex(runDir)
    const byCheckpoint = new Map<string, string[]>()
    for (const p of opts.paths) {
      const rel = toCheckpointRelPath(workspaceRoot, p)
      const cpId = findNewestUnresolvedCheckpointForPath(runDir, index, rel)
      if (!cpId) continue
      const arr = byCheckpoint.get(cpId) ?? []
      arr.push(rel)
      byCheckpoint.set(cpId, arr)
    }
    if (byCheckpoint.size === 0) {
      // Soft no-op: none of the paths are part of an actionable checkpoint.
      return {
        checkpointId: '',
        kept: [],
        discarded: [],
        skipped: [...opts.paths],
        conflicted: [],
        fullyResolved: true
      }
    }
    const kept: string[] = []
    const discarded: string[] = []
    const skipped: string[] = []
    const conflicted: string[] = []
    let allFullyResolved = true
    for (const [cpId, rels] of byCheckpoint) {
      const r = resolveWritesInCheckpoint(runDir, workspaceRoot, cpId, opts.action, rels)
      kept.push(...r.kept)
      discarded.push(...r.discarded)
      skipped.push(...r.skipped)
      conflicted.push(...r.conflicted)
      if (!r.fullyResolved) allFullyResolved = false
    }
    return {
      checkpointId: '',
      kept,
      discarded,
      skipped,
      conflicted,
      fullyResolved: allFullyResolved
    }
  }

  const id = resolveCheckpointId(runDir, undefined)
  if (!id) {
    // Soft no-op: UI may call Keep/Discard after the banner cleared or with no writes.
    return {
      checkpointId: '',
      kept: [],
      discarded: [],
      skipped: [],
      conflicted: [],
      fullyResolved: true
    }
  }
  return resolveWritesInCheckpoint(runDir, workspaceRoot, id, opts.action, null)
}

/** Newest unresolved checkpoint that still has an unresolved entry for `relPath`. */
function findNewestUnresolvedCheckpointForPath(
  runDir: string,
  index: CheckpointIndex,
  relPath: string
): string | null {
  for (let i = index.checkpoints.length - 1; i >= 0; i--) {
    const entry = index.checkpoints[i]!
    const meta = loadMeta(runDir, entry.id)
    if (!meta || meta.undone || meta.resolved) continue
    if (meta.files.some((f) => f.path === relPath && !f.resolved)) return meta.id
  }
  return null
}

function resolveWritesInCheckpoint(
  runDir: string,
  workspaceRoot: string,
  checkpointId: string,
  action: 'keep' | 'discard',
  paths: string[] | null
): ResolveWritesResult {
  const meta = loadMeta(runDir, checkpointId)
  if (!meta) throw new Error(`Checkpoint not found: ${checkpointId}`)
  if (meta.undone || meta.resolved) throw new Error('That checkpoint was already resolved')

  const targetPaths =
    paths && paths.length > 0
      ? new Set(paths.map((p) => toCheckpointRelPath(workspaceRoot, p)))
      : null

  const checkpointDir = join(runDir, 'checkpoints', checkpointId)
  const kept: string[] = []
  const discarded: string[] = []
  const skipped: string[] = []
  const conflicted: string[] = []

  for (const file of meta.files) {
    if (targetPaths && !targetPaths.has(file.path)) continue
    if (file.resolved) {
      skipped.push(file.path)
      continue
    }
    if (action === 'keep') {
      file.resolved = 'kept'
      kept.push(file.path)
      continue
    }
    // What the restore is about to replace, so the Undo itself can be undone.
    const redo = captureRedo(workspaceRoot, checkpointDir, file)
    const outcome = restoreOneFile(workspaceRoot, checkpointDir, file)
    if (outcome !== 'restored' && redo === 'copy') dropAfterImage(checkpointDir, file.path)
    if (outcome === 'restored') {
      file.resolved = 'discarded'
      if (redo) file.redo = redo
      else delete file.redo
      discarded.push(file.path)
    } else if (outcome === 'conflict') {
      // User edited the file after the agent wrote it; leave it unresolved and
      // surface it so the UI can explain why it cannot be auto-reverted.
      file.conflicted = true
      conflicted.push(file.path)
    } else if (outcome === 'failed') {
      // Undoable file whose restore failed (missing prior blob / I/O error):
      // keep it unresolved so the user can retry instead of falsely marking it
      // as reverted.
      skipped.push(file.path)
    } else {
      // Non-undoable: still mark discarded so the UI can clear it.
      file.resolved = 'discarded'
      skipped.push(file.path)
    }
  }

  // When every undoable file is handled, stamp leftover non-undoable as kept so
  // disk meta.resolved matches the UI fullyResolved banner clear.
  const undoablesDone = meta.files.every((f) => Boolean(f.resolved) || !f.undoable)
  if (undoablesDone) {
    for (const file of meta.files) {
      if (!file.resolved && !file.undoable) file.resolved = 'kept'
    }
  }
  const allHandled = meta.files.every((f) => Boolean(f.resolved))
  if (allHandled) {
    markCheckpointFullyResolved(runDir, meta)
  } else {
    saveMeta(runDir, meta)
  }

  return {
    checkpointId,
    kept,
    discarded,
    skipped,
    conflicted,
    fullyResolved: allHandled
  }
}

/**
 * Before an Undo restores a file, keep what the agent left there so the Undo
 * can be taken back: a copy of its version under `after/`, or `absent` when it
 * had deleted the file. Only while the file is exactly the agent's write — a
 * file changed since, or already back as it was, has nothing of the agent's to
 * bring back. Never throws: without a copy the Undo still goes ahead.
 */
function captureRedo(
  workspaceRoot: string,
  checkpointDir: string,
  file: CheckpointFileEntry
): 'copy' | 'absent' | null {
  if (!file.undoable) return null
  try {
    const resolved = resolveEntryPath(workspaceRoot, checkpointDir, file.path)
    const current = hashExistingFile(resolved)
    if (file.action === 'deleted') return current === undefined ? 'absent' : null
    if (!current || !file.hash || current !== file.hash) return null
    const dest = afterImagePathFor(checkpointDir, file.path)
    mkdirSync(dirname(dest), { recursive: true })
    copyFileSync(resolved, dest)
    return 'copy'
  } catch (err) {
    logger.warn('Could not keep the agent version before an Undo; it cannot be brought back', {
      scope: 'agent',
      path: file.path,
      err
    })
    return null
  }
}

function dropAfterImage(checkpointDir: string, relPath: string): void {
  try {
    rmSync(afterImagePathFor(checkpointDir, relPath), { force: true })
  } catch {
    // Dead weight at worst; retention frees the checkpoint with it.
  }
}

/**
 * Bring back the agent's write an Undo took away — only while the file is
 * still exactly what the Undo left (the copy from before the agent, or no file
 * for one it created). Anything else is a change made since: it is left alone.
 */
function redoFile(
  workspaceRoot: string,
  checkpointDir: string,
  file: CheckpointFileEntry
): 'reopened' | 'conflict' | 'failed' {
  try {
    const resolved = resolveEntryPath(workspaceRoot, checkpointDir, file.path)
    const current = hashExistingFile(resolved)
    if (file.action === 'created') {
      if (current !== undefined) return 'conflict'
    } else {
      const blob = blobPathFor(checkpointDir, file.path)
      const before = existsSync(blob) ? hashExistingFile(blob) : undefined
      if (!before || current !== before) return 'conflict'
    }
    if (file.redo === 'absent') {
      rmSync(resolved, { force: true })
      return 'reopened'
    }
    const after = afterImagePathFor(checkpointDir, file.path)
    const afterHash = hashExistingFile(after)
    if (!afterHash || (file.hash && afterHash !== file.hash)) return 'failed'
    mkdirSync(dirname(resolved), { recursive: true })
    copyFileSync(after, resolved)
    dropAfterImage(checkpointDir, file.path)
    return 'reopened'
  } catch (err) {
    logger.warn('Could not bring back an undone agent write', { scope: 'agent', path: file.path, err })
    return 'failed'
  }
}

export type ReopenWritesResult = {
  /** Back to waiting on Keep or Undo; an undone one has the agent's version again. */
  reopened: string[]
  /** Undone, then changed since: left as it is. */
  conflicted: string[]
  /** Not decided, settled by a rewind, or undone with nothing kept to bring back. */
  skipped: string[]
  /** Each checkpoint that changed, with its files as they are now. */
  checkpoints: Array<{ checkpointId: string; files: CheckpointFileEntry[] }>
}

/**
 * Take back a Keep or an Undo: the file waits on review again. A kept file
 * only changes its mark; an undone one gets the agent's version back (see
 * redoFile). Scoped to `checkpointId` when given — every decided file in it,
 * or just `paths` — else each of `paths` in the newest checkpoint that wrote
 * it, which is the decision the Changes list shows for it.
 */
export function reopenWrites(
  runDir: string,
  workspaceRoot: string,
  opts: { checkpointId?: string; paths?: string[] }
): ReopenWritesResult {
  const out: ReopenWritesResult = { reopened: [], conflicted: [], skipped: [], checkpoints: [] }
  const byCheckpoint = new Map<string, Set<string> | null>()
  if (opts.checkpointId) {
    assertValidCheckpointId(opts.checkpointId)
    byCheckpoint.set(
      opts.checkpointId,
      opts.paths?.length ? new Set(opts.paths.map((p) => toCheckpointRelPath(workspaceRoot, p))) : null
    )
  } else if (opts.paths?.length) {
    const metas = listCheckpointMetas(runDir)
    for (const p of opts.paths) {
      const rel = toCheckpointRelPath(workspaceRoot, p)
      const newest = [...metas].reverse().find((m) => m.files.some((f) => f.path === rel))
      if (!newest) {
        out.skipped.push(rel)
        continue
      }
      const set = byCheckpoint.get(newest.id) ?? new Set<string>()
      set.add(rel)
      byCheckpoint.set(newest.id, set)
    }
  } else {
    throw new Error('Name the files or the checkpoint to reopen')
  }

  for (const [id, rels] of byCheckpoint) {
    const meta = loadMeta(runDir, id)
    if (!meta) throw new Error(`Checkpoint not found: ${id}`)
    const checkpointDir = join(runDir, 'checkpoints', id)
    let changed = false
    for (const file of meta.files) {
      if (rels && !rels.has(file.path)) continue
      if (!file.resolved || file.rewound) {
        if (rels) out.skipped.push(file.path)
        continue
      }
      if (file.resolved === 'discarded') {
        if (!file.redo) {
          out.skipped.push(file.path)
          continue
        }
        const outcome = redoFile(workspaceRoot, checkpointDir, file)
        if (outcome === 'conflict') {
          out.conflicted.push(file.path)
          continue
        }
        if (outcome === 'failed') {
          out.skipped.push(file.path)
          continue
        }
      }
      delete file.resolved
      delete file.redo
      delete file.conflicted
      out.reopened.push(file.path)
      changed = true
    }
    if (!changed) continue
    if (meta.resolved || meta.undone) {
      delete meta.resolved
      delete meta.undone
      const idx = loadIndex(runDir)
      const entry = idx.checkpoints.find((c) => c.id === meta.id)
      if (entry?.undone) {
        delete entry.undone
        saveIndex(runDir, idx)
      }
    }
    saveMeta(runDir, meta)
    out.checkpoints.push({ checkpointId: meta.id, files: meta.files })
  }
  return out
}

/**
 * Keep every write of `paths` still waiting on review, in whichever turn left
 * it waiting: a commit took them as they are. Returns what it kept, by
 * checkpoint, so taking the commit back can reopen exactly those.
 */
export function keepWritesForPaths(
  runDir: string,
  workspaceRoot: string,
  paths: readonly string[]
): Array<{ checkpointId: string; path: string }> {
  const wanted = new Set(paths.map((p) => toCheckpointRelPath(workspaceRoot, p)))
  const kept: Array<{ checkpointId: string; path: string }> = []
  if (wanted.size === 0) return kept
  for (const entry of loadIndex(runDir).checkpoints) {
    const meta = loadMeta(runDir, entry.id)
    if (!meta || meta.undone || meta.resolved) continue
    const rels = meta.files.filter((f) => !f.resolved && wanted.has(f.path)).map((f) => f.path)
    if (rels.length === 0) continue
    const result = resolveWritesInCheckpoint(runDir, workspaceRoot, meta.id, 'keep', rels)
    for (const path of result.kept) kept.push({ checkpointId: meta.id, path })
  }
  return kept
}

/**
 * The newest turn's record of the task's write to `relPath` — the one per-file
 * Keep and Undo act on — and whether it is still waiting on review. Null when
 * no turn wrote it.
 */
export type AgentWriteRecord = {
  checkpointId: string
  /** As the checkpoint records it: workspace-relative, forward slashes. */
  path: string
  /** Kept, undone or settled by a rewind: no longer waiting on review. */
  settled: CheckpointFileResolution | 'rewound' | null
  undoable: boolean
  hash?: string
}

export function newestAgentWrite(runDir: string, workspaceRoot: string, relPath: string): AgentWriteRecord | null {
  const rel = toCheckpointRelPath(workspaceRoot, relPath)
  const metas = listCheckpointMetas(runDir)
  for (let i = metas.length - 1; i >= 0; i -= 1) {
    const meta = metas[i]!
    const file = meta.files.find((f) => f.path === rel)
    if (!file) continue
    const settled: AgentWriteRecord['settled'] = file.rewound
      ? 'rewound'
      : (file.resolved ?? (meta.undone || meta.resolved ? 'discarded' : null))
    return { checkpointId: meta.id, path: rel, settled, undoable: file.undoable, ...(file.hash ? { hash: file.hash } : {}) }
  }
  return null
}

/**
 * The review changed a write still waiting on it (one hunk undone or put
 * back): the file is still the agent's write to Keep, Undo or rewind, so its
 * hash moves with it. Only from exactly the agent's write — a file someone
 * changed since keeps reading as changed, so an Undo still refuses to
 * overwrite that change. Returns whether the record moved.
 */
export function restampAgentWrite(
  runDir: string,
  checkpointId: string,
  relPath: string,
  fromHash: string,
  toHash: string
): boolean {
  const meta = loadMeta(runDir, checkpointId)
  if (!meta || meta.undone || meta.resolved) return false
  const file = meta.files.find((f) => f.path === relPath)
  if (!file || file.resolved || !file.hash || file.hash !== fromHash) return false
  file.hash = toHash
  saveMeta(runDir, meta)
  return true
}

/**
 * A file is in at most one of restored, skipped and edited, however many
 * rewound runs changed it: the one that says where the rewind left it.
 */
export type RewindWritesResult = {
  checkpointIds: string[]
  /** Back to how they were before the rewound runs. */
  restored: string[]
  /** Changed by a write that kept no copy (not undoable), which the rewind could not get past. */
  skipped: string[]
  /** Changed after an agent's write: the rewind stops at that change and leaves it. */
  edited: string[]
  /**
   * True when an undoable file could not be restored — a missing copy or an
   * I/O error. The rewind then leaves the workspace as it was: files it had
   * already restored are put back, and no checkpoint is marked.
   */
  undoableRestoreFailed: boolean
  /** The file that stopped the rewind, and why: an error code, or what is missing. */
  failure?: { path: string; reason: string }
  /** Files the failed rewind changed and then could not put back as they were. */
  notPutBack?: string[]
}

/** Where the rewind will leave one file, in the terms of RewindWritesResult. */
export type RewindWritesPlanFile = {
  path: string
  /**
   * What the rewind undoes, as git would letter it: created (it removes the
   * file), modified (puts it back), deleted (brings it back).
   */
  action: CheckpointFileAction
  /** False when the rewind stops at a write that kept no copy (skipped). */
  undoable: boolean
  /** Changed after an agent's write: the rewind stops at that change (edited). */
  edited?: boolean
  /**
   * Stops (edited, or no copy) only after taking off later runs' writes: the
   * file changes, but not all the way back.
   */
  partway?: boolean
}

export type RewindWritesPlan = {
  checkpointIds: string[]
  files: RewindWritesPlanFile[]
}

/**
 * Selection rule for a rewind to `fromUserMessageIndex`, shared by the preview
 * (planRewindWrites) and execution (rewindWritesFrom) so they can never diverge.
 * Checkpoints without `anchorUserMessageIndex` (legacy runs) are only rewound
 * when rewinding to the start of the transcript (`fromUserMessageIndex === 0`).
 */
function isRewoundCheckpoint(meta: WriteCheckpointMeta, fromUserMessageIndex: number): boolean {
  const anchor = meta.anchorUserMessageIndex
  if (anchor !== undefined) return anchor >= fromUserMessageIndex
  return fromUserMessageIndex === 0
}

/** Per-run checkpoint selection for a rewind that spans multiple runs. */
export type RewindRunScope = {
  runDir: string
  /**
   * 'anchored' keeps the parent-run rule (isRewoundCheckpoint against the
   * rewind point); 'all' restores every checkpoint in the run — used for
   * inline instance runs whose entire recorded work is being undone.
   */
  selection: 'anchored' | 'all'
}

type RewindEntry = {
  runDir: string
  meta: WriteCheckpointMeta
  createdAtMs: number
  scopeSeq: number
  indexPos: number
}

function collectRewindEntries(
  scopes: RewindRunScope[],
  fromUserMessageIndex: number
): RewindEntry[] {
  const entries: RewindEntry[] = []
  for (let scopeSeq = 0; scopeSeq < scopes.length; scopeSeq++) {
    const scope = scopes[scopeSeq]!
    const index = loadIndex(scope.runDir)
    for (let indexPos = index.checkpoints.length - 1; indexPos >= 0; indexPos--) {
      const entry = index.checkpoints[indexPos]!
      const meta = loadMeta(scope.runDir, entry.id)
      if (!meta) continue
      if (scope.selection === 'anchored' && !isRewoundCheckpoint(meta, fromUserMessageIndex)) {
        continue
      }
      const ts = Date.parse(meta.createdAt)
      entries.push({
        runDir: scope.runDir,
        meta,
        createdAtMs: Number.isFinite(ts) ? ts : 0,
        scopeSeq,
        indexPos
      })
    }
  }
  // Restore the newest action first: each restore's post-write hash guard
  // expects exactly the content produced by the next-newer undone write, so
  // strict reverse-chronological order keeps the guard chain verifiable even
  // when a parent run and its inline instances touched the same files.
  entries.sort(
    (a, b) => b.createdAtMs - a.createdAtMs || a.scopeSeq - b.scopeSeq || b.indexPos - a.indexPos
  )
  return entries
}

/** One rewound write of a file, and the checkpoint that holds its copy. */
type RewoundWrite = { file: CheckpointFileEntry; checkpointDir: string }

/**
 * Read-only preview of where rewindWritesFromScopes will leave each file;
 * mutates nothing. With the workspace it walks each file's rewound writes as
 * the rewind does. Without it there is nothing to walk on, so a file's newest
 * rewound write stands for it and nothing is marked edited.
 */
export function planRewindWritesAcrossRuns(
  scopes: RewindRunScope[],
  fromUserMessageIndex: number,
  workspaceRoot?: string
): RewindWritesPlan {
  const entries = collectRewindEntries(scopes, fromUserMessageIndex)
  // Each file's rewound writes in the order the rewind takes them: newest first.
  const writesByPath = new Map<string, RewoundWrite[]>()
  for (const entry of entries) {
    const checkpointDir = join(entry.runDir, 'checkpoints', entry.meta.id)
    for (const file of [...entry.meta.files].reverse()) {
      const writes = writesByPath.get(file.path)
      if (writes) writes.push({ file, checkpointDir })
      else writesByPath.set(file.path, [{ file, checkpointDir }])
    }
  }
  const files = [...writesByPath.values()].map((writes) => {
    const newest = writes[0]!.file
    const asNewest = { path: newest.path, action: newest.action, undoable: newest.undoable }
    return workspaceRoot ? (planFileRewind(workspaceRoot, writes) ?? asNewest) : asNewest
  })
  return {
    checkpointIds: entries.map((entry) => entry.meta.id),
    files: files.sort((a, b) => a.path.localeCompare(b.path))
  }
}

/**
 * Walk one file's rewound writes, newest first, on content hashes: the walk
 * rewindWritesFromScopes makes on disk. Each restore takes the file back a
 * run. A change made since stops it; a write with no copy stops it unless
 * the next write can be taken back past it (goesPastNoCopy).
 * Null when the file cannot be read to walk on.
 */
function planFileRewind(workspaceRoot: string, writes: RewoundWrite[]): RewindWritesPlanFile | null {
  const newest = writes[0]!.file
  try {
    const now = hashExistingFile(resolveEntryPath(workspaceRoot, writes[0]!.checkpointDir, newest.path))
    let content = now
    const taken: CheckpointFileEntry[] = []
    // Writes with no copy the walk has reached but not yet got past.
    let noCopy: CheckpointFileEntry[] = []
    let edited = false
    for (const { file, checkpointDir } of writes) {
      if (!file.undoable) {
        noCopy.push(file)
        continue
      }
      const blob = file.action === 'created' ? null : blobPathFor(checkpointDir, file.path)
      if (noCopy.length > 0 && !goesPastNoCopy(content, blob, file)) break
      const state = writeState(content, blob, file)
      if (state === 'edited') {
        edited = true
        break
      }
      // 'restored' leaves the file as it is: it already holds this write's copy.
      if (state === 'writable') content = blob ? hashExistingFile(blob) : undefined
      taken.push(...noCopy, file)
      noCopy = []
    }
    const stopped = edited || noCopy.length > 0
    return {
      path: newest.path,
      action: taken.length > 0 ? undoneAction(taken) : newest.action,
      undoable: noCopy.length === 0,
      ...(edited ? { edited: true } : {}),
      ...(stopped && content !== now ? { partway: true } : {})
    }
  } catch {
    return null
  }
}

/**
 * The letter for what taking back `taken` (newest first) undoes: a file the
 * oldest of them created goes, one the newest deleted comes back, and any
 * other is put back as it was.
 */
function undoneAction(taken: CheckpointFileEntry[]): CheckpointFileAction {
  if (taken[taken.length - 1]!.action === 'created') return 'created'
  return taken[0]!.action === 'deleted' ? 'deleted' : 'modified'
}

/**
 * Force-restore every selected write checkpoint (newest first), each file
 * until a change made since stops it, or a write with no copy it cannot get
 * past without destroying more than older runs' own work. Selection is
 * per scope: parent runs filter by the rewind anchor, inline instance runs are
 * included whole. Ignores UI Keep/Discard and prior undone flags so
 * edit-and-resend can rewind multi-turn history.
 *
 * Checkpoints without `anchorUserMessageIndex` (legacy runs) are only restored
 * when rewinding to the start of the transcript (`fromUserMessageIndex === 0`).
 * Including them on a mid-history rewind would undo earlier-turn writes.
 *
 * All or nothing: when an undoable file cannot be restored, the files already
 * restored are put back and `undoableRestoreFailed` is set.
 */
export function rewindWritesFromScopes(
  workspaceRoot: string,
  scopes: RewindRunScope[],
  fromUserMessageIndex: number
): RewindWritesResult {
  for (const scope of scopes) discardWriteCheckpoint(scope.runDir)
  // Where the rewind leaves each file, newest first: one entry per file, as
  // in the preview, however many rewound runs changed it. Each restore takes
  // the file back a run; the first thing to stop it after that (a change made
  // since, or a write with no copy) says why it is not all the way back.
  const leftAs = new Map<string, RestoreOutcome>()
  // Files whose walk has stopped: older runs leave them as they are. Their
  // copies would go back over a change made since, unguarded when a run never
  // finalized (a crash leaves no hash). Past a write with no copy the walk
  // goes on only where that destroys nothing (goesPastNoCopy).
  const stopped = new Set<string>()

  const entries = collectRewindEntries(scopes, fromUserMessageIndex)
  // A copy that is gone would fail its restore halfway through, after newer
  // files were already put back. Check them all first and touch nothing.
  for (const entry of entries) {
    const checkpointDir = join(entry.runDir, 'checkpoints', entry.meta.id)
    for (const file of entry.meta.files) {
      if (!file.undoable || file.action === 'created') continue
      if (!existsSync(blobPathFor(checkpointDir, file.path))) {
        logger.warn('Rewind stopped before restoring: a checkpoint copy is missing', {
          scope: 'agent',
          path: file.path
        })
        return rewindFailed({ path: file.path, reason: 'its saved copy is missing' }, [])
      }
    }
  }

  // An I/O error (EPERM, EBUSY, a full disk) only shows up while writing, so
  // each restore notes what it overwrites first, a failure puts all of it back,
  // and no checkpoint is marked until every file is through.
  const undo = new RewindUndo()
  try {
    for (const entry of entries) {
      const checkpointDir = join(entry.runDir, 'checkpoints', entry.meta.id)
      for (const file of [...entry.meta.files].reverse()) {
        if (
          !stopped.has(file.path) &&
          leftAs.get(file.path) === 'skipped' &&
          !goesPastNoCopyOnDisk(workspaceRoot, checkpointDir, file)
        ) {
          stopped.add(file.path)
        }
        // Whatever the walk decides here is the rewind's, never reopened for
        // review, and an earlier Undo's copy of the agent's version is void.
        file.rewound = true
        delete file.redo
        if (stopped.has(file.path)) {
          // A newer run stopped the walk: this run's write stays under it.
          file.resolved = 'kept'
          continue
        }
        let outcome: RestoreOutcome
        try {
          outcome = restoreFile(workspaceRoot, checkpointDir, file, undo)
        } catch (err) {
          logger.warn('Rewind could not restore a file; putting back what it changed', {
            scope: 'agent',
            path: file.path,
            err
          })
          return rewindFailed({ path: file.path, reason: failureReason(err) }, undo.rollBack())
        }
        if (outcome === 'restored') {
          file.resolved = 'discarded'
        } else if (outcome === 'conflict') {
          // Changed after the agent wrote it: left as it is, by older runs
          // too. The rewind goes on with the other files.
          file.resolved = 'kept'
          stopped.add(file.path)
        }
        leftAs.set(file.path, outcome)
      }
    }
  } finally {
    undo.dispose()
  }

  // Marking is per checkpoint and follows what the walk actually did to it. A
  // checkpoint whose every write the rewind took back is undone: its copies
  // are dead weight and retention may free them. One whose file was left as
  // what was on disk — the user's own change, or a newer run's write that
  // stopped the walk — keeps its copies and stays unresolved: that write is
  // still in the file, and a later rewind over this run needs the copy. The
  // per-file outcomes are persisted either way, so the Changes list still shows
  // each file as kept or reverted (its own resolved flags drive the banner).
  for (const entry of entries) {
    if (entry.meta.files.every((file) => !file.undoable || file.resolved === 'discarded')) {
      markCheckpointFullyResolved(entry.runDir, entry.meta)
      continue
    }
    try {
      saveMeta(entry.runDir, entry.meta)
    } catch (err) {
      logger.warn('Failed to record how a rewind left a checkpoint', {
        scope: 'agent',
        correlationId: basename(entry.runDir),
        checkpointId: entry.meta.id,
        err
      })
    }
  }
  const leftAsOf = (outcome: RestoreOutcome): string[] =>
    [...leftAs].filter(([, left]) => left === outcome).map(([path]) => path)
  return {
    checkpointIds: entries.map((entry) => entry.meta.id),
    restored: leftAsOf('restored'),
    skipped: leftAsOf('skipped'),
    edited: leftAsOf('conflict'),
    undoableRestoreFailed: false
  }
}

function rewindFailed(failure: { path: string; reason: string }, notPutBack: string[]): RewindWritesResult {
  return {
    checkpointIds: [],
    restored: [],
    skipped: [],
    edited: [],
    undoableRestoreFailed: true,
    failure,
    ...(notPutBack.length > 0 ? { notPutBack } : {})
  }
}

/** A short why for the user: the error code when there is one. */
function failureReason(err: unknown): string {
  const code = (err as NodeJS.ErrnoException | null)?.code
  if (typeof code === 'string' && code) return code
  return err instanceof Error ? err.message : String(err)
}

/** Single-run rewind (parent scope) — see rewindWritesFromScopes. */
export function rewindWritesFrom(
  runDir: string,
  workspaceRoot: string,
  fromUserMessageIndex: number
): RewindWritesResult {
  return rewindWritesFromScopes(
    workspaceRoot,
    [{ runDir, selection: 'anchored' }],
    fromUserMessageIndex
  )
}

/** Single-run preview (parent scope) — see planRewindWritesAcrossRuns. */
export function planRewindWrites(runDir: string, fromUserMessageIndex: number): RewindWritesPlan {
  return planRewindWritesAcrossRuns([{ runDir, selection: 'anchored' }], fromUserMessageIndex)
}

/** Test helper: clear all active sessions. */
export function resetWriteCheckpointsForTests(): void {
  activeSessions.clear()
}
