import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  realpathSync,
  rmSync,
  statSync
} from 'fs'
import { copyFile, mkdir, readdir, stat } from 'fs/promises'
import { basename, dirname, join, relative } from 'path'
import { createHash, randomUUID } from 'crypto'
import { realpathIfExists, resolveInsideWorkspace } from '../workspace/safePath'
import { atomicWriteFile, atomicWriteJson } from '@main/storage/atomicWrite'
import { logger } from '../../shared/logger'
import { isPlausibleWorkspaceFilePath } from './loopPolicy'

export type CheckpointFileAction = 'created' | 'modified' | 'deleted'

export type CheckpointFileResolution = 'kept' | 'discarded'

export type CheckpointFileEntry = {
  /** Workspace-relative path using forward slashes. */
  path: string
  action: CheckpointFileAction
  /** False for recursive directory deletes (v1 cannot restore). */
  undoable: boolean
  /**
   * SHA-256 of workspace content after the write (created/modified).
   * Restore skips when current content differs (user edit after the agent).
   */
  hash?: string
  /** Set when the user Keep/Discard resolves this path. */
  resolved?: CheckpointFileResolution
  /** Revert was refused because the file was edited after the agent wrote it. */
  conflicted?: boolean
}

export type WriteCheckpointMeta = {
  id: string
  createdAt: string
  undone?: boolean
  /** True when every file is Keep/Discard resolved (or discarded via Undo). */
  resolved?: boolean
  /**
   * Index of the user message this invoke was answering (messages already include
   * that user turn when the checkpoint session starts). Used by edit-and-rewind.
   */
  anchorUserMessageIndex?: number
  files: CheckpointFileEntry[]
}

export type CheckpointIndex = {
  checkpoints: Array<{ id: string; createdAt: string; undone?: boolean }>
}

const activeSessions = new Map<string, InvokeWriteCheckpoint>()

/** Checkpoint IDs are UUIDs generated by this module; never trust external input. */
const CHECKPOINT_ID_RE = /^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/

function assertValidCheckpointId(id: string): void {
  if (!CHECKPOINT_ID_RE.test(id)) {
    throw new Error(`Invalid checkpoint id: ${id.slice(0, 64)}`)
  }
}

function normalizeRelPath(rel: string): string {
  return rel.replace(/\\/g, '/')
}

function toCheckpointRelPath(workspaceRoot: string, pathArg: string): string {
  try {
    const resolved = resolveInsideWorkspace(workspaceRoot, pathArg)
    const rel = normalizeRelPath(relative(realpathIfExists(workspaceRoot), resolved))
    if (rel && !rel.startsWith('..')) return rel
  } catch {
    /* fall through to slash-normalize */
  }
  return normalizeRelPath(pathArg)
}

function hashExistingFile(path: string): string | undefined {
  if (!existsSync(path)) return undefined
  try {
    const st = statSync(path)
    if (!st.isFile()) return undefined
    return createHash('sha256').update(readFileSync(path)).digest('hex')
  } catch {
    return undefined
  }
}

function blobPathFor(checkpointDir: string, relPath: string): string {
  const parts = normalizeRelPath(relPath).split('/').filter(Boolean)
  if (parts.some((p) => p === '..')) {
    throw new Error('Invalid checkpoint path')
  }
  return join(checkpointDir, 'files', ...parts)
}

function loadIndex(runDir: string): CheckpointIndex {
  const p = join(runDir, 'checkpoints', 'index.json')
  if (!existsSync(p)) return { checkpoints: [] }
  try {
    const raw = JSON.parse(readFileSync(p, 'utf8')) as CheckpointIndex
    const checkpoints = (Array.isArray(raw.checkpoints) ? raw.checkpoints : []).filter(
      (c): c is { id: string; createdAt: string; undone?: boolean } =>
        c != null && typeof c === 'object' && typeof (c as { id?: unknown }).id === 'string' &&
        CHECKPOINT_ID_RE.test((c as { id: string }).id)
    )
    return { checkpoints }
  } catch {
    return { checkpoints: [] }
  }
}

function saveIndex(runDir: string, index: CheckpointIndex): void {
  const dir = join(runDir, 'checkpoints')
  mkdirSync(dir, { recursive: true })
  atomicWriteJson(join(dir, 'index.json'), index)
}

function loadMeta(runDir: string, id: string): WriteCheckpointMeta | null {
  assertValidCheckpointId(id)
  const p = join(runDir, 'checkpoints', id, 'meta.json')
  if (!existsSync(p)) return null
  try {
    return JSON.parse(readFileSync(p, 'utf8')) as WriteCheckpointMeta
  } catch {
    return null
  }
}

/** Read checkpoint meta for IPC persistence / hydration. */
export function getWriteCheckpointMeta(
  runDir: string,
  checkpointId: string
): WriteCheckpointMeta | null {
  // Soft no-op resolveWrites may pass ''; avoid assert throw → IPC_HANDLER.
  if (!checkpointId.trim() || !CHECKPOINT_ID_RE.test(checkpointId)) return null
  return loadMeta(runDir, checkpointId)
}

function saveMeta(runDir: string, meta: WriteCheckpointMeta): void {
  assertValidCheckpointId(meta.id)
  const dir = join(runDir, 'checkpoints', meta.id)
  mkdirSync(dir, { recursive: true })
  atomicWriteJson(join(dir, 'meta.json'), meta)
}

/** One turn (invoke) of agent writes; first prior per path wins. */
export class InvokeWriteCheckpoint {
  readonly id: string
  readonly createdAt: string
  readonly anchorUserMessageIndex: number | undefined
  private readonly runDir: string
  private readonly workspaceRoot: string
  private readonly files = new Map<string, CheckpointFileEntry>()
  /** Rel-paths with an in-flight async snapshot so first-path-wins stays racy-safe. */
  private readonly pendingRels = new Set<string>()
  private finalized = false

  constructor(
    runDir: string,
    workspaceRoot: string,
    anchorUserMessageIndex?: number
  ) {
    this.id = randomUUID()
    this.createdAt = new Date().toISOString()
    this.runDir = runDir
    this.workspaceRoot = workspaceRoot
    this.anchorUserMessageIndex = anchorUserMessageIndex
  }

  private realWorkspaceRoot(): string {
    return existsSync(this.workspaceRoot) ? realpathSync(this.workspaceRoot) : this.workspaceRoot
  }

  private relPathFromResolved(resolved: string): string {
    return normalizeRelPath(relative(this.realWorkspaceRoot(), resolved))
  }

  private checkpointDir(): string {
    return join(this.runDir, 'checkpoints', this.id)
  }

  /**
   * Snapshot prior content before a write or delete.
   * Async blob copy so the Electron main/UI thread is not blocked on disk I/O.
   * @param pathArg Path as the tool received it (workspace-relative or absolute inside root).
   */
  async recordPrior(
    pathArg: string,
    kind: 'write' | 'delete',
    opts?: { recursiveDir?: boolean }
  ): Promise<void> {
    if (this.finalized) return
    const resolved = resolveInsideWorkspace(this.workspaceRoot, pathArg)
    const rel = this.relPathFromResolved(resolved)
    if (!rel || rel.startsWith('..')) return
    // Recursive dir deletes are recorded as bare directory names (no extension).
    // Plausible-file checks reject those; still allow the checkpoint entry.
    if (!opts?.recursiveDir && !isPlausibleWorkspaceFilePath(rel)) return
    if (this.files.has(rel) || this.pendingRels.has(rel)) return
    this.pendingRels.add(rel)
    const filesBefore = this.files.size
    try {
      await this.snapshotPrior(resolved, rel, kind, opts)
    } finally {
      this.pendingRels.delete(rel)
      if (this.files.size > filesBefore) this.persistIncremental()
    }
  }

  private async snapshotPrior(
    resolved: string,
    rel: string,
    kind: 'write' | 'delete',
    opts?: { recursiveDir?: boolean }
  ): Promise<void> {
    let st: Awaited<ReturnType<typeof stat>> | null = null
    try {
      st = await stat(resolved)
    } catch {
      st = null
    }
    if (kind === 'write') {
      if (!st) {
        this.files.set(rel, { path: rel, action: 'created', undoable: true })
        return
      }
      if (st.isDirectory()) {
        // Writing through edit tools targets files; ignore dirs.
        return
      }
      const dest = blobPathFor(this.checkpointDir(), rel)
      await mkdir(dirname(dest), { recursive: true })
      await copyFile(resolved, dest)
      this.files.set(rel, { path: rel, action: 'modified', undoable: true })
      return
    }

    // delete
    if (!st) return
    if (st.isDirectory()) {
      // Snapshot the directory tree so the delete is undoable. Each file becomes
      // its own 'deleted' checkpoint entry; restoring them recreates the original
      // tree (v1 could not restore directories — now fixed).
      const maxDirRestoreFiles = 20000
      let fileCount = 0
      let overflow = false
      const snapshotTree = async (absDir: string): Promise<void> => {
        if (overflow) return
        let entries
        try {
          entries = await readdir(absDir, { withFileTypes: true })
        } catch {
          return
        }
        for (const entry of entries) {
          const abs = join(absDir, entry.name)
          if (entry.isDirectory()) {
            // entry.isDirectory() is false for symlinks, so symlink dirs are not followed.
            await snapshotTree(abs)
            if (overflow) return
            continue
          }
          if (!entry.isFile()) continue // skip symlinks / sockets / devices
          if (fileCount >= maxDirRestoreFiles) {
            overflow = true
            return
          }
          fileCount++
          const childRel = this.relPathFromResolved(abs)
          if (!childRel || childRel.startsWith('..')) continue
          const dest = blobPathFor(this.checkpointDir(), childRel)
          try {
            await mkdir(dirname(dest), { recursive: true })
            await copyFile(abs, dest)
          } catch {
            continue
          }
          this.files.set(childRel, { path: childRel, action: 'deleted', undoable: true })
        }
      }
      await snapshotTree(resolved)
      if (overflow) {
        logger.warn('Directory delete too large to snapshot for undo; marked non-undoable', {
          scope: 'agent',
          path: rel
        })
        this.files.set(rel, { path: rel, action: 'deleted', undoable: false })
      } else if (fileCount === 0) {
        // Empty directory: nothing to restore, but keep the entry for UI parity.
        this.files.set(rel, { path: rel, action: 'deleted', undoable: false })
      }
      return
    }
    const dest = blobPathFor(this.checkpointDir(), rel)
    await mkdir(dirname(dest), { recursive: true })
    await copyFile(resolved, dest)
    this.files.set(rel, { path: rel, action: 'deleted', undoable: true })
  }

  /**
   * Record a mutation observed after a tool ran (e.g. opaque terminal redirect).
   * First path wins — does not overwrite recordPrior entries.
   */
  async recordObservedMutation(
    pathArg: string,
    kind: 'created' | 'modified' | 'deleted',
    priorBlobPath?: string
  ): Promise<void> {
    if (this.finalized) return
    const resolved = resolveInsideWorkspace(this.workspaceRoot, pathArg)
    const rel = this.relPathFromResolved(resolved)
    if (!rel || rel.startsWith('..')) return
    if (!isPlausibleWorkspaceFilePath(rel)) return
    if (this.files.has(rel) || this.pendingRels.has(rel)) return
    this.pendingRels.add(rel)
    const filesBefore = this.files.size
    try {
      if (kind === 'created') {
        this.files.set(rel, { path: rel, action: 'created', undoable: true })
        return
      }

      let blobExists = false
      if (priorBlobPath) {
        try {
          await stat(priorBlobPath)
          blobExists = true
        } catch {
          blobExists = false
        }
      }
      if (!priorBlobPath || !blobExists) {
        this.files.set(rel, {
          path: rel,
          action: kind === 'modified' ? 'modified' : 'deleted',
          undoable: false
        })
        return
      }

      const dest = blobPathFor(this.checkpointDir(), rel)
      await mkdir(dirname(dest), { recursive: true })
      await copyFile(priorBlobPath, dest)
      this.files.set(rel, {
        path: rel,
        action: kind === 'modified' ? 'modified' : 'deleted',
        undoable: true
      })
    } finally {
      this.pendingRels.delete(rel)
      if (this.files.size > filesBefore) this.persistIncremental()
    }
  }

  private stampPostWriteHashes(): void {
    for (const file of this.files.values()) {
      if (!file.undoable || file.action === 'deleted') continue
      try {
        const resolved = resolveInsideWorkspace(this.workspaceRoot, file.path)
        const hash = hashExistingFile(resolved)
        if (hash) file.hash = hash
      } catch {
        // Leave unhashed; restore falls back to unguarded copy/delete.
      }
    }
  }

  /**
   * Persist the in-progress checkpoint (meta + index entry) so a crash or power
   * loss mid-turn cannot erase the turn's undo data. Post-write hashes are only
   * stamped by finalize(); the incremental meta restores the pre-crash content
   * without user-edit conflict detection, which is the best available outcome
   * after an unorderly death.
   */
  private persistIncremental(): void {
    if (this.finalized) return
    if (this.files.size === 0) return
    const meta: WriteCheckpointMeta = {
      id: this.id,
      createdAt: this.createdAt,
      ...(this.anchorUserMessageIndex !== undefined
        ? { anchorUserMessageIndex: this.anchorUserMessageIndex }
        : {}),
      files: [...this.files.values()]
    }
    try {
      saveMeta(this.runDir, meta)
      const index = loadIndex(this.runDir)
      if (!index.checkpoints.some((c) => c.id === this.id)) {
        index.checkpoints.push({ id: meta.id, createdAt: meta.createdAt })
        saveIndex(this.runDir, index)
      }
    } catch (err) {
      logger.warn('Failed to persist incremental write checkpoint', {
        scope: 'agent',
        correlationId: basename(this.runDir),
        checkpointId: this.id,
        err
      })
    }
  }

  /** Persist if any files were recorded; returns meta or null. */
  finalize(): WriteCheckpointMeta | null {
    if (this.finalized) return null
    this.finalized = true
    if (this.files.size === 0) return null
    this.stampPostWriteHashes()

    const meta: WriteCheckpointMeta = {
      id: this.id,
      createdAt: this.createdAt,
      ...(this.anchorUserMessageIndex !== undefined
        ? { anchorUserMessageIndex: this.anchorUserMessageIndex }
        : {}),
      files: [...this.files.values()]
    }
    saveMeta(this.runDir, meta)
    const index = loadIndex(this.runDir)
    // Incremental persistence may already have registered this id mid-turn.
    if (!index.checkpoints.some((c) => c.id === meta.id)) {
      index.checkpoints.push({
        id: meta.id,
        createdAt: meta.createdAt
      })
      saveIndex(this.runDir, index)
    }
    return meta
  }
}

export function beginWriteCheckpoint(
  runDir: string,
  workspaceRoot: string,
  anchorUserMessageIndex?: number
): InvokeWriteCheckpoint {
  const existing = activeSessions.get(runDir)
  if (existing) return existing
  const session = new InvokeWriteCheckpoint(runDir, workspaceRoot, anchorUserMessageIndex)
  activeSessions.set(runDir, session)
  return session
}

export function getWriteCheckpoint(runDir: string | undefined): InvokeWriteCheckpoint | undefined {
  if (!runDir) return undefined
  return activeSessions.get(runDir)
}

export function finalizeWriteCheckpoint(runDir: string): WriteCheckpointMeta | null {
  const session = activeSessions.get(runDir)
  activeSessions.delete(runDir)
  if (!session) return null
  return session.finalize()
}

/** Drop an open session without persisting (e.g. tests). */
export function discardWriteCheckpoint(runDir: string): void {
  activeSessions.delete(runDir)
}

export type ResolveWritesResult = {
  checkpointId: string
  kept: string[]
  discarded: string[]
  skipped: string[]
  /**
   * Paths whose revert was refused because the file was edited by the user after
   * the agent wrote it (content no longer matches). These stay unresolved so the
   * UI can surface "can't auto-revert" instead of falsely marking them reverted.
   */
  conflicted: string[]
  fullyResolved: boolean
}

function resolveCheckpointId(runDir: string, checkpointId?: string): string | null {
  if (checkpointId) assertValidCheckpointId(checkpointId)
  const index = loadIndex(runDir)
  let id = checkpointId
  if (!id) {
    for (let i = index.checkpoints.length - 1; i >= 0; i--) {
      const entry = index.checkpoints[i]!
      const meta = loadMeta(runDir, entry.id)
      if (meta && !meta.undone && !meta.resolved) {
        id = entry.id
        break
      }
    }
  }
  if (!id) return null
  assertValidCheckpointId(id)
  return id
}

function restoreOneFile(
  workspaceRoot: string,
  checkpointDir: string,
  file: CheckpointFileEntry
): 'restored' | 'skipped' | 'conflict' | 'failed' {
  if (!file.undoable) return 'skipped'
  const resolved = resolveInsideWorkspace(workspaceRoot, file.path)
  try {
    if (file.action === 'created') {
      if (file.hash) {
        const current = hashExistingFile(resolved)
        if (current && current !== file.hash) {
          // User edited the file the agent created — refuse to delete their work.
          logger.warn('Skipping checkpoint restore; file changed after the agent write', {
            scope: 'agent',
            path: file.path
          })
          return 'conflict'
        }
      }
      if (existsSync(resolved)) {
        rmSync(resolved, { force: true })
      }
      return 'restored'
    }
    const blob = blobPathFor(checkpointDir, file.path)
    if (!existsSync(blob)) return 'failed'

    if (file.action === 'modified' && file.hash) {
      const current = hashExistingFile(resolved)
      if (current) {
        if (current !== file.hash) {
          const priorHash = hashExistingFile(blob)
          if (current === priorHash) return 'restored'
          // User edited the file after the agent modified it — refuse to clobber.
          logger.warn('Skipping checkpoint restore; file changed after the agent write', {
            scope: 'agent',
            path: file.path
          })
          return 'conflict'
        }
        // current === file.hash: user has not changed the file; fall through to
        // restore the prior blob at the bottom of this function.
      }
      // current is undefined: the agent-modified file was deleted after the write.
      // Fall through so the prior blob is restored, recreating the original file
      // instead of silently leaving the deletion in place.
    }

    if (file.action === 'deleted') {
      const current = hashExistingFile(resolved)
      if (current) {
        const priorHash = hashExistingFile(blob)
        if (current !== priorHash) {
          logger.warn('Skipping checkpoint restore; file changed after the agent write', {
            scope: 'agent',
            path: file.path
          })
          return 'skipped'
        }
        return 'restored'
      }
    }

    mkdirSync(dirname(resolved), { recursive: true })
    copyFileSync(blob, resolved)
    return 'restored'
  } catch (err) {
    logger.warn('Failed to restore checkpoint file', {
      scope: 'agent',
      path: file.path,
      err
    })
    return 'failed'
  }
}

function markCheckpointFullyResolved(runDir: string, meta: WriteCheckpointMeta): void {
  const idx = loadIndex(runDir)
  const entry = idx.checkpoints.find((c) => c.id === meta.id)
  if (entry) entry.undone = true
  saveIndex(runDir, idx)
  meta.resolved = true
  meta.undone = true
  saveMeta(runDir, meta)
}

/**
 * Keep and/or discard specific paths (or all unresolved when paths omitted for discard/keep all).
 *
 * Resolution is scoped to `checkpointId` when provided. When `checkpointId` is
 * omitted but `paths` are given, each path is resolved within the newest
 * unresolved checkpoint that recorded it — so a user can Keep/Discard a file
 * from any turn, not just the latest one. When both are omitted the latest
 * unresolved checkpoint is fully resolved (Undo / Keep-all / Discard-all).
 */
export function resolveWrites(
  runDir: string,
  workspaceRoot: string,
  opts: {
    checkpointId?: string
    action: 'keep' | 'discard'
    /** When omitted, applies to all unresolved files. */
    paths?: string[]
  }
): ResolveWritesResult {
  if (opts.checkpointId) {
    return resolveWritesInCheckpoint(runDir, workspaceRoot, opts.checkpointId, opts.action, opts.paths ?? null)
  }

  if (opts.paths && opts.paths.length > 0) {
    const index = loadIndex(runDir)
    const byCheckpoint = new Map<string, string[]>()
    for (const p of opts.paths) {
      const rel = toCheckpointRelPath(workspaceRoot, p)
      const cpId = findNewestUnresolvedCheckpointForPath(runDir, index, rel)
      if (!cpId) continue
      const arr = byCheckpoint.get(cpId) ?? []
      arr.push(rel)
      byCheckpoint.set(cpId, arr)
    }
    if (byCheckpoint.size === 0) {
      // Soft no-op: none of the paths are part of an actionable checkpoint.
      return {
        checkpointId: '',
        kept: [],
        discarded: [],
        skipped: [...opts.paths],
        conflicted: [],
        fullyResolved: true
      }
    }
    const kept: string[] = []
    const discarded: string[] = []
    const skipped: string[] = []
    const conflicted: string[] = []
    let allFullyResolved = true
    for (const [cpId, rels] of byCheckpoint) {
      const r = resolveWritesInCheckpoint(runDir, workspaceRoot, cpId, opts.action, rels)
      kept.push(...r.kept)
      discarded.push(...r.discarded)
      skipped.push(...r.skipped)
      conflicted.push(...r.conflicted)
      if (!r.fullyResolved) allFullyResolved = false
    }
    return {
      checkpointId: '',
      kept,
      discarded,
      skipped,
      conflicted,
      fullyResolved: allFullyResolved
    }
  }

  const id = resolveCheckpointId(runDir, undefined)
  if (!id) {
    // Soft no-op: UI may call Keep/Discard after the banner cleared or with no writes.
    return {
      checkpointId: '',
      kept: [],
      discarded: [],
      skipped: [],
      conflicted: [],
      fullyResolved: true
    }
  }
  return resolveWritesInCheckpoint(runDir, workspaceRoot, id, opts.action, null)
}

/** Newest unresolved checkpoint that still has an unresolved entry for `relPath`. */
function findNewestUnresolvedCheckpointForPath(
  runDir: string,
  index: CheckpointIndex,
  relPath: string
): string | null {
  for (let i = index.checkpoints.length - 1; i >= 0; i--) {
    const entry = index.checkpoints[i]!
    const meta = loadMeta(runDir, entry.id)
    if (!meta || meta.undone || meta.resolved) continue
    if (meta.files.some((f) => f.path === relPath && !f.resolved)) return meta.id
  }
  return null
}

function resolveWritesInCheckpoint(
  runDir: string,
  workspaceRoot: string,
  checkpointId: string,
  action: 'keep' | 'discard',
  paths: string[] | null
): ResolveWritesResult {
  const meta = loadMeta(runDir, checkpointId)
  if (!meta) throw new Error(`Checkpoint not found: ${checkpointId}`)
  if (meta.undone || meta.resolved) throw new Error('That checkpoint was already resolved')

  const targetPaths =
    paths && paths.length > 0
      ? new Set(paths.map((p) => toCheckpointRelPath(workspaceRoot, p)))
      : null

  const checkpointDir = join(runDir, 'checkpoints', checkpointId)
  const kept: string[] = []
  const discarded: string[] = []
  const skipped: string[] = []
  const conflicted: string[] = []

  for (const file of meta.files) {
    if (targetPaths && !targetPaths.has(file.path)) continue
    if (file.resolved) {
      skipped.push(file.path)
      continue
    }
    if (action === 'keep') {
      file.resolved = 'kept'
      kept.push(file.path)
      continue
    }
    const outcome = restoreOneFile(workspaceRoot, checkpointDir, file)
    if (outcome === 'restored') {
      file.resolved = 'discarded'
      discarded.push(file.path)
    } else if (outcome === 'conflict') {
      // User edited the file after the agent wrote it; leave it unresolved and
      // surface it so the UI can explain why it cannot be auto-reverted.
      file.conflicted = true
      conflicted.push(file.path)
    } else if (outcome === 'failed') {
      // Undoable file whose restore failed (missing prior blob / I/O error):
      // keep it unresolved so the user can retry instead of falsely marking it
      // as reverted.
      skipped.push(file.path)
    } else {
      // Non-undoable: still mark discarded so the UI can clear it.
      file.resolved = 'discarded'
      skipped.push(file.path)
    }
  }

  // When every undoable file is handled, stamp leftover non-undoable as kept so
  // disk meta.resolved matches the UI fullyResolved banner clear.
  const undoablesDone = meta.files.every((f) => Boolean(f.resolved) || !f.undoable)
  if (undoablesDone) {
    for (const file of meta.files) {
      if (!file.resolved && !file.undoable) file.resolved = 'kept'
    }
  }
  const allHandled = meta.files.every((f) => Boolean(f.resolved))
  if (allHandled) {
    markCheckpointFullyResolved(runDir, meta)
  } else {
    saveMeta(runDir, meta)
  }

  return {
    checkpointId,
    kept,
    discarded,
    skipped,
    conflicted,
    fullyResolved: allHandled
  }
}

export type RewindWritesResult = {
  checkpointIds: string[]
  restored: string[]
  skipped: string[]
  /** True when an undoable file could not be restored (I/O or hash conflict). */
  undoableRestoreFailed: boolean
}

export type RewindWritesPlanFile = {
  path: string
  action: CheckpointFileAction
  undoable: boolean
}

export type RewindWritesPlan = {
  checkpointIds: string[]
  files: RewindWritesPlanFile[]
}

/**
 * Selection rule for a rewind to `fromUserMessageIndex`, shared by the preview
 * (planRewindWrites) and execution (rewindWritesFrom) so they can never diverge.
 * Checkpoints without `anchorUserMessageIndex` (legacy runs) are only rewound
 * when rewinding to the start of the transcript (`fromUserMessageIndex === 0`).
 */
function isRewoundCheckpoint(meta: WriteCheckpointMeta, fromUserMessageIndex: number): boolean {
  const anchor = meta.anchorUserMessageIndex
  if (anchor !== undefined) return anchor >= fromUserMessageIndex
  return fromUserMessageIndex === 0
}

/** Per-run checkpoint selection for a rewind that spans multiple runs. */
export type RewindRunScope = {
  runDir: string
  /**
   * 'anchored' keeps the parent-run rule (isRewoundCheckpoint against the
   * rewind point); 'all' restores every checkpoint in the run — used for
   * inline instance runs whose entire recorded work is being undone.
   */
  selection: 'anchored' | 'all'
}

type RewindEntry = {
  runDir: string
  meta: WriteCheckpointMeta
  createdAtMs: number
  scopeSeq: number
  indexPos: number
}

function collectRewindEntries(
  scopes: RewindRunScope[],
  fromUserMessageIndex: number
): RewindEntry[] {
  const entries: RewindEntry[] = []
  for (let scopeSeq = 0; scopeSeq < scopes.length; scopeSeq++) {
    const scope = scopes[scopeSeq]!
    const index = loadIndex(scope.runDir)
    for (let indexPos = index.checkpoints.length - 1; indexPos >= 0; indexPos--) {
      const entry = index.checkpoints[indexPos]!
      const meta = loadMeta(scope.runDir, entry.id)
      if (!meta) continue
      if (scope.selection === 'anchored' && !isRewoundCheckpoint(meta, fromUserMessageIndex)) {
        continue
      }
      const ts = Date.parse(meta.createdAt)
      entries.push({
        runDir: scope.runDir,
        meta,
        createdAtMs: Number.isFinite(ts) ? ts : 0,
        scopeSeq,
        indexPos
      })
    }
  }
  // Restore the newest action first: each restore's post-write hash guard
  // expects exactly the content produced by the next-newer undone write, so
  // strict reverse-chronological order keeps the guard chain verifiable even
  // when a parent run and its inline instances touched the same files.
  entries.sort(
    (a, b) => b.createdAtMs - a.createdAtMs || a.scopeSeq - b.scopeSeq || b.indexPos - a.indexPos
  )
  return entries
}

/** Read-only preview of what rewindWritesFromScopes would restore; mutates nothing. */
export function planRewindWritesAcrossRuns(
  scopes: RewindRunScope[],
  fromUserMessageIndex: number
): RewindWritesPlan {
  const checkpointIds: string[] = []
  const byPath = new Map<string, RewindWritesPlanFile>()
  for (const entry of collectRewindEntries(scopes, fromUserMessageIndex)) {
    checkpointIds.push(entry.meta.id)
    for (const file of entry.meta.files) {
      // Newest checkpoint wins per path; older checkpoints never overwrite it.
      if (!byPath.has(file.path)) {
        byPath.set(file.path, {
          path: file.path,
          action: file.action,
          undoable: file.undoable
        })
      }
    }
  }
  return {
    checkpointIds,
    files: [...byPath.values()].sort((a, b) => a.path.localeCompare(b.path))
  }
}

/**
 * Force-restore every selected write checkpoint (newest first). Selection is
 * per scope: parent runs filter by the rewind anchor, inline instance runs are
 * included whole. Ignores UI Keep/Discard and prior undone flags so
 * edit-and-resend can rewind multi-turn history.
 *
 * Checkpoints without `anchorUserMessageIndex` (legacy runs) are only restored
 * when rewinding to the start of the transcript (`fromUserMessageIndex === 0`).
 * Including them on a mid-history rewind would undo earlier-turn writes.
 */
export function rewindWritesFromScopes(
  workspaceRoot: string,
  scopes: RewindRunScope[],
  fromUserMessageIndex: number
): RewindWritesResult {
  for (const scope of scopes) discardWriteCheckpoint(scope.runDir)
  const checkpointIds: string[] = []
  const restored: string[] = []
  const skipped: string[] = []
  let undoableRestoreFailed = false

  for (const entry of collectRewindEntries(scopes, fromUserMessageIndex)) {
    const checkpointDir = join(entry.runDir, 'checkpoints', entry.meta.id)
    let hadIoFailure = false
    for (const file of [...entry.meta.files].reverse()) {
      const outcome = restoreOneFile(workspaceRoot, checkpointDir, file)
      if (outcome === 'restored') {
        file.resolved = 'discarded'
        restored.push(file.path)
      } else if (file.undoable) {
        hadIoFailure = true
        skipped.push(file.path)
      } else {
        skipped.push(file.path)
      }
    }
    if (hadIoFailure) {
      undoableRestoreFailed = true
      saveMeta(entry.runDir, entry.meta)
    } else {
      markCheckpointFullyResolved(entry.runDir, entry.meta)
    }
    checkpointIds.push(entry.meta.id)
  }

  return { checkpointIds, restored, skipped, undoableRestoreFailed }
}

/** Single-run rewind (parent scope) — see rewindWritesFromScopes. */
export function rewindWritesFrom(
  runDir: string,
  workspaceRoot: string,
  fromUserMessageIndex: number
): RewindWritesResult {
  return rewindWritesFromScopes(
    workspaceRoot,
    [{ runDir, selection: 'anchored' }],
    fromUserMessageIndex
  )
}

/** Single-run preview (parent scope) — see planRewindWritesAcrossRuns. */
export function planRewindWrites(runDir: string, fromUserMessageIndex: number): RewindWritesPlan {
  return planRewindWritesAcrossRuns([{ runDir, selection: 'anchored' }], fromUserMessageIndex)
}

/** Test helper: clear all active sessions. */
export function resetWriteCheckpointsForTests(): void {
  activeSessions.clear()
}
