/**
 * Copies the real brand kit and the marketplace package icons into the site.
 *
 * The identity in resources/branding/precision-mono is generated by
 * scripts/generate-precision-mono-brand.mjs (run on postinstall), and
 * resources/branding/** is excluded from the packaged app, so it is repo-only
 * material that the website is the natural consumer of. Copying it here keeps
 * one source of truth instead of a second, drifting set of logo files.
 */
import { copyFileSync, mkdirSync, rmSync, existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const landing = join(here, '..')
const repo = join(landing, '..')

const brandSrc = join(repo, 'resources/branding/precision-mono')
const brandOut = join(landing, 'public/brand')
const iconSrc = join(repo, 'resources/marketplace/icons')
const iconOut = join(landing, 'public/brand/extensions')

const REQUIRED = [
  'vyotiq-lockup-black.svg',
  'vyotiq-lockup-white.svg',
  'vyotiq-mark-black.svg',
  'vyotiq-mark-white.svg',
  'vyotiq-app-icon.svg',
  'vyotiq-app-icon.png',
  'vyotiq-social-card.png'
]

if (!existsSync(brandSrc)) {
  console.error(`[bake-brand] brand kit missing at ${brandSrc} — run \`pnpm sync:brand\` at the repo root`)
  process.exit(1)
}

rmSync(brandOut, { recursive: true, force: true })
mkdirSync(iconOut, { recursive: true })

for (const file of REQUIRED) {
  const from = join(brandSrc, file)
  if (!existsSync(from)) {
    console.error(`[bake-brand] required brand asset missing: ${file}`)
    process.exit(1)
  }
  copyFileSync(from, join(brandOut, file))
}

// The favicon is the mark on its own, recoloured to the accent so it reads at
// 16px in both a light and a dark browser tab strip.
const mark = readFileSync(join(brandSrc, 'vyotiq-mark-black.svg'), 'utf8')
writeFileSync(join(brandOut, 'favicon.svg'), mark.replaceAll('#000000', 'currentColor'), 'utf8')

// Marketplace icons are third-party brand marks shipped with the app for its
// own extension list. Only the ones the catalog actually references are copied.
const catalog = JSON.parse(readFileSync(join(repo, 'resources/marketplace/catalog.json'), 'utf8'))
const referenced = new Set(
  catalog.packages.map((p) => p.iconPath).filter(Boolean).map((p) => p.replace(/^icons\//, ''))
)

let copied = 0
for (const file of readdirSync(iconSrc)) {
  if (!referenced.has(file)) continue
  copyFileSync(join(iconSrc, file), join(iconOut, file))
  copied++
}

console.log(`[bake-brand] ${REQUIRED.length} brand assets + favicon · ${copied} extension icons`)
