/**
 * GENERATED by scripts/generate-precision-mono-brand.mjs — do not edit.
 * Run `pnpm sync:brand` after changing the mark's geometry.
 *
 * The same four faces the SVG kit ships, for the places that must draw the
 * mark inline to follow currentColor.
 */

/** Cropped to the hexagon, so `width=N height=N` renders N of real ink. */
export const VYOTIQ_MARK_VIEW_BOX = '112 112 800 800'

export const VYOTIQ_MARK_PATHS = [
  'M 794.908 512.000 L 370.546 757.005 L 370.546 266.995 Z',
  'M 858.410 540.000 L 858.410 712.000 L 512.000 912.000 L 363.044 826.000 Z',
  'M 314.546 798.000 L 165.590 712.000 L 165.590 312.000 L 314.546 226.000 Z',
  'M 363.044 198.000 L 512.000 112.000 L 858.410 312.000 L 858.410 484.000 Z'
] as const
