#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

banner "Vyotiq release secrets"

# Preflight: set_secret runs `gh secret set` with no --repo, so a secret lands
# in whatever repo this directory resolves to. Check before anything is written.
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  current_repo=$(gh repo view --json nameWithOwner --jq .nameWithOwner 2>/dev/null || true)
  if [[ "$current_repo" == "vyotiqai/vyotiq-agent-v" ]]; then
    note "Writing secrets to ${current_repo}."
  elif [[ -z "$current_repo" ]]; then
    warn "Could not determine the current repository. set_secret writes to whatever repo this directory resolves to — check it is vyotiqai/vyotiq-agent-v before continuing, or use the gh secret set … --repo commands printed in each stage."
  else
    warn "This directory resolves to ${current_repo}, NOT vyotiqai/vyotiq-agent-v — every secret below would be written to the wrong repository. Stop here, or use the gh secret set … --repo commands printed in each stage."
  fi
fi

# ── 1: Sentry DSN → .env ──────────────────────────────────────────────────
stage "Sentry DSN → .env"
say "Crash reporting only ships if a Sentry DSN is baked into the build, and .env is the local copy."
open_url "https://sentry.io"
step "Sign in → your org → the project for this app → Settings → Client Keys (DSN)."
note "Portal labels move; the value is what matters, not the label. If the label has moved, ask Sentry where the DSN key lives now."
step "Copy the DSN — it looks like https://<key>@<org>.ingest.sentry.io/<project>."
ask SENTRY_DSN "Paste the DSN:"
write_env SENTRY_DSN "$SENTRY_DSN"
write_env VITE_SENTRY_DSN "$SENTRY_DSN"   # same value; the renderer build reads the VITE_ name
note "A blank DSN is a supported local-dev state (see .env.example)."

# ── 2: Sentry DSN → GitHub secret ─────────────────────────────────────────
stage "Sentry DSN → GitHub secret"
say "The release build inlines the DSN from a GitHub secret so a packaged app reports crashes; without it the release ships with crash reporting off."
open_url "https://github.com/vyotiqai/vyotiq-agent-v/settings/secrets/actions"
step "Confirm you are on vyotiqai/vyotiq-agent-v, the private SOURCE repo — installers live on a separate releases repo and are already covered by RELEASES_TOKEN."
ask_secret SENTRY_DSN "Paste the DSN again (Enter keeps the .env value):"
if confirm "Write SENTRY_DSN to the vyotiqai/vyotiq-agent-v GitHub secret now?"; then
  set_secret SENTRY_DSN "$SENTRY_DSN"
else
  warn "skipped: set it with: gh secret set SENTRY_DSN --repo vyotiqai/vyotiq-agent-v"
fi

# ── 3: Apple notarization ─────────────────────────────────────────────────
stage "Apple notarization"
say "Notarization needs an Apple Developer Program membership; all three values must be set together, otherwise electron-builder builds the DMG unsigned."
open_url "https://account.apple.com"
open_url "https://developer.apple.com/account/resources/team"
step "account.apple.com → Sign-in and security → App-specific passwords → Generate (needs 2FA) → name it vyotiq-release → copy the xxxx-xxxx-… password ONCE, it is never shown again."
ask APPLE_ID "Apple ID email used for notarization:"
ask_secret APPLE_APP_SPECIFIC_PASSWORD "App-specific password:"
step "developer.apple.com → account → Membership / Resources → copy the 10-character Team ID."
ask APPLE_TEAM_ID "Apple Team ID:"
if confirm "Write APPLE_ID, APPLE_APP_SPECIFIC_PASSWORD and APPLE_TEAM_ID to the vyotiqai/vyotiq-agent-v GitHub secrets now?"; then
  set_secret APPLE_ID "$APPLE_ID"
  set_secret APPLE_APP_SPECIFIC_PASSWORD "$APPLE_APP_SPECIFIC_PASSWORD"
  set_secret APPLE_TEAM_ID "$APPLE_TEAM_ID"
else
  warn "skipped: set all three with:"
  note "  gh secret set APPLE_ID --repo vyotiqai/vyotiq-agent-v"
  note "  gh secret set APPLE_APP_SPECIFIC_PASSWORD --repo vyotiqai/vyotiq-agent-v"
  note "  gh secret set APPLE_TEAM_ID --repo vyotiqai/vyotiq-agent-v"
fi
note "Without these the release still ships, unnotarized."

# ── 4: Windows code signing certificate ───────────────────────────────────
stage "Windows code signing certificate"
say "Authenticode needs a real .p12 certificate from a CA, or the Azure Trusted Signing account in stage 5. There is no free path here; with no certificate, skip — unsigned builds are the current state and still install."
open_url "https://github.com/vyotiqai/vyotiq-agent-v/settings/secrets/actions"
ask P12_PATH "Full path to the .p12 file (or Enter to skip this stage):"
if [[ -z "${P12_PATH:-}" ]]; then
  warn "skipped Authenticode: the release stays unsigned"
else
  if [[ ! -f "$P12_PATH" ]]; then
    warn "not found: $P12_PATH"
  elif CSC_LINK=$(base64 < "$P12_PATH" | tr -d '\r\n') && [[ -n "$CSC_LINK" ]]; then
    ask_secret CSC_KEY_PASSWORD "Password that opens the .p12:"
    if confirm "Write CSC_LINK and CSC_KEY_PASSWORD to the vyotiqai/vyotiq-agent-v GitHub secrets now?"; then
      set_secret CSC_LINK "$CSC_LINK"
      set_secret CSC_KEY_PASSWORD "$CSC_KEY_PASSWORD"
    else
      warn "skipped: set both with:"
      note "  gh secret set CSC_LINK --repo vyotiqai/vyotiq-agent-v"
      note "  gh secret set CSC_KEY_PASSWORD --repo vyotiqai/vyotiq-agent-v"
    fi
  else
    warn "could not read $P12_PATH as base64"
  fi
fi
note "CSC_LINK must be base64 of the FILE with no line breaks — a value containing newlines is the classic cause of a silent signing failure."

# ── 5: Azure Trusted Signing ──────────────────────────────────────────────
stage "Azure Trusted Signing"
say "The certificate-free alternative to a .p12; it needs an Azure Trusted Signing account plus an Entra ID app registration. It cannot be used yet — capture the values now so the config change is unblocked."
open_url "https://portal.azure.com"
open_url "https://portal.azure.com/#view/Microsoft_AAD_RegisteredApps/ApplicationsListBlade"
open_url "https://learn.microsoft.com/azure/trusted-signing/quickstart"
step "Entra ID → App registrations → New registration → copy Application (client) ID (GUID) and Directory (tenant) ID (GUID)."
step "Certificates & secrets → New client secret → copy the secret VALUE once."
ask AZURE_CLIENT_ID "Application (client) ID:"
ask AZURE_TENANT_ID "Directory (tenant) ID:"
ask_secret AZURE_CLIENT_SECRET "Client secret value:"
if confirm "Write AZURE_CLIENT_ID, AZURE_TENANT_ID and AZURE_CLIENT_SECRET to the vyotiqai/vyotiq-agent-v GitHub secrets now?"; then
  set_secret AZURE_CLIENT_ID "$AZURE_CLIENT_ID"
  set_secret AZURE_TENANT_ID "$AZURE_TENANT_ID"
  set_secret AZURE_CLIENT_SECRET "$AZURE_CLIENT_SECRET"
else
  warn "skipped: set all three with:"
  note "  gh secret set AZURE_CLIENT_ID --repo vyotiqai/vyotiq-agent-v"
  note "  gh secret set AZURE_TENANT_ID --repo vyotiqai/vyotiq-agent-v"
  note "  gh secret set AZURE_CLIENT_SECRET --repo vyotiqai/vyotiq-agent-v"
fi
note "AZURE_* stays inert until electron-builder.yml gains win.azureSignOptions (v26; win.sign { type: \"azure\" } in v27) — a separate code change, not part of this wizard."

# ── 6: Verify ────────────────────────────────────────────────────────────
stage "Verify"
say "Read-back check only — nothing is uploaded from this stage."
names=(SENTRY_DSN APPLE_ID APPLE_APP_SPECIFIC_PASSWORD APPLE_TEAM_ID CSC_LINK CSC_KEY_PASSWORD AZURE_CLIENT_ID AZURE_TENANT_ID AZURE_CLIENT_SECRET)
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  listing=$(gh secret list --repo vyotiqai/vyotiq-agent-v 2>/dev/null || true)
  set_count=0
  for n in "${names[@]}"; do
    if printf '%s\n' "$listing" | grep -qE "^${n}[[:space:]]"; then
      say "${n}: set"
      set_count=$((set_count + 1))
    else
      say "${n}: MISSING"
    fi
  done
  say "${set_count} of ${#names[@]} set on vyotiqai/vyotiq-agent-v."
else
  warn "gh unavailable — check the secrets page by hand"
fi
if [[ -f "$ENV_FILE" ]]; then
  envkeys=$(grep -Eo '^(SENTRY_DSN|VITE_SENTRY_DSN)' "$ENV_FILE" | sort -u | tr '\n' ' ' || true)
  say "${ENV_FILE} keys present: ${envkeys:-none}"
else
  warn "${ENV_FILE} does not exist yet"
fi
note "Two GitHub secrets are intentionally absent: RELEASES_TOKEN (already set; cross-repo publish) and GITHUB_TOKEN (automatic)."
note "Signing only takes effect once the electron-builder.yml config exists, and publisherName must stay unset until then — re-adding it early breaks Windows auto-update with ERR_UPDATER_INVALID_SIGNATURE."

finish

# finish() ends on a `(( count ))` test that returns 1 when a list is empty, so
# a fully successful run would otherwise report failure.
exit 0
